// Ingest Service Protobuf Definitions
// Provides gRPC service for content ingestion (emails, meetings, attachments)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: ingest/v1/ingest.proto

package ingestv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IngestService_IngestEmail_FullMethodName       = "/penfold.ingest.v1.IngestService/IngestEmail"
	IngestService_IngestAttachment_FullMethodName  = "/penfold.ingest.v1.IngestService/IngestAttachment"
	IngestService_IngestMeeting_FullMethodName     = "/penfold.ingest.v1.IngestService/IngestMeeting"
	IngestService_CreateIngestJob_FullMethodName   = "/penfold.ingest.v1.IngestService/CreateIngestJob"
	IngestService_UpdateJobProgress_FullMethodName = "/penfold.ingest.v1.IngestService/UpdateJobProgress"
	IngestService_CompleteIngestJob_FullMethodName = "/penfold.ingest.v1.IngestService/CompleteIngestJob"
	IngestService_GetIngestJob_FullMethodName      = "/penfold.ingest.v1.IngestService/GetIngestJob"
	IngestService_GetRemainingFiles_FullMethodName = "/penfold.ingest.v1.IngestService/GetRemainingFiles"
	IngestService_RecordIngestError_FullMethodName = "/penfold.ingest.v1.IngestService/RecordIngestError"
)

// IngestServiceClient is the client API for IngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IngestService provides gRPC endpoints for content ingestion.
type IngestServiceClient interface {
	// IngestEmail ingests a single email with duplicate detection.
	IngestEmail(ctx context.Context, in *IngestEmailRequest, opts ...grpc.CallOption) (*IngestEmailResponse, error)
	// IngestAttachment stores an attachment with parent link.
	IngestAttachment(ctx context.Context, in *IngestAttachmentRequest, opts ...grpc.CallOption) (*IngestAttachmentResponse, error)
	// IngestMeeting ingests a full meeting with transcript and chat sources.
	IngestMeeting(ctx context.Context, in *IngestMeetingRequest, opts ...grpc.CallOption) (*IngestMeetingResponse, error)
	// CreateIngestJob creates a batch ingestion job record.
	CreateIngestJob(ctx context.Context, in *CreateIngestJobRequest, opts ...grpc.CallOption) (*CreateIngestJobResponse, error)
	// UpdateJobProgress updates job progress counts.
	UpdateJobProgress(ctx context.Context, in *UpdateJobProgressRequest, opts ...grpc.CallOption) (*UpdateJobProgressResponse, error)
	// CompleteIngestJob marks a job as complete.
	CompleteIngestJob(ctx context.Context, in *CompleteIngestJobRequest, opts ...grpc.CallOption) (*CompleteIngestJobResponse, error)
	// GetIngestJob retrieves job status by ID.
	GetIngestJob(ctx context.Context, in *GetIngestJobRequest, opts ...grpc.CallOption) (*GetIngestJobResponse, error)
	// GetRemainingFiles retrieves unprocessed files for job resume.
	GetRemainingFiles(ctx context.Context, in *GetRemainingFilesRequest, opts ...grpc.CallOption) (*GetRemainingFilesResponse, error)
	// RecordIngestError records a failed file during ingestion.
	RecordIngestError(ctx context.Context, in *RecordIngestErrorRequest, opts ...grpc.CallOption) (*RecordIngestErrorResponse, error)
}

type ingestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestServiceClient(cc grpc.ClientConnInterface) IngestServiceClient {
	return &ingestServiceClient{cc}
}

func (c *ingestServiceClient) IngestEmail(ctx context.Context, in *IngestEmailRequest, opts ...grpc.CallOption) (*IngestEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestEmailResponse)
	err := c.cc.Invoke(ctx, IngestService_IngestEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestServiceClient) IngestAttachment(ctx context.Context, in *IngestAttachmentRequest, opts ...grpc.CallOption) (*IngestAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestAttachmentResponse)
	err := c.cc.Invoke(ctx, IngestService_IngestAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestServiceClient) IngestMeeting(ctx context.Context, in *IngestMeetingRequest, opts ...grpc.CallOption) (*IngestMeetingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestMeetingResponse)
	err := c.cc.Invoke(ctx, IngestService_IngestMeeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestServiceClient) CreateIngestJob(ctx context.Context, in *CreateIngestJobRequest, opts ...grpc.CallOption) (*CreateIngestJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateIngestJobResponse)
	err := c.cc.Invoke(ctx, IngestService_CreateIngestJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestServiceClient) UpdateJobProgress(ctx context.Context, in *UpdateJobProgressRequest, opts ...grpc.CallOption) (*UpdateJobProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateJobProgressResponse)
	err := c.cc.Invoke(ctx, IngestService_UpdateJobProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestServiceClient) CompleteIngestJob(ctx context.Context, in *CompleteIngestJobRequest, opts ...grpc.CallOption) (*CompleteIngestJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteIngestJobResponse)
	err := c.cc.Invoke(ctx, IngestService_CompleteIngestJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestServiceClient) GetIngestJob(ctx context.Context, in *GetIngestJobRequest, opts ...grpc.CallOption) (*GetIngestJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIngestJobResponse)
	err := c.cc.Invoke(ctx, IngestService_GetIngestJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestServiceClient) GetRemainingFiles(ctx context.Context, in *GetRemainingFilesRequest, opts ...grpc.CallOption) (*GetRemainingFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRemainingFilesResponse)
	err := c.cc.Invoke(ctx, IngestService_GetRemainingFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestServiceClient) RecordIngestError(ctx context.Context, in *RecordIngestErrorRequest, opts ...grpc.CallOption) (*RecordIngestErrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordIngestErrorResponse)
	err := c.cc.Invoke(ctx, IngestService_RecordIngestError_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IngestServiceServer is the server API for IngestService service.
// All implementations must embed UnimplementedIngestServiceServer
// for forward compatibility.
//
// IngestService provides gRPC endpoints for content ingestion.
type IngestServiceServer interface {
	// IngestEmail ingests a single email with duplicate detection.
	IngestEmail(context.Context, *IngestEmailRequest) (*IngestEmailResponse, error)
	// IngestAttachment stores an attachment with parent link.
	IngestAttachment(context.Context, *IngestAttachmentRequest) (*IngestAttachmentResponse, error)
	// IngestMeeting ingests a full meeting with transcript and chat sources.
	IngestMeeting(context.Context, *IngestMeetingRequest) (*IngestMeetingResponse, error)
	// CreateIngestJob creates a batch ingestion job record.
	CreateIngestJob(context.Context, *CreateIngestJobRequest) (*CreateIngestJobResponse, error)
	// UpdateJobProgress updates job progress counts.
	UpdateJobProgress(context.Context, *UpdateJobProgressRequest) (*UpdateJobProgressResponse, error)
	// CompleteIngestJob marks a job as complete.
	CompleteIngestJob(context.Context, *CompleteIngestJobRequest) (*CompleteIngestJobResponse, error)
	// GetIngestJob retrieves job status by ID.
	GetIngestJob(context.Context, *GetIngestJobRequest) (*GetIngestJobResponse, error)
	// GetRemainingFiles retrieves unprocessed files for job resume.
	GetRemainingFiles(context.Context, *GetRemainingFilesRequest) (*GetRemainingFilesResponse, error)
	// RecordIngestError records a failed file during ingestion.
	RecordIngestError(context.Context, *RecordIngestErrorRequest) (*RecordIngestErrorResponse, error)
	mustEmbedUnimplementedIngestServiceServer()
}

// UnimplementedIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestServiceServer struct{}

func (UnimplementedIngestServiceServer) IngestEmail(context.Context, *IngestEmailRequest) (*IngestEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngestEmail not implemented")
}
func (UnimplementedIngestServiceServer) IngestAttachment(context.Context, *IngestAttachmentRequest) (*IngestAttachmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngestAttachment not implemented")
}
func (UnimplementedIngestServiceServer) IngestMeeting(context.Context, *IngestMeetingRequest) (*IngestMeetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngestMeeting not implemented")
}
func (UnimplementedIngestServiceServer) CreateIngestJob(context.Context, *CreateIngestJobRequest) (*CreateIngestJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIngestJob not implemented")
}
func (UnimplementedIngestServiceServer) UpdateJobProgress(context.Context, *UpdateJobProgressRequest) (*UpdateJobProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJobProgress not implemented")
}
func (UnimplementedIngestServiceServer) CompleteIngestJob(context.Context, *CompleteIngestJobRequest) (*CompleteIngestJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteIngestJob not implemented")
}
func (UnimplementedIngestServiceServer) GetIngestJob(context.Context, *GetIngestJobRequest) (*GetIngestJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIngestJob not implemented")
}
func (UnimplementedIngestServiceServer) GetRemainingFiles(context.Context, *GetRemainingFilesRequest) (*GetRemainingFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRemainingFiles not implemented")
}
func (UnimplementedIngestServiceServer) RecordIngestError(context.Context, *RecordIngestErrorRequest) (*RecordIngestErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordIngestError not implemented")
}
func (UnimplementedIngestServiceServer) mustEmbedUnimplementedIngestServiceServer() {}
func (UnimplementedIngestServiceServer) testEmbeddedByValue()                       {}

// UnsafeIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestServiceServer will
// result in compilation errors.
type UnsafeIngestServiceServer interface {
	mustEmbedUnimplementedIngestServiceServer()
}

func RegisterIngestServiceServer(s grpc.ServiceRegistrar, srv IngestServiceServer) {
	// If the following call pancis, it indicates UnimplementedIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngestService_ServiceDesc, srv)
}

func _IngestService_IngestEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestServiceServer).IngestEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestService_IngestEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestServiceServer).IngestEmail(ctx, req.(*IngestEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestService_IngestAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestServiceServer).IngestAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestService_IngestAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestServiceServer).IngestAttachment(ctx, req.(*IngestAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestService_IngestMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestServiceServer).IngestMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestService_IngestMeeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestServiceServer).IngestMeeting(ctx, req.(*IngestMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestService_CreateIngestJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIngestJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestServiceServer).CreateIngestJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestService_CreateIngestJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestServiceServer).CreateIngestJob(ctx, req.(*CreateIngestJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestService_UpdateJobProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestServiceServer).UpdateJobProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestService_UpdateJobProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestServiceServer).UpdateJobProgress(ctx, req.(*UpdateJobProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestService_CompleteIngestJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteIngestJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestServiceServer).CompleteIngestJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestService_CompleteIngestJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestServiceServer).CompleteIngestJob(ctx, req.(*CompleteIngestJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestService_GetIngestJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIngestJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestServiceServer).GetIngestJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestService_GetIngestJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestServiceServer).GetIngestJob(ctx, req.(*GetIngestJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestService_GetRemainingFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRemainingFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestServiceServer).GetRemainingFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestService_GetRemainingFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestServiceServer).GetRemainingFiles(ctx, req.(*GetRemainingFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestService_RecordIngestError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordIngestErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestServiceServer).RecordIngestError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestService_RecordIngestError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestServiceServer).RecordIngestError(ctx, req.(*RecordIngestErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IngestService_ServiceDesc is the grpc.ServiceDesc for IngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "penfold.ingest.v1.IngestService",
	HandlerType: (*IngestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestEmail",
			Handler:    _IngestService_IngestEmail_Handler,
		},
		{
			MethodName: "IngestAttachment",
			Handler:    _IngestService_IngestAttachment_Handler,
		},
		{
			MethodName: "IngestMeeting",
			Handler:    _IngestService_IngestMeeting_Handler,
		},
		{
			MethodName: "CreateIngestJob",
			Handler:    _IngestService_CreateIngestJob_Handler,
		},
		{
			MethodName: "UpdateJobProgress",
			Handler:    _IngestService_UpdateJobProgress_Handler,
		},
		{
			MethodName: "CompleteIngestJob",
			Handler:    _IngestService_CompleteIngestJob_Handler,
		},
		{
			MethodName: "GetIngestJob",
			Handler:    _IngestService_GetIngestJob_Handler,
		},
		{
			MethodName: "GetRemainingFiles",
			Handler:    _IngestService_GetRemainingFiles_Handler,
		},
		{
			MethodName: "RecordIngestError",
			Handler:    _IngestService_RecordIngestError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ingest/v1/ingest.proto",
}
