// Review Service Protobuf Definitions
// Provides gRPC service for managing daily review items and user review actions

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: reviewpb/review.proto

package reviewpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReviewStatus represents the current state of a review item.
type ReviewStatus int32

const (
	// Default value. Should not be used explicitly.
	ReviewStatus_REVIEW_STATUS_UNSPECIFIED ReviewStatus = 0
	// Item is awaiting review by the user.
	ReviewStatus_REVIEW_STATUS_PENDING ReviewStatus = 1
	// Item has been reviewed and approved by the user.
	ReviewStatus_REVIEW_STATUS_APPROVED ReviewStatus = 2
	// Item has been reviewed and rejected/dismissed by the user.
	ReviewStatus_REVIEW_STATUS_REJECTED ReviewStatus = 3
	// Item has been deferred for later review.
	ReviewStatus_REVIEW_STATUS_DEFERRED ReviewStatus = 4
)

// Enum value maps for ReviewStatus.
var (
	ReviewStatus_name = map[int32]string{
		0: "REVIEW_STATUS_UNSPECIFIED",
		1: "REVIEW_STATUS_PENDING",
		2: "REVIEW_STATUS_APPROVED",
		3: "REVIEW_STATUS_REJECTED",
		4: "REVIEW_STATUS_DEFERRED",
	}
	ReviewStatus_value = map[string]int32{
		"REVIEW_STATUS_UNSPECIFIED": 0,
		"REVIEW_STATUS_PENDING":     1,
		"REVIEW_STATUS_APPROVED":    2,
		"REVIEW_STATUS_REJECTED":    3,
		"REVIEW_STATUS_DEFERRED":    4,
	}
)

func (x ReviewStatus) Enum() *ReviewStatus {
	p := new(ReviewStatus)
	*p = x
	return p
}

func (x ReviewStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReviewStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_reviewpb_review_proto_enumTypes[0].Descriptor()
}

func (ReviewStatus) Type() protoreflect.EnumType {
	return &file_reviewpb_review_proto_enumTypes[0]
}

func (x ReviewStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReviewStatus.Descriptor instead.
func (ReviewStatus) EnumDescriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{0}
}

// Priority indicates the urgency level of a review item.
type Priority int32

const (
	// Default value. Should not be used explicitly.
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	// Low priority item that can be addressed at leisure.
	Priority_PRIORITY_LOW Priority = 1
	// Medium priority item requiring attention in a reasonable timeframe.
	Priority_PRIORITY_MEDIUM Priority = 2
	// High priority item requiring prompt attention.
	Priority_PRIORITY_HIGH Priority = 3
	// Urgent item requiring immediate attention.
	Priority_PRIORITY_URGENT Priority = 4
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_MEDIUM",
		3: "PRIORITY_HIGH",
		4: "PRIORITY_URGENT",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_MEDIUM":      2,
		"PRIORITY_HIGH":        3,
		"PRIORITY_URGENT":      4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_reviewpb_review_proto_enumTypes[1].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_reviewpb_review_proto_enumTypes[1]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{1}
}

// ActionType represents the type of action taken on a review item.
type ActionType int32

const (
	// Default value. Should not be used explicitly.
	ActionType_ACTION_TYPE_UNSPECIFIED ActionType = 0
	// Item was approved.
	ActionType_ACTION_TYPE_APPROVE ActionType = 1
	// Item was rejected.
	ActionType_ACTION_TYPE_REJECT ActionType = 2
	// Item was deferred.
	ActionType_ACTION_TYPE_DEFER ActionType = 3
	// Previous action was undone.
	ActionType_ACTION_TYPE_UNDO ActionType = 4
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "ACTION_TYPE_APPROVE",
		2: "ACTION_TYPE_REJECT",
		3: "ACTION_TYPE_DEFER",
		4: "ACTION_TYPE_UNDO",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED": 0,
		"ACTION_TYPE_APPROVE":     1,
		"ACTION_TYPE_REJECT":      2,
		"ACTION_TYPE_DEFER":       3,
		"ACTION_TYPE_UNDO":        4,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_reviewpb_review_proto_enumTypes[2].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_reviewpb_review_proto_enumTypes[2]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{2}
}

// ReviewItem represents a single item requiring user review.
type ReviewItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the review item.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Type of content being reviewed (e.g., "email", "document", "relationship", "task").
	ContentType string `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Brief summary of the content for quick scanning.
	ContentSummary string `protobuf:"bytes,3,opt,name=content_summary,json=contentSummary,proto3" json:"content_summary,omitempty"`
	// Source system or connector that generated this item (e.g., "gmail", "slack", "manual").
	Source string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	// Priority level of the review item.
	Priority Priority `protobuf:"varint,5,opt,name=priority,proto3,enum=penfold.processing.review.v1.Priority" json:"priority,omitempty"`
	// Current review status.
	Status ReviewStatus `protobuf:"varint,6,opt,name=status,proto3,enum=penfold.processing.review.v1.ReviewStatus" json:"status,omitempty"`
	// When the review item was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When the review item was last updated.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Reference to the underlying content entity.
	ContentId string `protobuf:"bytes,9,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	// Optional category for grouping items (e.g., "communications", "tasks", "insights").
	Category string `protobuf:"bytes,10,opt,name=category,proto3" json:"category,omitempty"`
	// Additional metadata as key-value pairs.
	Metadata      map[string]string `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewItem) Reset() {
	*x = ReviewItem{}
	mi := &file_reviewpb_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewItem) ProtoMessage() {}

func (x *ReviewItem) ProtoReflect() protoreflect.Message {
	mi := &file_reviewpb_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewItem.ProtoReflect.Descriptor instead.
func (*ReviewItem) Descriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{0}
}

func (x *ReviewItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReviewItem) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ReviewItem) GetContentSummary() string {
	if x != nil {
		return x.ContentSummary
	}
	return ""
}

func (x *ReviewItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ReviewItem) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *ReviewItem) GetStatus() ReviewStatus {
	if x != nil {
		return x.Status
	}
	return ReviewStatus_REVIEW_STATUS_UNSPECIFIED
}

func (x *ReviewItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ReviewItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ReviewItem) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *ReviewItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ReviewItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ReviewAction records an action taken on a review item.
// Used for the undo stack and audit trail.
type ReviewAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the action.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Identifier of the review item this action was taken on.
	ItemId string `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	// Type of action taken.
	ActionType ActionType `protobuf:"varint,3,opt,name=action_type,json=actionType,proto3,enum=penfold.processing.review.v1.ActionType" json:"action_type,omitempty"`
	// Previous status before the action was taken.
	PreviousStatus ReviewStatus `protobuf:"varint,4,opt,name=previous_status,json=previousStatus,proto3,enum=penfold.processing.review.v1.ReviewStatus" json:"previous_status,omitempty"`
	// New status after the action was taken.
	NewStatus ReviewStatus `protobuf:"varint,5,opt,name=new_status,json=newStatus,proto3,enum=penfold.processing.review.v1.ReviewStatus" json:"new_status,omitempty"`
	// When the action was performed.
	PerformedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=performed_at,json=performedAt,proto3" json:"performed_at,omitempty"`
	// Optional reason or note provided with the action.
	Reason string `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	// Whether this action can be undone.
	Undoable      bool `protobuf:"varint,8,opt,name=undoable,proto3" json:"undoable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewAction) Reset() {
	*x = ReviewAction{}
	mi := &file_reviewpb_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewAction) ProtoMessage() {}

func (x *ReviewAction) ProtoReflect() protoreflect.Message {
	mi := &file_reviewpb_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewAction.ProtoReflect.Descriptor instead.
func (*ReviewAction) Descriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{1}
}

func (x *ReviewAction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReviewAction) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ReviewAction) GetActionType() ActionType {
	if x != nil {
		return x.ActionType
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *ReviewAction) GetPreviousStatus() ReviewStatus {
	if x != nil {
		return x.PreviousStatus
	}
	return ReviewStatus_REVIEW_STATUS_UNSPECIFIED
}

func (x *ReviewAction) GetNewStatus() ReviewStatus {
	if x != nil {
		return x.NewStatus
	}
	return ReviewStatus_REVIEW_STATUS_UNSPECIFIED
}

func (x *ReviewAction) GetPerformedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PerformedAt
	}
	return nil
}

func (x *ReviewAction) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReviewAction) GetUndoable() bool {
	if x != nil {
		return x.Undoable
	}
	return false
}

// ReviewCategory groups review items by category for the daily review.
type ReviewCategory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Category name (e.g., "communications", "tasks", "insights", "relationships").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human-readable display name for the category.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Review items in this category.
	Items []*ReviewItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	// Count of items in this category.
	ItemCount     int32 `protobuf:"varint,4,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewCategory) Reset() {
	*x = ReviewCategory{}
	mi := &file_reviewpb_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewCategory) ProtoMessage() {}

func (x *ReviewCategory) ProtoReflect() protoreflect.Message {
	mi := &file_reviewpb_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewCategory.ProtoReflect.Descriptor instead.
func (*ReviewCategory) Descriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{2}
}

func (x *ReviewCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReviewCategory) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ReviewCategory) GetItems() []*ReviewItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ReviewCategory) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

// DailyReview represents the complete daily review for a user.
type DailyReview struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Date of the review in YYYY-MM-DD format.
	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	// Review items grouped by category.
	Categories []*ReviewCategory `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	// Total number of pending items.
	TotalPending int32 `protobuf:"varint,3,opt,name=total_pending,json=totalPending,proto3" json:"total_pending,omitempty"`
	// Number of high priority and urgent items.
	HighPriorityCount int32 `protobuf:"varint,4,opt,name=high_priority_count,json=highPriorityCount,proto3" json:"high_priority_count,omitempty"`
	// Number of items already processed today.
	ProcessedToday int32 `protobuf:"varint,5,opt,name=processed_today,json=processedToday,proto3" json:"processed_today,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DailyReview) Reset() {
	*x = DailyReview{}
	mi := &file_reviewpb_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyReview) ProtoMessage() {}

func (x *DailyReview) ProtoReflect() protoreflect.Message {
	mi := &file_reviewpb_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyReview.ProtoReflect.Descriptor instead.
func (*DailyReview) Descriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{3}
}

func (x *DailyReview) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyReview) GetCategories() []*ReviewCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *DailyReview) GetTotalPending() int32 {
	if x != nil {
		return x.TotalPending
	}
	return 0
}

func (x *DailyReview) GetHighPriorityCount() int32 {
	if x != nil {
		return x.HighPriorityCount
	}
	return 0
}

func (x *DailyReview) GetProcessedToday() int32 {
	if x != nil {
		return x.ProcessedToday
	}
	return 0
}

// GetDailyReviewRequest retrieves today's review items.
type GetDailyReviewRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional tenant ID for multi-tenancy support.
	TenantId *string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	// Optional date override (defaults to today). Format: YYYY-MM-DD.
	Date *string `protobuf:"bytes,2,opt,name=date,proto3,oneof" json:"date,omitempty"`
	// Whether to include already processed items from today.
	IncludeProcessed bool `protobuf:"varint,3,opt,name=include_processed,json=includeProcessed,proto3" json:"include_processed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetDailyReviewRequest) Reset() {
	*x = GetDailyReviewRequest{}
	mi := &file_reviewpb_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyReviewRequest) ProtoMessage() {}

func (x *GetDailyReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reviewpb_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyReviewRequest.ProtoReflect.Descriptor instead.
func (*GetDailyReviewRequest) Descriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{4}
}

func (x *GetDailyReviewRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *GetDailyReviewRequest) GetDate() string {
	if x != nil && x.Date != nil {
		return *x.Date
	}
	return ""
}

func (x *GetDailyReviewRequest) GetIncludeProcessed() bool {
	if x != nil {
		return x.IncludeProcessed
	}
	return false
}

// GetDailyReviewResponse contains the daily review.
type GetDailyReviewResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The daily review with categorized items.
	Review        *DailyReview `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyReviewResponse) Reset() {
	*x = GetDailyReviewResponse{}
	mi := &file_reviewpb_review_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyReviewResponse) ProtoMessage() {}

func (x *GetDailyReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reviewpb_review_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyReviewResponse.ProtoReflect.Descriptor instead.
func (*GetDailyReviewResponse) Descriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{5}
}

func (x *GetDailyReviewResponse) GetReview() *DailyReview {
	if x != nil {
		return x.Review
	}
	return nil
}

// GetReviewItemRequest retrieves a single review item.
type GetReviewItemRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the review item.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Optional tenant ID for multi-tenancy support.
	TenantId      *string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewItemRequest) Reset() {
	*x = GetReviewItemRequest{}
	mi := &file_reviewpb_review_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewItemRequest) ProtoMessage() {}

func (x *GetReviewItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reviewpb_review_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewItemRequest.ProtoReflect.Descriptor instead.
func (*GetReviewItemRequest) Descriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{6}
}

func (x *GetReviewItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetReviewItemRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

// GetReviewItemResponse contains the requested review item.
type GetReviewItemResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested review item.
	Item *ReviewItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	// Recent actions taken on this item (most recent first).
	RecentActions []*ReviewAction `protobuf:"bytes,2,rep,name=recent_actions,json=recentActions,proto3" json:"recent_actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewItemResponse) Reset() {
	*x = GetReviewItemResponse{}
	mi := &file_reviewpb_review_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewItemResponse) ProtoMessage() {}

func (x *GetReviewItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reviewpb_review_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewItemResponse.ProtoReflect.Descriptor instead.
func (*GetReviewItemResponse) Descriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{7}
}

func (x *GetReviewItemResponse) GetItem() *ReviewItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *GetReviewItemResponse) GetRecentActions() []*ReviewAction {
	if x != nil {
		return x.RecentActions
	}
	return nil
}

// ListReviewItemsRequest retrieves a filtered list of review items.
type ListReviewItemsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional tenant ID for multi-tenancy support.
	TenantId *string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	// Filter by review status.
	Statuses []ReviewStatus `protobuf:"varint,2,rep,packed,name=statuses,proto3,enum=penfold.processing.review.v1.ReviewStatus" json:"statuses,omitempty"`
	// Filter by priority levels.
	Priorities []Priority `protobuf:"varint,3,rep,packed,name=priorities,proto3,enum=penfold.processing.review.v1.Priority" json:"priorities,omitempty"`
	// Filter by content types.
	ContentTypes []string `protobuf:"bytes,4,rep,name=content_types,json=contentTypes,proto3" json:"content_types,omitempty"`
	// Filter by sources.
	Sources []string `protobuf:"bytes,5,rep,name=sources,proto3" json:"sources,omitempty"`
	// Filter by categories.
	Categories []string `protobuf:"bytes,6,rep,name=categories,proto3" json:"categories,omitempty"`
	// Filter by creation date range.
	CreatedAfter  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_after,json=createdAfter,proto3,oneof" json:"created_after,omitempty"`
	CreatedBefore *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_before,json=createdBefore,proto3,oneof" json:"created_before,omitempty"`
	// Maximum number of results to return (default: 50, max: 500).
	PageSize int32 `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Pagination token from previous response.
	PageToken string `protobuf:"bytes,10,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Sort order: "created_at_asc", "created_at_desc", "priority_desc", "priority_asc".
	SortOrder     string `protobuf:"bytes,11,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewItemsRequest) Reset() {
	*x = ListReviewItemsRequest{}
	mi := &file_reviewpb_review_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewItemsRequest) ProtoMessage() {}

func (x *ListReviewItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reviewpb_review_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewItemsRequest.ProtoReflect.Descriptor instead.
func (*ListReviewItemsRequest) Descriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{8}
}

func (x *ListReviewItemsRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *ListReviewItemsRequest) GetStatuses() []ReviewStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *ListReviewItemsRequest) GetPriorities() []Priority {
	if x != nil {
		return x.Priorities
	}
	return nil
}

func (x *ListReviewItemsRequest) GetContentTypes() []string {
	if x != nil {
		return x.ContentTypes
	}
	return nil
}

func (x *ListReviewItemsRequest) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ListReviewItemsRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ListReviewItemsRequest) GetCreatedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAfter
	}
	return nil
}

func (x *ListReviewItemsRequest) GetCreatedBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedBefore
	}
	return nil
}

func (x *ListReviewItemsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListReviewItemsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListReviewItemsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

// ListReviewItemsResponse contains a paginated list of review items.
type ListReviewItemsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of review items matching the filters.
	Items []*ReviewItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Token for fetching the next page (empty if no more results).
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total count of items matching the query.
	TotalCount    *int64 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3,oneof" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewItemsResponse) Reset() {
	*x = ListReviewItemsResponse{}
	mi := &file_reviewpb_review_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewItemsResponse) ProtoMessage() {}

func (x *ListReviewItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reviewpb_review_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewItemsResponse.ProtoReflect.Descriptor instead.
func (*ListReviewItemsResponse) Descriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{9}
}

func (x *ListReviewItemsResponse) GetItems() []*ReviewItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListReviewItemsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListReviewItemsResponse) GetTotalCount() int64 {
	if x != nil && x.TotalCount != nil {
		return *x.TotalCount
	}
	return 0
}

// ApproveItemRequest marks a review item as approved.
type ApproveItemRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the review item to approve.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Optional tenant ID for multi-tenancy support.
	TenantId *string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	// Optional note or comment about the approval.
	Note          string `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveItemRequest) Reset() {
	*x = ApproveItemRequest{}
	mi := &file_reviewpb_review_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveItemRequest) ProtoMessage() {}

func (x *ApproveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reviewpb_review_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveItemRequest.ProtoReflect.Descriptor instead.
func (*ApproveItemRequest) Descriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{10}
}

func (x *ApproveItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApproveItemRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *ApproveItemRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// ApproveItemResponse confirms the approval.
type ApproveItemResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated review item.
	Item *ReviewItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	// The action record for this approval.
	Action        *ReviewAction `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveItemResponse) Reset() {
	*x = ApproveItemResponse{}
	mi := &file_reviewpb_review_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveItemResponse) ProtoMessage() {}

func (x *ApproveItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reviewpb_review_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveItemResponse.ProtoReflect.Descriptor instead.
func (*ApproveItemResponse) Descriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{11}
}

func (x *ApproveItemResponse) GetItem() *ReviewItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ApproveItemResponse) GetAction() *ReviewAction {
	if x != nil {
		return x.Action
	}
	return nil
}

// RejectItemRequest marks a review item as rejected.
type RejectItemRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the review item to reject.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Optional tenant ID for multi-tenancy support.
	TenantId *string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	// Reason for rejection.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectItemRequest) Reset() {
	*x = RejectItemRequest{}
	mi := &file_reviewpb_review_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectItemRequest) ProtoMessage() {}

func (x *RejectItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reviewpb_review_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectItemRequest.ProtoReflect.Descriptor instead.
func (*RejectItemRequest) Descriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{12}
}

func (x *RejectItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RejectItemRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *RejectItemRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// RejectItemResponse confirms the rejection.
type RejectItemResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated review item.
	Item *ReviewItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	// The action record for this rejection.
	Action        *ReviewAction `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectItemResponse) Reset() {
	*x = RejectItemResponse{}
	mi := &file_reviewpb_review_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectItemResponse) ProtoMessage() {}

func (x *RejectItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reviewpb_review_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectItemResponse.ProtoReflect.Descriptor instead.
func (*RejectItemResponse) Descriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{13}
}

func (x *RejectItemResponse) GetItem() *ReviewItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *RejectItemResponse) GetAction() *ReviewAction {
	if x != nil {
		return x.Action
	}
	return nil
}

// UndoActionRequest reverses the last action on a review item.
type UndoActionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the review item to undo.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Optional tenant ID for multi-tenancy support.
	TenantId      *string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndoActionRequest) Reset() {
	*x = UndoActionRequest{}
	mi := &file_reviewpb_review_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndoActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndoActionRequest) ProtoMessage() {}

func (x *UndoActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reviewpb_review_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndoActionRequest.ProtoReflect.Descriptor instead.
func (*UndoActionRequest) Descriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{14}
}

func (x *UndoActionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UndoActionRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

// UndoActionResponse confirms the undo operation.
type UndoActionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated review item (restored to previous state).
	Item *ReviewItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	// The action that was undone.
	UndoneAction *ReviewAction `protobuf:"bytes,2,opt,name=undone_action,json=undoneAction,proto3" json:"undone_action,omitempty"`
	// Whether there are more actions that can be undone.
	CanUndoMore   bool `protobuf:"varint,3,opt,name=can_undo_more,json=canUndoMore,proto3" json:"can_undo_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndoActionResponse) Reset() {
	*x = UndoActionResponse{}
	mi := &file_reviewpb_review_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndoActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndoActionResponse) ProtoMessage() {}

func (x *UndoActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reviewpb_review_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndoActionResponse.ProtoReflect.Descriptor instead.
func (*UndoActionResponse) Descriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{15}
}

func (x *UndoActionResponse) GetItem() *ReviewItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *UndoActionResponse) GetUndoneAction() *ReviewAction {
	if x != nil {
		return x.UndoneAction
	}
	return nil
}

func (x *UndoActionResponse) GetCanUndoMore() bool {
	if x != nil {
		return x.CanUndoMore
	}
	return false
}

// GetReviewStatsRequest retrieves review statistics.
type GetReviewStatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional tenant ID for multi-tenancy support.
	TenantId *string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	// Time range for statistics (defaults to last 30 days).
	FromTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from_time,json=fromTime,proto3,oneof" json:"from_time,omitempty"`
	ToTime        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to_time,json=toTime,proto3,oneof" json:"to_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewStatsRequest) Reset() {
	*x = GetReviewStatsRequest{}
	mi := &file_reviewpb_review_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewStatsRequest) ProtoMessage() {}

func (x *GetReviewStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reviewpb_review_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewStatsRequest.ProtoReflect.Descriptor instead.
func (*GetReviewStatsRequest) Descriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{16}
}

func (x *GetReviewStatsRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *GetReviewStatsRequest) GetFromTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FromTime
	}
	return nil
}

func (x *GetReviewStatsRequest) GetToTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ToTime
	}
	return nil
}

// GetReviewStatsResponse contains review statistics.
type GetReviewStatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of items currently pending review.
	PendingCount int64 `protobuf:"varint,1,opt,name=pending_count,json=pendingCount,proto3" json:"pending_count,omitempty"`
	// Number of items approved in the time range.
	ApprovedCount int64 `protobuf:"varint,2,opt,name=approved_count,json=approvedCount,proto3" json:"approved_count,omitempty"`
	// Number of items rejected in the time range.
	RejectedCount int64 `protobuf:"varint,3,opt,name=rejected_count,json=rejectedCount,proto3" json:"rejected_count,omitempty"`
	// Number of items deferred in the time range.
	DeferredCount int64 `protobuf:"varint,4,opt,name=deferred_count,json=deferredCount,proto3" json:"deferred_count,omitempty"`
	// Breakdown by priority.
	ByPriority map[string]int64 `protobuf:"bytes,5,rep,name=by_priority,json=byPriority,proto3" json:"by_priority,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Breakdown by content type.
	ByContentType map[string]int64 `protobuf:"bytes,6,rep,name=by_content_type,json=byContentType,proto3" json:"by_content_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Breakdown by source.
	BySource map[string]int64 `protobuf:"bytes,7,rep,name=by_source,json=bySource,proto3" json:"by_source,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Breakdown by category.
	ByCategory map[string]int64 `protobuf:"bytes,8,rep,name=by_category,json=byCategory,proto3" json:"by_category,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Average time from creation to review (in seconds).
	AvgReviewTimeSeconds float64 `protobuf:"fixed64,9,opt,name=avg_review_time_seconds,json=avgReviewTimeSeconds,proto3" json:"avg_review_time_seconds,omitempty"`
	// Daily review counts for the time range.
	DailyCounts   []*DailyReviewCount `protobuf:"bytes,10,rep,name=daily_counts,json=dailyCounts,proto3" json:"daily_counts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewStatsResponse) Reset() {
	*x = GetReviewStatsResponse{}
	mi := &file_reviewpb_review_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewStatsResponse) ProtoMessage() {}

func (x *GetReviewStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reviewpb_review_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewStatsResponse.ProtoReflect.Descriptor instead.
func (*GetReviewStatsResponse) Descriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{17}
}

func (x *GetReviewStatsResponse) GetPendingCount() int64 {
	if x != nil {
		return x.PendingCount
	}
	return 0
}

func (x *GetReviewStatsResponse) GetApprovedCount() int64 {
	if x != nil {
		return x.ApprovedCount
	}
	return 0
}

func (x *GetReviewStatsResponse) GetRejectedCount() int64 {
	if x != nil {
		return x.RejectedCount
	}
	return 0
}

func (x *GetReviewStatsResponse) GetDeferredCount() int64 {
	if x != nil {
		return x.DeferredCount
	}
	return 0
}

func (x *GetReviewStatsResponse) GetByPriority() map[string]int64 {
	if x != nil {
		return x.ByPriority
	}
	return nil
}

func (x *GetReviewStatsResponse) GetByContentType() map[string]int64 {
	if x != nil {
		return x.ByContentType
	}
	return nil
}

func (x *GetReviewStatsResponse) GetBySource() map[string]int64 {
	if x != nil {
		return x.BySource
	}
	return nil
}

func (x *GetReviewStatsResponse) GetByCategory() map[string]int64 {
	if x != nil {
		return x.ByCategory
	}
	return nil
}

func (x *GetReviewStatsResponse) GetAvgReviewTimeSeconds() float64 {
	if x != nil {
		return x.AvgReviewTimeSeconds
	}
	return 0
}

func (x *GetReviewStatsResponse) GetDailyCounts() []*DailyReviewCount {
	if x != nil {
		return x.DailyCounts
	}
	return nil
}

// DailyReviewCount provides review counts for a single day.
type DailyReviewCount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Date in YYYY-MM-DD format.
	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	// Number of items created on this day.
	Created int64 `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	// Number of items reviewed on this day.
	Reviewed int64 `protobuf:"varint,3,opt,name=reviewed,proto3" json:"reviewed,omitempty"`
	// Number approved.
	Approved int64 `protobuf:"varint,4,opt,name=approved,proto3" json:"approved,omitempty"`
	// Number rejected.
	Rejected      int64 `protobuf:"varint,5,opt,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyReviewCount) Reset() {
	*x = DailyReviewCount{}
	mi := &file_reviewpb_review_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyReviewCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyReviewCount) ProtoMessage() {}

func (x *DailyReviewCount) ProtoReflect() protoreflect.Message {
	mi := &file_reviewpb_review_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyReviewCount.ProtoReflect.Descriptor instead.
func (*DailyReviewCount) Descriptor() ([]byte, []int) {
	return file_reviewpb_review_proto_rawDescGZIP(), []int{18}
}

func (x *DailyReviewCount) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyReviewCount) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *DailyReviewCount) GetReviewed() int64 {
	if x != nil {
		return x.Reviewed
	}
	return 0
}

func (x *DailyReviewCount) GetApproved() int64 {
	if x != nil {
		return x.Approved
	}
	return 0
}

func (x *DailyReviewCount) GetRejected() int64 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

var File_reviewpb_review_proto protoreflect.FileDescriptor

const file_reviewpb_review_proto_rawDesc = "" +
	"\n" +
	"\x15reviewpb/review.proto\x12\x1cpenfold.processing.review.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x04\n" +
	"\n" +
	"ReviewItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12'\n" +
	"\x0fcontent_summary\x18\x03 \x01(\tR\x0econtentSummary\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12B\n" +
	"\bpriority\x18\x05 \x01(\x0e2&.penfold.processing.review.v1.PriorityR\bpriority\x12B\n" +
	"\x06status\x18\x06 \x01(\x0e2*.penfold.processing.review.v1.ReviewStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"content_id\x18\t \x01(\tR\tcontentId\x12\x1a\n" +
	"\bcategory\x18\n" +
	" \x01(\tR\bcategory\x12R\n" +
	"\bmetadata\x18\v \x03(\v26.penfold.processing.review.v1.ReviewItem.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x95\x03\n" +
	"\fReviewAction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12I\n" +
	"\vaction_type\x18\x03 \x01(\x0e2(.penfold.processing.review.v1.ActionTypeR\n" +
	"actionType\x12S\n" +
	"\x0fprevious_status\x18\x04 \x01(\x0e2*.penfold.processing.review.v1.ReviewStatusR\x0epreviousStatus\x12I\n" +
	"\n" +
	"new_status\x18\x05 \x01(\x0e2*.penfold.processing.review.v1.ReviewStatusR\tnewStatus\x12=\n" +
	"\fperformed_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vperformedAt\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12\x1a\n" +
	"\bundoable\x18\b \x01(\bR\bundoable\"\xa6\x01\n" +
	"\x0eReviewCategory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12>\n" +
	"\x05items\x18\x03 \x03(\v2(.penfold.processing.review.v1.ReviewItemR\x05items\x12\x1d\n" +
	"\n" +
	"item_count\x18\x04 \x01(\x05R\titemCount\"\xed\x01\n" +
	"\vDailyReview\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12L\n" +
	"\n" +
	"categories\x18\x02 \x03(\v2,.penfold.processing.review.v1.ReviewCategoryR\n" +
	"categories\x12#\n" +
	"\rtotal_pending\x18\x03 \x01(\x05R\ftotalPending\x12.\n" +
	"\x13high_priority_count\x18\x04 \x01(\x05R\x11highPriorityCount\x12'\n" +
	"\x0fprocessed_today\x18\x05 \x01(\x05R\x0eprocessedToday\"\x96\x01\n" +
	"\x15GetDailyReviewRequest\x12 \n" +
	"\ttenant_id\x18\x01 \x01(\tH\x00R\btenantId\x88\x01\x01\x12\x17\n" +
	"\x04date\x18\x02 \x01(\tH\x01R\x04date\x88\x01\x01\x12+\n" +
	"\x11include_processed\x18\x03 \x01(\bR\x10includeProcessedB\f\n" +
	"\n" +
	"_tenant_idB\a\n" +
	"\x05_date\"[\n" +
	"\x16GetDailyReviewResponse\x12A\n" +
	"\x06review\x18\x01 \x01(\v2).penfold.processing.review.v1.DailyReviewR\x06review\"V\n" +
	"\x14GetReviewItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\ttenant_id\x18\x02 \x01(\tH\x00R\btenantId\x88\x01\x01B\f\n" +
	"\n" +
	"_tenant_id\"\xa8\x01\n" +
	"\x15GetReviewItemResponse\x12<\n" +
	"\x04item\x18\x01 \x01(\v2(.penfold.processing.review.v1.ReviewItemR\x04item\x12Q\n" +
	"\x0erecent_actions\x18\x02 \x03(\v2*.penfold.processing.review.v1.ReviewActionR\rrecentActions\"\xc5\x04\n" +
	"\x16ListReviewItemsRequest\x12 \n" +
	"\ttenant_id\x18\x01 \x01(\tH\x00R\btenantId\x88\x01\x01\x12F\n" +
	"\bstatuses\x18\x02 \x03(\x0e2*.penfold.processing.review.v1.ReviewStatusR\bstatuses\x12F\n" +
	"\n" +
	"priorities\x18\x03 \x03(\x0e2&.penfold.processing.review.v1.PriorityR\n" +
	"priorities\x12#\n" +
	"\rcontent_types\x18\x04 \x03(\tR\fcontentTypes\x12\x18\n" +
	"\asources\x18\x05 \x03(\tR\asources\x12\x1e\n" +
	"\n" +
	"categories\x18\x06 \x03(\tR\n" +
	"categories\x12D\n" +
	"\rcreated_after\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x01R\fcreatedAfter\x88\x01\x01\x12F\n" +
	"\x0ecreated_before\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x02R\rcreatedBefore\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\t \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\n" +
	" \x01(\tR\tpageToken\x12\x1d\n" +
	"\n" +
	"sort_order\x18\v \x01(\tR\tsortOrderB\f\n" +
	"\n" +
	"_tenant_idB\x10\n" +
	"\x0e_created_afterB\x11\n" +
	"\x0f_created_before\"\xb7\x01\n" +
	"\x17ListReviewItemsResponse\x12>\n" +
	"\x05items\x18\x01 \x03(\v2(.penfold.processing.review.v1.ReviewItemR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12$\n" +
	"\vtotal_count\x18\x03 \x01(\x03H\x00R\n" +
	"totalCount\x88\x01\x01B\x0e\n" +
	"\f_total_count\"h\n" +
	"\x12ApproveItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\ttenant_id\x18\x02 \x01(\tH\x00R\btenantId\x88\x01\x01\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04noteB\f\n" +
	"\n" +
	"_tenant_id\"\x97\x01\n" +
	"\x13ApproveItemResponse\x12<\n" +
	"\x04item\x18\x01 \x01(\v2(.penfold.processing.review.v1.ReviewItemR\x04item\x12B\n" +
	"\x06action\x18\x02 \x01(\v2*.penfold.processing.review.v1.ReviewActionR\x06action\"k\n" +
	"\x11RejectItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\ttenant_id\x18\x02 \x01(\tH\x00R\btenantId\x88\x01\x01\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reasonB\f\n" +
	"\n" +
	"_tenant_id\"\x96\x01\n" +
	"\x12RejectItemResponse\x12<\n" +
	"\x04item\x18\x01 \x01(\v2(.penfold.processing.review.v1.ReviewItemR\x04item\x12B\n" +
	"\x06action\x18\x02 \x01(\v2*.penfold.processing.review.v1.ReviewActionR\x06action\"S\n" +
	"\x11UndoActionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\ttenant_id\x18\x02 \x01(\tH\x00R\btenantId\x88\x01\x01B\f\n" +
	"\n" +
	"_tenant_id\"\xc7\x01\n" +
	"\x12UndoActionResponse\x12<\n" +
	"\x04item\x18\x01 \x01(\v2(.penfold.processing.review.v1.ReviewItemR\x04item\x12O\n" +
	"\rundone_action\x18\x02 \x01(\v2*.penfold.processing.review.v1.ReviewActionR\fundoneAction\x12\"\n" +
	"\rcan_undo_more\x18\x03 \x01(\bR\vcanUndoMore\"\xd9\x01\n" +
	"\x15GetReviewStatsRequest\x12 \n" +
	"\ttenant_id\x18\x01 \x01(\tH\x00R\btenantId\x88\x01\x01\x12<\n" +
	"\tfrom_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\bfromTime\x88\x01\x01\x128\n" +
	"\ato_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x06toTime\x88\x01\x01B\f\n" +
	"\n" +
	"_tenant_idB\f\n" +
	"\n" +
	"_from_timeB\n" +
	"\n" +
	"\b_to_time\"\xd9\a\n" +
	"\x16GetReviewStatsResponse\x12#\n" +
	"\rpending_count\x18\x01 \x01(\x03R\fpendingCount\x12%\n" +
	"\x0eapproved_count\x18\x02 \x01(\x03R\rapprovedCount\x12%\n" +
	"\x0erejected_count\x18\x03 \x01(\x03R\rrejectedCount\x12%\n" +
	"\x0edeferred_count\x18\x04 \x01(\x03R\rdeferredCount\x12e\n" +
	"\vby_priority\x18\x05 \x03(\v2D.penfold.processing.review.v1.GetReviewStatsResponse.ByPriorityEntryR\n" +
	"byPriority\x12o\n" +
	"\x0fby_content_type\x18\x06 \x03(\v2G.penfold.processing.review.v1.GetReviewStatsResponse.ByContentTypeEntryR\rbyContentType\x12_\n" +
	"\tby_source\x18\a \x03(\v2B.penfold.processing.review.v1.GetReviewStatsResponse.BySourceEntryR\bbySource\x12e\n" +
	"\vby_category\x18\b \x03(\v2D.penfold.processing.review.v1.GetReviewStatsResponse.ByCategoryEntryR\n" +
	"byCategory\x125\n" +
	"\x17avg_review_time_seconds\x18\t \x01(\x01R\x14avgReviewTimeSeconds\x12Q\n" +
	"\fdaily_counts\x18\n" +
	" \x03(\v2..penfold.processing.review.v1.DailyReviewCountR\vdailyCounts\x1a=\n" +
	"\x0fByPriorityEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a@\n" +
	"\x12ByContentTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a;\n" +
	"\rBySourceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a=\n" +
	"\x0fByCategoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x94\x01\n" +
	"\x10DailyReviewCount\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x18\n" +
	"\acreated\x18\x02 \x01(\x03R\acreated\x12\x1a\n" +
	"\breviewed\x18\x03 \x01(\x03R\breviewed\x12\x1a\n" +
	"\bapproved\x18\x04 \x01(\x03R\bapproved\x12\x1a\n" +
	"\brejected\x18\x05 \x01(\x03R\brejected*\x9c\x01\n" +
	"\fReviewStatus\x12\x1d\n" +
	"\x19REVIEW_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15REVIEW_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16REVIEW_STATUS_APPROVED\x10\x02\x12\x1a\n" +
	"\x16REVIEW_STATUS_REJECTED\x10\x03\x12\x1a\n" +
	"\x16REVIEW_STATUS_DEFERRED\x10\x04*s\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_MEDIUM\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x03\x12\x13\n" +
	"\x0fPRIORITY_URGENT\x10\x04*\x87\x01\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ACTION_TYPE_APPROVE\x10\x01\x12\x16\n" +
	"\x12ACTION_TYPE_REJECT\x10\x02\x12\x15\n" +
	"\x11ACTION_TYPE_DEFER\x10\x03\x12\x14\n" +
	"\x10ACTION_TYPE_UNDO\x10\x042\xd9\x06\n" +
	"\rReviewService\x12{\n" +
	"\x0eGetDailyReview\x123.penfold.processing.review.v1.GetDailyReviewRequest\x1a4.penfold.processing.review.v1.GetDailyReviewResponse\x12x\n" +
	"\rGetReviewItem\x122.penfold.processing.review.v1.GetReviewItemRequest\x1a3.penfold.processing.review.v1.GetReviewItemResponse\x12~\n" +
	"\x0fListReviewItems\x124.penfold.processing.review.v1.ListReviewItemsRequest\x1a5.penfold.processing.review.v1.ListReviewItemsResponse\x12r\n" +
	"\vApproveItem\x120.penfold.processing.review.v1.ApproveItemRequest\x1a1.penfold.processing.review.v1.ApproveItemResponse\x12o\n" +
	"\n" +
	"RejectItem\x12/.penfold.processing.review.v1.RejectItemRequest\x1a0.penfold.processing.review.v1.RejectItemResponse\x12o\n" +
	"\n" +
	"UndoAction\x12/.penfold.processing.review.v1.UndoActionRequest\x1a0.penfold.processing.review.v1.UndoActionResponse\x12{\n" +
	"\x0eGetReviewStats\x123.penfold.processing.review.v1.GetReviewStatsRequest\x1a4.penfold.processing.review.v1.GetReviewStatsResponseBNZLgithub.com/otherjamesbrown/penfold/api/proto/processing/v1/reviewpb;reviewpbb\x06proto3"

var (
	file_reviewpb_review_proto_rawDescOnce sync.Once
	file_reviewpb_review_proto_rawDescData []byte
)

func file_reviewpb_review_proto_rawDescGZIP() []byte {
	file_reviewpb_review_proto_rawDescOnce.Do(func() {
		file_reviewpb_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reviewpb_review_proto_rawDesc), len(file_reviewpb_review_proto_rawDesc)))
	})
	return file_reviewpb_review_proto_rawDescData
}

var file_reviewpb_review_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_reviewpb_review_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_reviewpb_review_proto_goTypes = []any{
	(ReviewStatus)(0),               // 0: penfold.processing.review.v1.ReviewStatus
	(Priority)(0),                   // 1: penfold.processing.review.v1.Priority
	(ActionType)(0),                 // 2: penfold.processing.review.v1.ActionType
	(*ReviewItem)(nil),              // 3: penfold.processing.review.v1.ReviewItem
	(*ReviewAction)(nil),            // 4: penfold.processing.review.v1.ReviewAction
	(*ReviewCategory)(nil),          // 5: penfold.processing.review.v1.ReviewCategory
	(*DailyReview)(nil),             // 6: penfold.processing.review.v1.DailyReview
	(*GetDailyReviewRequest)(nil),   // 7: penfold.processing.review.v1.GetDailyReviewRequest
	(*GetDailyReviewResponse)(nil),  // 8: penfold.processing.review.v1.GetDailyReviewResponse
	(*GetReviewItemRequest)(nil),    // 9: penfold.processing.review.v1.GetReviewItemRequest
	(*GetReviewItemResponse)(nil),   // 10: penfold.processing.review.v1.GetReviewItemResponse
	(*ListReviewItemsRequest)(nil),  // 11: penfold.processing.review.v1.ListReviewItemsRequest
	(*ListReviewItemsResponse)(nil), // 12: penfold.processing.review.v1.ListReviewItemsResponse
	(*ApproveItemRequest)(nil),      // 13: penfold.processing.review.v1.ApproveItemRequest
	(*ApproveItemResponse)(nil),     // 14: penfold.processing.review.v1.ApproveItemResponse
	(*RejectItemRequest)(nil),       // 15: penfold.processing.review.v1.RejectItemRequest
	(*RejectItemResponse)(nil),      // 16: penfold.processing.review.v1.RejectItemResponse
	(*UndoActionRequest)(nil),       // 17: penfold.processing.review.v1.UndoActionRequest
	(*UndoActionResponse)(nil),      // 18: penfold.processing.review.v1.UndoActionResponse
	(*GetReviewStatsRequest)(nil),   // 19: penfold.processing.review.v1.GetReviewStatsRequest
	(*GetReviewStatsResponse)(nil),  // 20: penfold.processing.review.v1.GetReviewStatsResponse
	(*DailyReviewCount)(nil),        // 21: penfold.processing.review.v1.DailyReviewCount
	nil,                             // 22: penfold.processing.review.v1.ReviewItem.MetadataEntry
	nil,                             // 23: penfold.processing.review.v1.GetReviewStatsResponse.ByPriorityEntry
	nil,                             // 24: penfold.processing.review.v1.GetReviewStatsResponse.ByContentTypeEntry
	nil,                             // 25: penfold.processing.review.v1.GetReviewStatsResponse.BySourceEntry
	nil,                             // 26: penfold.processing.review.v1.GetReviewStatsResponse.ByCategoryEntry
	(*timestamppb.Timestamp)(nil),   // 27: google.protobuf.Timestamp
}
var file_reviewpb_review_proto_depIdxs = []int32{
	1,  // 0: penfold.processing.review.v1.ReviewItem.priority:type_name -> penfold.processing.review.v1.Priority
	0,  // 1: penfold.processing.review.v1.ReviewItem.status:type_name -> penfold.processing.review.v1.ReviewStatus
	27, // 2: penfold.processing.review.v1.ReviewItem.created_at:type_name -> google.protobuf.Timestamp
	27, // 3: penfold.processing.review.v1.ReviewItem.updated_at:type_name -> google.protobuf.Timestamp
	22, // 4: penfold.processing.review.v1.ReviewItem.metadata:type_name -> penfold.processing.review.v1.ReviewItem.MetadataEntry
	2,  // 5: penfold.processing.review.v1.ReviewAction.action_type:type_name -> penfold.processing.review.v1.ActionType
	0,  // 6: penfold.processing.review.v1.ReviewAction.previous_status:type_name -> penfold.processing.review.v1.ReviewStatus
	0,  // 7: penfold.processing.review.v1.ReviewAction.new_status:type_name -> penfold.processing.review.v1.ReviewStatus
	27, // 8: penfold.processing.review.v1.ReviewAction.performed_at:type_name -> google.protobuf.Timestamp
	3,  // 9: penfold.processing.review.v1.ReviewCategory.items:type_name -> penfold.processing.review.v1.ReviewItem
	5,  // 10: penfold.processing.review.v1.DailyReview.categories:type_name -> penfold.processing.review.v1.ReviewCategory
	6,  // 11: penfold.processing.review.v1.GetDailyReviewResponse.review:type_name -> penfold.processing.review.v1.DailyReview
	3,  // 12: penfold.processing.review.v1.GetReviewItemResponse.item:type_name -> penfold.processing.review.v1.ReviewItem
	4,  // 13: penfold.processing.review.v1.GetReviewItemResponse.recent_actions:type_name -> penfold.processing.review.v1.ReviewAction
	0,  // 14: penfold.processing.review.v1.ListReviewItemsRequest.statuses:type_name -> penfold.processing.review.v1.ReviewStatus
	1,  // 15: penfold.processing.review.v1.ListReviewItemsRequest.priorities:type_name -> penfold.processing.review.v1.Priority
	27, // 16: penfold.processing.review.v1.ListReviewItemsRequest.created_after:type_name -> google.protobuf.Timestamp
	27, // 17: penfold.processing.review.v1.ListReviewItemsRequest.created_before:type_name -> google.protobuf.Timestamp
	3,  // 18: penfold.processing.review.v1.ListReviewItemsResponse.items:type_name -> penfold.processing.review.v1.ReviewItem
	3,  // 19: penfold.processing.review.v1.ApproveItemResponse.item:type_name -> penfold.processing.review.v1.ReviewItem
	4,  // 20: penfold.processing.review.v1.ApproveItemResponse.action:type_name -> penfold.processing.review.v1.ReviewAction
	3,  // 21: penfold.processing.review.v1.RejectItemResponse.item:type_name -> penfold.processing.review.v1.ReviewItem
	4,  // 22: penfold.processing.review.v1.RejectItemResponse.action:type_name -> penfold.processing.review.v1.ReviewAction
	3,  // 23: penfold.processing.review.v1.UndoActionResponse.item:type_name -> penfold.processing.review.v1.ReviewItem
	4,  // 24: penfold.processing.review.v1.UndoActionResponse.undone_action:type_name -> penfold.processing.review.v1.ReviewAction
	27, // 25: penfold.processing.review.v1.GetReviewStatsRequest.from_time:type_name -> google.protobuf.Timestamp
	27, // 26: penfold.processing.review.v1.GetReviewStatsRequest.to_time:type_name -> google.protobuf.Timestamp
	23, // 27: penfold.processing.review.v1.GetReviewStatsResponse.by_priority:type_name -> penfold.processing.review.v1.GetReviewStatsResponse.ByPriorityEntry
	24, // 28: penfold.processing.review.v1.GetReviewStatsResponse.by_content_type:type_name -> penfold.processing.review.v1.GetReviewStatsResponse.ByContentTypeEntry
	25, // 29: penfold.processing.review.v1.GetReviewStatsResponse.by_source:type_name -> penfold.processing.review.v1.GetReviewStatsResponse.BySourceEntry
	26, // 30: penfold.processing.review.v1.GetReviewStatsResponse.by_category:type_name -> penfold.processing.review.v1.GetReviewStatsResponse.ByCategoryEntry
	21, // 31: penfold.processing.review.v1.GetReviewStatsResponse.daily_counts:type_name -> penfold.processing.review.v1.DailyReviewCount
	7,  // 32: penfold.processing.review.v1.ReviewService.GetDailyReview:input_type -> penfold.processing.review.v1.GetDailyReviewRequest
	9,  // 33: penfold.processing.review.v1.ReviewService.GetReviewItem:input_type -> penfold.processing.review.v1.GetReviewItemRequest
	11, // 34: penfold.processing.review.v1.ReviewService.ListReviewItems:input_type -> penfold.processing.review.v1.ListReviewItemsRequest
	13, // 35: penfold.processing.review.v1.ReviewService.ApproveItem:input_type -> penfold.processing.review.v1.ApproveItemRequest
	15, // 36: penfold.processing.review.v1.ReviewService.RejectItem:input_type -> penfold.processing.review.v1.RejectItemRequest
	17, // 37: penfold.processing.review.v1.ReviewService.UndoAction:input_type -> penfold.processing.review.v1.UndoActionRequest
	19, // 38: penfold.processing.review.v1.ReviewService.GetReviewStats:input_type -> penfold.processing.review.v1.GetReviewStatsRequest
	8,  // 39: penfold.processing.review.v1.ReviewService.GetDailyReview:output_type -> penfold.processing.review.v1.GetDailyReviewResponse
	10, // 40: penfold.processing.review.v1.ReviewService.GetReviewItem:output_type -> penfold.processing.review.v1.GetReviewItemResponse
	12, // 41: penfold.processing.review.v1.ReviewService.ListReviewItems:output_type -> penfold.processing.review.v1.ListReviewItemsResponse
	14, // 42: penfold.processing.review.v1.ReviewService.ApproveItem:output_type -> penfold.processing.review.v1.ApproveItemResponse
	16, // 43: penfold.processing.review.v1.ReviewService.RejectItem:output_type -> penfold.processing.review.v1.RejectItemResponse
	18, // 44: penfold.processing.review.v1.ReviewService.UndoAction:output_type -> penfold.processing.review.v1.UndoActionResponse
	20, // 45: penfold.processing.review.v1.ReviewService.GetReviewStats:output_type -> penfold.processing.review.v1.GetReviewStatsResponse
	39, // [39:46] is the sub-list for method output_type
	32, // [32:39] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_reviewpb_review_proto_init() }
func file_reviewpb_review_proto_init() {
	if File_reviewpb_review_proto != nil {
		return
	}
	file_reviewpb_review_proto_msgTypes[4].OneofWrappers = []any{}
	file_reviewpb_review_proto_msgTypes[6].OneofWrappers = []any{}
	file_reviewpb_review_proto_msgTypes[8].OneofWrappers = []any{}
	file_reviewpb_review_proto_msgTypes[9].OneofWrappers = []any{}
	file_reviewpb_review_proto_msgTypes[10].OneofWrappers = []any{}
	file_reviewpb_review_proto_msgTypes[12].OneofWrappers = []any{}
	file_reviewpb_review_proto_msgTypes[14].OneofWrappers = []any{}
	file_reviewpb_review_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reviewpb_review_proto_rawDesc), len(file_reviewpb_review_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reviewpb_review_proto_goTypes,
		DependencyIndexes: file_reviewpb_review_proto_depIdxs,
		EnumInfos:         file_reviewpb_review_proto_enumTypes,
		MessageInfos:      file_reviewpb_review_proto_msgTypes,
	}.Build()
	File_reviewpb_review_proto = out.File
	file_reviewpb_review_proto_goTypes = nil
	file_reviewpb_review_proto_depIdxs = nil
}
