-- =====================================================
-- Content ID Column Migration
-- Created: 2026-01-24
-- Bead: pe-8psg - Add content_id column to sources table
-- Description: Add content_id support for unified tracing across
--              all AI operations. Content IDs are short, human-readable
--              identifiers (format: <type>-<base62>) generated by CLI.
-- =====================================================

-- +goose Up

-- Add content_id column to sources table
-- Nullable for backwards compatibility with existing rows
-- Format: <type:2>-<base62_timestamp:4><base62_random:4> (e.g., em-9x3kp7mn)
ALTER TABLE sources ADD COLUMN IF NOT EXISTS content_id VARCHAR(12);

-- Create unique index for content_id lookups
-- Partial index excludes NULL values (existing rows without content_id)
CREATE UNIQUE INDEX IF NOT EXISTS idx_sources_content_id
    ON sources(content_id)
    WHERE content_id IS NOT NULL;

-- Comments for documentation
COMMENT ON COLUMN sources.content_id IS 'Short human-readable ID for unified tracing (format: <type>-<base62>, e.g., em-9x3kp7mn)';

-- +goose Down

-- Drop the index first
DROP INDEX IF EXISTS idx_sources_content_id;

-- Remove the content_id column
ALTER TABLE sources DROP COLUMN IF EXISTS content_id;
