package pattern

import (
	"context"
	"testing"
	"time"

	"github.com/otherjamesbrown/penfold/services/review/automation"
)

func TestDefaultLearnerConfig(t *testing.T) {
	config := DefaultLearnerConfig()

	if config.MinSupportCount <= 0 {
		t.Error("MinSupportCount should be positive")
	}
	if config.MinConfidence <= 0 || config.MinConfidence > 1 {
		t.Error("MinConfidence should be between 0 and 1")
	}
	if config.MaxSuggestions <= 0 {
		t.Error("MaxSuggestions should be positive")
	}
	if config.LookbackDays <= 0 {
		t.Error("LookbackDays should be positive")
	}
	if !config.EnableSenderPatterns {
		t.Error("Sender patterns should be enabled by default")
	}
	if !config.EnableTopicPatterns {
		t.Error("Topic patterns should be enabled by default")
	}
}

func TestNewPatternLearner(t *testing.T) {
	detector := newTestDetector()
	learner := NewPatternLearner(nil, detector)

	if learner == nil {
		t.Fatal("expected learner to be created")
	}
	if learner.config == nil {
		t.Error("expected default config to be set")
	}
}

func TestPatternLearnerRecordDecision(t *testing.T) {
	detector := newTestDetector()
	learner := NewPatternLearner(DefaultLearnerConfig(), detector)

	item := &automation.ReviewItem{
		ID:       "item-1",
		TenantID: "tenant-1",
		Sender:   "test@example.com",
		Category: "work",
	}
	decision := automation.NewDecision("tenant-1", "user-1", item, automation.ActionAccept)

	learner.RecordDecision(decision)

	// Check that decision was recorded (indirect check via decisions map)
	learner.mu.RLock()
	decisions := learner.decisions["tenant-1"]
	learner.mu.RUnlock()

	if len(decisions) != 1 {
		t.Errorf("expected 1 decision recorded, got %d", len(decisions))
	}
}

func TestPatternLearnerExtractPattern(t *testing.T) {
	detector := newTestDetector()
	config := DefaultLearnerConfig()
	config.MinSupportCount = 3
	config.MinConfidence = 0.8
	learner := NewPatternLearner(config, detector)

	// Create decisions with clear pattern
	decisions := make([]*automation.Decision, 0)
	for i := 0; i < 5; i++ {
		item := &automation.ReviewItem{
			ID:       "item-" + string(rune('a'+i)),
			TenantID: "tenant-1",
			Sender:   "newsletter@company.com",
			Category: "marketing",
		}
		decision := automation.NewDecision("tenant-1", "user-1", item, automation.ActionReject)
		decisions = append(decisions, decision)
	}

	pattern := learner.ExtractPattern(decisions)

	if pattern == nil {
		t.Skip("pattern extraction may need more specific data")
		return
	}

	if pattern.SuggestedAction != string(automation.ActionReject) {
		t.Errorf("expected suggested action 'reject', got '%s'", pattern.SuggestedAction)
	}
	if !pattern.AutoGenerated {
		t.Error("expected pattern to be auto-generated")
	}
	if pattern.Source != "learned" {
		t.Errorf("expected source 'learned', got '%s'", pattern.Source)
	}
}

func TestPatternLearnerExtractPatternInsufficientData(t *testing.T) {
	detector := newTestDetector()
	config := DefaultLearnerConfig()
	config.MinSupportCount = 10
	learner := NewPatternLearner(config, detector)

	// Only 3 decisions
	decisions := make([]*automation.Decision, 0)
	for i := 0; i < 3; i++ {
		item := &automation.ReviewItem{
			ID:       "item-" + string(rune('a'+i)),
			TenantID: "tenant-1",
		}
		decision := automation.NewDecision("tenant-1", "user-1", item, automation.ActionAccept)
		decisions = append(decisions, decision)
	}

	pattern := learner.ExtractPattern(decisions)

	if pattern != nil {
		t.Error("expected nil pattern due to insufficient data")
	}
}

func TestPatternLearnerSuggestPatternsForTenant(t *testing.T) {
	detector := newTestDetector()
	config := &LearnerConfig{
		MinSupportCount:      2,
		MinConfidence:        0.7,
		MaxSuggestions:       10,
		LookbackDays:         30,
		EnableSenderPatterns: true,
		EnableTopicPatterns:  true,
	}
	learner := NewPatternLearner(config, detector)

	// Record decisions with clear pattern
	for i := 0; i < 5; i++ {
		item := &automation.ReviewItem{
			ID:       "item-" + string(rune('a'+i)),
			TenantID: "tenant-1",
			Sender:   "spam@example.com",
			Category: "spam",
		}
		decision := automation.NewDecision("tenant-1", "user-1", item, automation.ActionReject)
		learner.RecordDecision(decision)
	}

	ctx := context.Background()
	suggestions, err := learner.SuggestPatternsForTenant(ctx, "tenant-1")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Should have at least one suggestion
	if len(suggestions) == 0 {
		t.Log("no suggestions returned, may need more diverse data")
		return
	}

	// Verify suggestions have required fields
	for _, s := range suggestions {
		if s.ID == "" {
			t.Error("suggestion ID should be set")
		}
		if s.TenantID != "tenant-1" {
			t.Errorf("expected tenant ID 'tenant-1', got '%s'", s.TenantID)
		}
		if s.Pattern == nil {
			t.Error("suggestion should have a pattern")
		}
		if s.Status != "pending" {
			t.Errorf("expected status 'pending', got '%s'", s.Status)
		}
	}
}

func TestPatternLearnerSuggestPatternsInsufficientData(t *testing.T) {
	detector := newTestDetector()
	config := &LearnerConfig{
		MinSupportCount: 10,
		MinConfidence:   0.8,
		LookbackDays:    30,
	}
	learner := NewPatternLearner(config, detector)

	// Only record a few decisions
	for i := 0; i < 3; i++ {
		item := &automation.ReviewItem{
			ID:       "item-" + string(rune('a'+i)),
			TenantID: "tenant-1",
		}
		decision := automation.NewDecision("tenant-1", "user-1", item, automation.ActionAccept)
		learner.RecordDecision(decision)
	}

	ctx := context.Background()
	suggestions, err := learner.SuggestPatternsForTenant(ctx, "tenant-1")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if len(suggestions) != 0 {
		t.Errorf("expected 0 suggestions with insufficient data, got %d", len(suggestions))
	}
}

func TestPatternLearnerTenantIsolation(t *testing.T) {
	detector := newTestDetector()
	config := &LearnerConfig{
		MinSupportCount:      2,
		MinConfidence:        0.7,
		MaxSuggestions:       10,
		LookbackDays:         30,
		EnableSenderPatterns: true,
	}
	learner := NewPatternLearner(config, detector)

	// Record decisions for tenant-1
	for i := 0; i < 5; i++ {
		item := &automation.ReviewItem{
			ID:       "item-t1-" + string(rune('a'+i)),
			TenantID: "tenant-1",
			Sender:   "sender1@example.com",
		}
		decision := automation.NewDecision("tenant-1", "user-1", item, automation.ActionAccept)
		learner.RecordDecision(decision)
	}

	// Record decisions for tenant-2
	for i := 0; i < 5; i++ {
		item := &automation.ReviewItem{
			ID:       "item-t2-" + string(rune('a'+i)),
			TenantID: "tenant-2",
			Sender:   "sender2@example.com",
		}
		decision := automation.NewDecision("tenant-2", "user-2", item, automation.ActionReject)
		learner.RecordDecision(decision)
	}

	ctx := context.Background()

	// Get suggestions for tenant-1
	suggestions1, _ := learner.SuggestPatternsForTenant(ctx, "tenant-1")
	for _, s := range suggestions1 {
		if s.TenantID != "tenant-1" {
			t.Error("tenant-1 suggestion has wrong tenant ID")
		}
	}

	// Get suggestions for tenant-2
	suggestions2, _ := learner.SuggestPatternsForTenant(ctx, "tenant-2")
	for _, s := range suggestions2 {
		if s.TenantID != "tenant-2" {
			t.Error("tenant-2 suggestion has wrong tenant ID")
		}
	}
}

func TestExtractDomain(t *testing.T) {
	tests := []struct {
		email    string
		expected string
	}{
		{"user@example.com", "example.com"},
		{"name@company.org", "company.org"},
		{"invalid-email", ""},
		{"@missing-local", "missing-local"},
		{"missing-domain@", ""},
		{"", ""},
	}

	for _, tt := range tests {
		result := extractDomain(tt.email)
		if result != tt.expected {
			t.Errorf("extractDomain(%s): expected %s, got %s", tt.email, tt.expected, result)
		}
	}
}

func TestExtractWords(t *testing.T) {
	words := extractWords("Important Meeting Tomorrow")

	if len(words) == 0 {
		t.Error("expected some words to be extracted")
	}

	// Should not include stop words
	for _, w := range words {
		if w == "the" || w == "a" || w == "is" {
			t.Errorf("stop word '%s' should not be included", w)
		}
	}
}

func TestDeterminePatternType(t *testing.T) {
	tests := []struct {
		name       string
		conditions []PatternCondition
		expected   PatternType
	}{
		{
			name: "sender field",
			conditions: []PatternCondition{
				NewPatternCondition("sender", OpEquals, "test@example.com"),
			},
			expected: PatternSender,
		},
		{
			name: "category field",
			conditions: []PatternCondition{
				NewPatternCondition("category", OpEquals, "work"),
			},
			expected: PatternTopic,
		},
		{
			name: "hour_of_day field",
			conditions: []PatternCondition{
				NewPatternCondition("hour_of_day", OpEquals, 9),
			},
			expected: PatternTime,
		},
		{
			name: "source field",
			conditions: []PatternCondition{
				NewPatternCondition("source", OpEquals, "email"),
			},
			expected: PatternSource,
		},
		{
			name: "priority field",
			conditions: []PatternCondition{
				NewPatternCondition("priority", OpGreaterThan, 2),
			},
			expected: PatternPriority,
		},
		{
			name: "multiple conditions",
			conditions: []PatternCondition{
				NewPatternCondition("sender", OpEquals, "test@example.com"),
				NewPatternCondition("category", OpEquals, "work"),
			},
			expected: PatternSender, // First condition determines type
		},
		{
			name:       "empty conditions",
			conditions: []PatternCondition{},
			expected:   PatternContent,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := determinePatternType(tt.conditions)
			if result != tt.expected {
				t.Errorf("expected %s, got %s", tt.expected, result)
			}
		})
	}
}

func TestGeneratePatternName(t *testing.T) {
	conditions := []PatternCondition{
		NewPatternCondition("sender", OpEquals, "test@example.com"),
	}

	name := generatePatternName(conditions, automation.ActionAccept)

	if name == "" {
		t.Error("expected non-empty name")
	}
	if len(name) > 100 {
		t.Error("name should be reasonably short")
	}
}

func TestNewDecisionTracker(t *testing.T) {
	tracker := NewDecisionTracker(100)

	if tracker == nil {
		t.Fatal("expected tracker to be created")
	}
	if tracker.maxSize != 100 {
		t.Errorf("expected max size 100, got %d", tracker.maxSize)
	}
}

func TestDecisionTrackerDefaultMaxSize(t *testing.T) {
	tracker := NewDecisionTracker(0)

	if tracker.maxSize != 10000 {
		t.Errorf("expected default max size 10000, got %d", tracker.maxSize)
	}
}

func TestDecisionTrackerRecord(t *testing.T) {
	tracker := NewDecisionTracker(100)

	item := &automation.ReviewItem{
		ID:       "item-1",
		TenantID: "tenant-1",
	}
	decision := automation.NewDecision("tenant-1", "user-1", item, automation.ActionAccept)

	tracker.Record(decision)

	decisions := tracker.GetDecisions()
	if len(decisions) != 1 {
		t.Errorf("expected 1 decision, got %d", len(decisions))
	}
}

func TestDecisionTrackerMaxSize(t *testing.T) {
	tracker := NewDecisionTracker(5)

	// Record more than max size
	for i := 0; i < 10; i++ {
		item := &automation.ReviewItem{
			ID:       "item-" + string(rune('a'+i)),
			TenantID: "tenant-1",
		}
		decision := automation.NewDecision("tenant-1", "user-1", item, automation.ActionAccept)
		tracker.Record(decision)
	}

	decisions := tracker.GetDecisions()
	if len(decisions) != 5 {
		t.Errorf("expected max 5 decisions, got %d", len(decisions))
	}
}

func TestDecisionTrackerGetByTenant(t *testing.T) {
	tracker := NewDecisionTracker(100)

	// Record decisions for different tenants
	for i := 0; i < 5; i++ {
		item1 := &automation.ReviewItem{ID: "t1-" + string(rune('a'+i)), TenantID: "tenant-1"}
		item2 := &automation.ReviewItem{ID: "t2-" + string(rune('a'+i)), TenantID: "tenant-2"}
		tracker.Record(automation.NewDecision("tenant-1", "user-1", item1, automation.ActionAccept))
		tracker.Record(automation.NewDecision("tenant-2", "user-2", item2, automation.ActionReject))
	}

	tenant1Decisions := tracker.GetDecisionsByTenant("tenant-1")
	if len(tenant1Decisions) != 5 {
		t.Errorf("expected 5 decisions for tenant-1, got %d", len(tenant1Decisions))
	}

	tenant2Decisions := tracker.GetDecisionsByTenant("tenant-2")
	if len(tenant2Decisions) != 5 {
		t.Errorf("expected 5 decisions for tenant-2, got %d", len(tenant2Decisions))
	}
}

func TestDecisionTrackerGetSince(t *testing.T) {
	tracker := NewDecisionTracker(100)

	now := time.Now()

	// Record old decision
	oldItem := &automation.ReviewItem{ID: "old", TenantID: "tenant-1"}
	oldDecision := automation.NewDecision("tenant-1", "user-1", oldItem, automation.ActionAccept)
	oldDecision.CreatedAt = now.Add(-48 * time.Hour)
	tracker.Record(oldDecision)

	// Record recent decision
	newItem := &automation.ReviewItem{ID: "new", TenantID: "tenant-1"}
	newDecision := automation.NewDecision("tenant-1", "user-1", newItem, automation.ActionAccept)
	newDecision.CreatedAt = now
	tracker.Record(newDecision)

	recent := tracker.GetDecisionsSince(now.Add(-24 * time.Hour))
	if len(recent) != 1 {
		t.Errorf("expected 1 recent decision, got %d", len(recent))
	}
}

func TestDecisionTrackerClear(t *testing.T) {
	tracker := NewDecisionTracker(100)

	item := &automation.ReviewItem{ID: "item-1", TenantID: "tenant-1"}
	tracker.Record(automation.NewDecision("tenant-1", "user-1", item, automation.ActionAccept))

	tracker.Clear()

	if len(tracker.GetDecisions()) != 0 {
		t.Error("expected 0 decisions after clear")
	}
}

func TestNewFeedbackLoop(t *testing.T) {
	fb := NewFeedbackLoop()

	if fb == nil {
		t.Fatal("expected feedback loop to be created")
	}
}

func TestFeedbackLoopRecordFeedback(t *testing.T) {
	fb := NewFeedbackLoop()

	fb.RecordFeedback("pattern-1", true)
	fb.RecordFeedback("pattern-1", true)
	fb.RecordFeedback("pattern-1", false)

	pos, neg, _ := fb.GetPatternStats("pattern-1")
	if pos != 2 {
		t.Errorf("expected 2 positive, got %d", pos)
	}
	if neg != 1 {
		t.Errorf("expected 1 negative, got %d", neg)
	}
}

func TestFeedbackLoopRecordOverride(t *testing.T) {
	fb := NewFeedbackLoop()

	fb.RecordOverride("pattern-1")
	fb.RecordOverride("pattern-1")

	_, _, overrides := fb.GetPatternStats("pattern-1")
	if overrides != 2 {
		t.Errorf("expected 2 overrides, got %d", overrides)
	}
}

func TestFeedbackLoopGetAccuracy(t *testing.T) {
	fb := NewFeedbackLoop()

	// No feedback - default to 1.0
	accuracy := fb.GetAccuracy("pattern-1")
	if accuracy != 1.0 {
		t.Errorf("expected 1.0 accuracy with no feedback, got %f", accuracy)
	}

	// Add feedback
	fb.RecordFeedback("pattern-1", true)
	fb.RecordFeedback("pattern-1", true)
	fb.RecordFeedback("pattern-1", false)

	accuracy = fb.GetAccuracy("pattern-1")
	expectedAccuracy := 2.0 / 3.0
	if accuracy < expectedAccuracy-0.01 || accuracy > expectedAccuracy+0.01 {
		t.Errorf("expected accuracy ~%.2f, got %.2f", expectedAccuracy, accuracy)
	}
}

func TestFeedbackLoopGetOverrideRate(t *testing.T) {
	fb := NewFeedbackLoop()

	// No data
	rate := fb.GetOverrideRate("pattern-1")
	if rate != 0.0 {
		t.Errorf("expected 0 override rate with no data, got %f", rate)
	}

	// Add feedback and overrides
	fb.RecordFeedback("pattern-1", true)
	fb.RecordFeedback("pattern-1", true)
	fb.RecordOverride("pattern-1")
	fb.RecordOverride("pattern-1")

	rate = fb.GetOverrideRate("pattern-1")
	// 2 overrides out of 2 positive + 2 overrides = 4 total
	expectedRate := 2.0 / 4.0
	if rate < expectedRate-0.01 || rate > expectedRate+0.01 {
		t.Errorf("expected override rate ~%.2f, got %.2f", expectedRate, rate)
	}
}

func TestFeedbackLoopShouldDisable(t *testing.T) {
	fb := NewFeedbackLoop()

	// Record mostly negative feedback
	for i := 0; i < 10; i++ {
		positive := i < 2 // 2 positive, 8 negative
		fb.RecordFeedback("pattern-1", positive)
	}

	// Should disable (80% negative > 50% threshold)
	if !fb.ShouldDisable("pattern-1", 5, 0.7) {
		t.Error("expected to suggest disabling pattern with high negative ratio")
	}

	// Test override rate threshold with a pattern that has good accuracy
	// Record mostly positive feedback for pattern-2
	for i := 0; i < 10; i++ {
		positive := i < 8 // 8 positive, 2 negative (80% accuracy)
		fb.RecordFeedback("pattern-2", positive)
	}
	// pattern-2 has no overrides so override rate is 0, should not disable
	if fb.ShouldDisable("pattern-2", 5, 0.1) {
		t.Error("expected not to suggest disabling pattern with high accuracy and low override rate")
	}

	// Should not disable with insufficient feedback
	if fb.ShouldDisable("pattern-1", 20, 0.5) {
		t.Error("expected not to suggest disabling with insufficient feedback")
	}
}

func TestEstimateImpact(t *testing.T) {
	// 30 observations over 30 days = 1 per day, projected 30 for next 30 days
	impact := estimateImpact(30, 30)
	if impact != 30 {
		t.Errorf("expected impact 30, got %d", impact)
	}

	// 60 observations over 30 days = 2 per day, projected 60 for next 30 days
	impact = estimateImpact(60, 30)
	if impact != 60 {
		t.Errorf("expected impact 60, got %d", impact)
	}

	// Zero lookback days
	impact = estimateImpact(10, 0)
	if impact != 10 {
		t.Errorf("expected impact 10 with zero lookback, got %d", impact)
	}
}

func TestFormatSuggestionExplanation(t *testing.T) {
	// Test basic formatting
	result := formatSuggestionExplanation("Action %s on items", automation.ActionAccept)
	if result == "" {
		t.Error("expected non-empty explanation")
	}
}

func TestToString(t *testing.T) {
	tests := []struct {
		input    int
		expected string
	}{
		{0, "0"},
		{1, "1"},
		{10, "10"},
		{123, "123"},
		{-5, "-5"},
	}

	for _, tt := range tests {
		result := toString(tt.input)
		if result != tt.expected {
			t.Errorf("toString(%d): expected %s, got %s", tt.input, tt.expected, result)
		}
	}
}

func TestToStringFloat(t *testing.T) {
	tests := []struct {
		input    float64
		expected string
	}{
		{1.5, "1.5"},
		{0.0, "0.0"},
		{10.9, "10.9"},
	}

	for _, tt := range tests {
		result := toStringFloat(tt.input)
		if result != tt.expected {
			t.Errorf("toStringFloat(%f): expected %s, got %s", tt.input, tt.expected, result)
		}
	}
}
