package pattern

import (
	"encoding/json"
	"testing"
	"time"
)

func TestPatternTypeIsValid(t *testing.T) {
	tests := []struct {
		name     string
		pt       PatternType
		expected bool
	}{
		{"sender is valid", PatternSender, true},
		{"topic is valid", PatternTopic, true},
		{"time is valid", PatternTime, true},
		{"content is valid", PatternContent, true},
		{"action is valid", PatternAction, true},
		{"source is valid", PatternSource, true},
		{"priority is valid", PatternPriority, true},
		{"composite is valid", PatternComposite, true},
		{"invalid type", PatternType("invalid"), false},
		{"empty type", PatternType(""), false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := tt.pt.IsValid()
			if result != tt.expected {
				t.Errorf("expected %v, got %v", tt.expected, result)
			}
		})
	}
}

func TestValidPatternTypes(t *testing.T) {
	types := ValidPatternTypes()
	if len(types) != 8 {
		t.Errorf("expected 8 pattern types, got %d", len(types))
	}

	// Verify all expected types are present
	expectedTypes := map[PatternType]bool{
		PatternSender:    false,
		PatternTopic:     false,
		PatternTime:      false,
		PatternContent:   false,
		PatternAction:    false,
		PatternSource:    false,
		PatternPriority:  false,
		PatternComposite: false,
	}

	for _, pt := range types {
		expectedTypes[pt] = true
	}

	for pt, found := range expectedTypes {
		if !found {
			t.Errorf("expected pattern type %s not found", pt)
		}
	}
}

func TestNewPatternCondition(t *testing.T) {
	cond := NewPatternCondition("sender", OpEquals, "test@example.com")

	if cond.Field != "sender" {
		t.Errorf("expected field 'sender', got '%s'", cond.Field)
	}
	if cond.Operator != OpEquals {
		t.Errorf("expected operator 'eq', got '%s'", cond.Operator)
	}
	if cond.Value != "test@example.com" {
		t.Errorf("expected value 'test@example.com', got '%v'", cond.Value)
	}
	if cond.Weight != 1.0 {
		t.Errorf("expected weight 1.0, got %f", cond.Weight)
	}
}

func TestNewPattern(t *testing.T) {
	conditions := []PatternCondition{
		NewPatternCondition("sender", OpEquals, "test@example.com"),
	}

	pattern := NewPattern("tenant-1", "Test Pattern", PatternSender, conditions)

	if pattern.ID == "" {
		t.Error("expected pattern ID to be set")
	}
	if pattern.TenantID != "tenant-1" {
		t.Errorf("expected tenant ID 'tenant-1', got '%s'", pattern.TenantID)
	}
	if pattern.Name != "Test Pattern" {
		t.Errorf("expected name 'Test Pattern', got '%s'", pattern.Name)
	}
	if pattern.Type != PatternSender {
		t.Errorf("expected type 'sender', got '%s'", pattern.Type)
	}
	if len(pattern.Conditions) != 1 {
		t.Errorf("expected 1 condition, got %d", len(pattern.Conditions))
	}
	if !pattern.Enabled {
		t.Error("expected pattern to be enabled by default")
	}
	if pattern.AutoGenerated {
		t.Error("expected pattern to not be auto-generated by default")
	}
	if pattern.Source != "manual" {
		t.Errorf("expected source 'manual', got '%s'", pattern.Source)
	}
}

func TestPatternValidate(t *testing.T) {
	tests := []struct {
		name      string
		pattern   *Pattern
		expectErr bool
	}{
		{
			name: "valid pattern",
			pattern: &Pattern{
				ID:       "pattern-1",
				TenantID: "tenant-1",
				Name:     "Test Pattern",
				Type:     PatternSender,
				Conditions: []PatternCondition{
					NewPatternCondition("sender", OpEquals, "test@example.com"),
				},
			},
			expectErr: false,
		},
		{
			name: "missing ID",
			pattern: &Pattern{
				TenantID: "tenant-1",
				Name:     "Test Pattern",
				Type:     PatternSender,
				Conditions: []PatternCondition{
					NewPatternCondition("sender", OpEquals, "test@example.com"),
				},
			},
			expectErr: true,
		},
		{
			name: "missing tenant ID",
			pattern: &Pattern{
				ID:   "pattern-1",
				Name: "Test Pattern",
				Type: PatternSender,
				Conditions: []PatternCondition{
					NewPatternCondition("sender", OpEquals, "test@example.com"),
				},
			},
			expectErr: true,
		},
		{
			name: "missing name",
			pattern: &Pattern{
				ID:       "pattern-1",
				TenantID: "tenant-1",
				Type:     PatternSender,
				Conditions: []PatternCondition{
					NewPatternCondition("sender", OpEquals, "test@example.com"),
				},
			},
			expectErr: true,
		},
		{
			name: "invalid type",
			pattern: &Pattern{
				ID:       "pattern-1",
				TenantID: "tenant-1",
				Name:     "Test Pattern",
				Type:     PatternType("invalid"),
				Conditions: []PatternCondition{
					NewPatternCondition("sender", OpEquals, "test@example.com"),
				},
			},
			expectErr: true,
		},
		{
			name: "no conditions",
			pattern: &Pattern{
				ID:         "pattern-1",
				TenantID:   "tenant-1",
				Name:       "Test Pattern",
				Type:       PatternSender,
				Conditions: []PatternCondition{},
			},
			expectErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.pattern.Validate()
			if (err != nil) != tt.expectErr {
				t.Errorf("expected error: %v, got: %v", tt.expectErr, err)
			}
		})
	}
}

func TestPatternClone(t *testing.T) {
	original := NewPattern("tenant-1", "Original", PatternSender, []PatternCondition{
		NewPatternCondition("sender", OpEquals, "test@example.com"),
	})
	original.Description = "Test description"
	original.Tags = []string{"tag1", "tag2"}
	original.Metadata["key"] = "value"

	clone := original.Clone()

	// Verify basic fields
	if clone.ID != original.ID {
		t.Error("clone ID should match original")
	}
	if clone.Name != original.Name {
		t.Error("clone name should match original")
	}

	// Verify independence
	clone.Name = "Modified"
	if original.Name == clone.Name {
		t.Error("modifying clone should not affect original")
	}

	clone.Tags[0] = "modified"
	if original.Tags[0] == "modified" {
		t.Error("modifying clone tags should not affect original")
	}

	clone.Metadata["key"] = "modified"
	if original.Metadata["key"] == "modified" {
		t.Error("modifying clone metadata should not affect original")
	}
}

func TestPatternAddExample(t *testing.T) {
	pattern := NewPattern("tenant-1", "Test", PatternSender, []PatternCondition{
		NewPatternCondition("sender", OpEquals, "test@example.com"),
	})

	example := PatternExample{
		ItemID:    "item-1",
		Timestamp: time.Now().UTC(),
		Action:    "accept",
	}

	pattern.AddExample(example)

	if len(pattern.Examples) != 1 {
		t.Errorf("expected 1 example, got %d", len(pattern.Examples))
	}
	if pattern.Examples[0].ItemID != "item-1" {
		t.Errorf("expected item ID 'item-1', got '%s'", pattern.Examples[0].ItemID)
	}
}

func TestPatternUpdateStats(t *testing.T) {
	pattern := NewPattern("tenant-1", "Test", PatternSender, []PatternCondition{
		NewPatternCondition("sender", OpEquals, "test@example.com"),
	})

	// Record some matches
	pattern.UpdateStats(true, false, 10)
	pattern.UpdateStats(true, false, 20)
	pattern.UpdateStats(true, true, 15)

	if pattern.Stats.TotalMatches != 3 {
		t.Errorf("expected 3 total matches, got %d", pattern.Stats.TotalMatches)
	}
	if pattern.Stats.SuccessfulActions != 2 {
		t.Errorf("expected 2 successful actions, got %d", pattern.Stats.SuccessfulActions)
	}
	if pattern.Stats.OverriddenActions != 1 {
		t.Errorf("expected 1 overridden action, got %d", pattern.Stats.OverriddenActions)
	}
	if pattern.Stats.LastMatchedAt == nil {
		t.Error("expected last matched at to be set")
	}

	// Check average processing time
	expectedAvg := (10.0 + 20.0 + 15.0) / 3.0
	if pattern.Stats.AverageProcessingTimeMs != expectedAvg {
		t.Errorf("expected avg processing time %f, got %f", expectedAvg, pattern.Stats.AverageProcessingTimeMs)
	}
}

func TestPatternCalculateConfidence(t *testing.T) {
	pattern := NewPattern("tenant-1", "Test", PatternSender, []PatternCondition{
		NewPatternCondition("sender", OpEquals, "test@example.com"),
	})

	// No matches - should be 0
	conf := pattern.CalculateConfidence()
	if conf != 0.0 {
		t.Errorf("expected 0 confidence with no matches, got %f", conf)
	}

	// Add successful actions
	for i := 0; i < 10; i++ {
		pattern.UpdateStats(true, false, 10)
	}

	conf = pattern.CalculateConfidence()
	if conf <= 0.0 || conf > 1.0 {
		t.Errorf("confidence should be between 0 and 1, got %f", conf)
	}
}

func TestPatternJSON(t *testing.T) {
	original := NewPattern("tenant-1", "Test Pattern", PatternSender, []PatternCondition{
		NewPatternCondition("sender", OpEquals, "test@example.com"),
	})
	original.Description = "Test description"
	original.Confidence = 0.85
	original.Tags = []string{"tag1", "tag2"}

	// Serialize
	data, err := original.ToJSON()
	if err != nil {
		t.Fatalf("failed to serialize pattern: %v", err)
	}

	// Deserialize
	restored, err := PatternFromJSON(data)
	if err != nil {
		t.Fatalf("failed to deserialize pattern: %v", err)
	}

	// Verify
	if restored.ID != original.ID {
		t.Errorf("ID mismatch: expected %s, got %s", original.ID, restored.ID)
	}
	if restored.Name != original.Name {
		t.Errorf("Name mismatch: expected %s, got %s", original.Name, restored.Name)
	}
	if restored.Confidence != original.Confidence {
		t.Errorf("Confidence mismatch: expected %f, got %f", original.Confidence, restored.Confidence)
	}
	if len(restored.Tags) != len(original.Tags) {
		t.Errorf("Tags length mismatch: expected %d, got %d", len(original.Tags), len(restored.Tags))
	}
}

func TestNewPatternSuggestion(t *testing.T) {
	pattern := NewPattern("tenant-1", "Test", PatternSender, []PatternCondition{
		NewPatternCondition("sender", OpEquals, "test@example.com"),
	})

	suggestion := NewPatternSuggestion("tenant-1", pattern, 0.85, 10)

	if suggestion.ID == "" {
		t.Error("expected suggestion ID to be set")
	}
	if suggestion.TenantID != "tenant-1" {
		t.Errorf("expected tenant ID 'tenant-1', got '%s'", suggestion.TenantID)
	}
	if suggestion.Confidence != 0.85 {
		t.Errorf("expected confidence 0.85, got %f", suggestion.Confidence)
	}
	if suggestion.SupportCount != 10 {
		t.Errorf("expected support count 10, got %d", suggestion.SupportCount)
	}
	if suggestion.Status != "pending" {
		t.Errorf("expected status 'pending', got '%s'", suggestion.Status)
	}
}

func TestPatternSuggestionApprove(t *testing.T) {
	pattern := NewPattern("tenant-1", "Test", PatternSender, []PatternCondition{
		NewPatternCondition("sender", OpEquals, "test@example.com"),
	})
	suggestion := NewPatternSuggestion("tenant-1", pattern, 0.85, 10)

	suggestion.Approve("admin@example.com")

	if suggestion.Status != "approved" {
		t.Errorf("expected status 'approved', got '%s'", suggestion.Status)
	}
	if suggestion.ReviewedAt == nil {
		t.Error("expected reviewed at to be set")
	}
	if suggestion.ReviewedBy != "admin@example.com" {
		t.Errorf("expected reviewed by 'admin@example.com', got '%s'", suggestion.ReviewedBy)
	}
}

func TestPatternSuggestionReject(t *testing.T) {
	pattern := NewPattern("tenant-1", "Test", PatternSender, []PatternCondition{
		NewPatternCondition("sender", OpEquals, "test@example.com"),
	})
	suggestion := NewPatternSuggestion("tenant-1", pattern, 0.85, 10)

	suggestion.Reject("moderator@example.com")

	if suggestion.Status != "rejected" {
		t.Errorf("expected status 'rejected', got '%s'", suggestion.Status)
	}
	if suggestion.ReviewedAt == nil {
		t.Error("expected reviewed at to be set")
	}
}

func TestPatternSet(t *testing.T) {
	ps := NewPatternSet("tenant-1")

	if ps.TenantID != "tenant-1" {
		t.Errorf("expected tenant ID 'tenant-1', got '%s'", ps.TenantID)
	}
	if !ps.Enabled {
		t.Error("expected pattern set to be enabled")
	}
	if len(ps.Patterns) != 0 {
		t.Errorf("expected 0 patterns, got %d", len(ps.Patterns))
	}

	// Add patterns
	p1 := NewPattern("tenant-1", "Pattern 1", PatternSender, []PatternCondition{
		NewPatternCondition("sender", OpEquals, "test@example.com"),
	})
	p1.Priority = 10

	p2 := NewPattern("tenant-1", "Pattern 2", PatternTopic, []PatternCondition{
		NewPatternCondition("category", OpEquals, "marketing"),
	})
	p2.Priority = 20

	ps.AddPattern(p1)
	ps.AddPattern(p2)

	if len(ps.Patterns) != 2 {
		t.Errorf("expected 2 patterns, got %d", len(ps.Patterns))
	}

	// Verify sorted by priority (highest first)
	if ps.Patterns[0].Priority != 20 {
		t.Error("patterns should be sorted by priority (highest first)")
	}

	// Get pattern by ID
	found := ps.GetPattern(p1.ID)
	if found == nil {
		t.Error("expected to find pattern by ID")
	}
	if found.Name != "Pattern 1" {
		t.Errorf("expected name 'Pattern 1', got '%s'", found.Name)
	}

	// Remove pattern
	removed := ps.RemovePattern(p1.ID)
	if !removed {
		t.Error("expected remove to return true")
	}
	if len(ps.Patterns) != 1 {
		t.Errorf("expected 1 pattern after removal, got %d", len(ps.Patterns))
	}

	// Try to remove non-existent
	removed = ps.RemovePattern("non-existent")
	if removed {
		t.Error("expected remove to return false for non-existent pattern")
	}
}

func TestPatternSetGetEnabled(t *testing.T) {
	ps := NewPatternSet("tenant-1")

	p1 := NewPattern("tenant-1", "Enabled", PatternSender, []PatternCondition{
		NewPatternCondition("sender", OpEquals, "test@example.com"),
	})
	p1.Enabled = true

	p2 := NewPattern("tenant-1", "Disabled", PatternTopic, []PatternCondition{
		NewPatternCondition("category", OpEquals, "marketing"),
	})
	p2.Enabled = false

	ps.AddPattern(p1)
	ps.AddPattern(p2)

	enabled := ps.GetEnabledPatterns()
	if len(enabled) != 1 {
		t.Errorf("expected 1 enabled pattern, got %d", len(enabled))
	}
	if enabled[0].Name != "Enabled" {
		t.Errorf("expected 'Enabled' pattern, got '%s'", enabled[0].Name)
	}
}

func TestPatternSetGetByType(t *testing.T) {
	ps := NewPatternSet("tenant-1")

	p1 := NewPattern("tenant-1", "Sender Pattern", PatternSender, []PatternCondition{
		NewPatternCondition("sender", OpEquals, "test@example.com"),
	})

	p2 := NewPattern("tenant-1", "Topic Pattern", PatternTopic, []PatternCondition{
		NewPatternCondition("category", OpEquals, "marketing"),
	})

	p3 := NewPattern("tenant-1", "Another Sender", PatternSender, []PatternCondition{
		NewPatternCondition("sender", OpEquals, "other@example.com"),
	})

	ps.AddPattern(p1)
	ps.AddPattern(p2)
	ps.AddPattern(p3)

	senderPatterns := ps.GetPatternsByType(PatternSender)
	if len(senderPatterns) != 2 {
		t.Errorf("expected 2 sender patterns, got %d", len(senderPatterns))
	}

	topicPatterns := ps.GetPatternsByType(PatternTopic)
	if len(topicPatterns) != 1 {
		t.Errorf("expected 1 topic pattern, got %d", len(topicPatterns))
	}

	timePatterns := ps.GetPatternsByType(PatternTime)
	if len(timePatterns) != 0 {
		t.Errorf("expected 0 time patterns, got %d", len(timePatterns))
	}
}

func TestPatternStatsJSON(t *testing.T) {
	stats := PatternStats{
		TotalMatches:          100,
		SuccessfulActions:     90,
		OverriddenActions:     10,
		AverageProcessingTimeMs: 15.5,
		TrendDirection:        1,
	}

	data, err := json.Marshal(stats)
	if err != nil {
		t.Fatalf("failed to marshal stats: %v", err)
	}

	var restored PatternStats
	if err := json.Unmarshal(data, &restored); err != nil {
		t.Fatalf("failed to unmarshal stats: %v", err)
	}

	if restored.TotalMatches != 100 {
		t.Errorf("expected 100 total matches, got %d", restored.TotalMatches)
	}
	if restored.SuccessfulActions != 90 {
		t.Errorf("expected 90 successful actions, got %d", restored.SuccessfulActions)
	}
}
