// Content Processor Service Protobuf Definitions
// Defines the gRPC service for managing content processing pipeline operations

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: content/v1/content.proto

package contentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContentProcessorService_ProcessContent_FullMethodName        = "/penfold.content.v1.ContentProcessorService/ProcessContent"
	ContentProcessorService_GetProcessingStatus_FullMethodName   = "/penfold.content.v1.ContentProcessorService/GetProcessingStatus"
	ContentProcessorService_GetContentItem_FullMethodName        = "/penfold.content.v1.ContentProcessorService/GetContentItem"
	ContentProcessorService_ListContentItems_FullMethodName      = "/penfold.content.v1.ContentProcessorService/ListContentItems"
	ContentProcessorService_ReprocessContent_FullMethodName      = "/penfold.content.v1.ContentProcessorService/ReprocessContent"
	ContentProcessorService_DeleteContentItem_FullMethodName     = "/penfold.content.v1.ContentProcessorService/DeleteContentItem"
	ContentProcessorService_DeleteContentItems_FullMethodName    = "/penfold.content.v1.ContentProcessorService/DeleteContentItems"
	ContentProcessorService_GetContentStats_FullMethodName       = "/penfold.content.v1.ContentProcessorService/GetContentStats"
	ContentProcessorService_GetContentText_FullMethodName        = "/penfold.content.v1.ContentProcessorService/GetContentText"
	ContentProcessorService_ListAvailableInsights_FullMethodName = "/penfold.content.v1.ContentProcessorService/ListAvailableInsights"
	ContentProcessorService_GetInsights_FullMethodName           = "/penfold.content.v1.ContentProcessorService/GetInsights"
	ContentProcessorService_GetContentTrace_FullMethodName       = "/penfold.content.v1.ContentProcessorService/GetContentTrace"
	ContentProcessorService_GetAssertions_FullMethodName         = "/penfold.content.v1.ContentProcessorService/GetAssertions"
	ContentProcessorService_PurgeContentItem_FullMethodName      = "/penfold.content.v1.ContentProcessorService/PurgeContentItem"
	ContentProcessorService_PurgeContentItems_FullMethodName     = "/penfold.content.v1.ContentProcessorService/PurgeContentItems"
	ContentProcessorService_ClearError_FullMethodName            = "/penfold.content.v1.ContentProcessorService/ClearError"
)

// ContentProcessorServiceClient is the client API for ContentProcessorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ContentProcessorService provides gRPC endpoints for content processing operations.
// This service manages the AI-powered content processing pipeline, including
// fetching, parsing, embedding generation, summarization, and entity extraction.
type ContentProcessorServiceClient interface {
	// ProcessContent triggers the content processing pipeline for a specific item.
	// Initiates async processing through configured stages (embed, summarize, extract).
	ProcessContent(ctx context.Context, in *ProcessContentRequest, opts ...grpc.CallOption) (*ProcessContentResponse, error)
	// GetProcessingStatus retrieves the current processing status of a content item.
	// Returns detailed stage completion information and any errors encountered.
	GetProcessingStatus(ctx context.Context, in *GetProcessingStatusRequest, opts ...grpc.CallOption) (*ProcessingStatus, error)
	// GetContentItem retrieves a specific content item by ID.
	// Returns the full content item including raw/processed content and metadata.
	GetContentItem(ctx context.Context, in *GetContentItemRequest, opts ...grpc.CallOption) (*ContentItem, error)
	// ListContentItems returns a paginated list of content items.
	// Supports filtering by source type, processing state, and time range.
	ListContentItems(ctx context.Context, in *ListContentItemsRequest, opts ...grpc.CallOption) (*ListContentItemsResponse, error)
	// ReprocessContent triggers reprocessing of an already-processed content item.
	// Useful for re-running processing after model updates or pipeline changes.
	ReprocessContent(ctx context.Context, in *ReprocessContentRequest, opts ...grpc.CallOption) (*ReprocessContentResponse, error)
	// DeleteContentItem removes a content item and all derived data.
	DeleteContentItem(ctx context.Context, in *DeleteContentItemRequest, opts ...grpc.CallOption) (*DeleteContentItemResponse, error)
	// DeleteContentItems bulk deletes content items matching filters.
	DeleteContentItems(ctx context.Context, in *DeleteContentItemsRequest, opts ...grpc.CallOption) (*DeleteContentItemsResponse, error)
	// GetContentStats returns content statistics.
	GetContentStats(ctx context.Context, in *GetContentStatsRequest, opts ...grpc.CallOption) (*ContentStats, error)
	// GetContentText retrieves the raw text content for a content item.
	GetContentText(ctx context.Context, in *GetContentTextRequest, opts ...grpc.CallOption) (*GetContentTextResponse, error)
	// ListAvailableInsights returns available insight types for a content item.
	ListAvailableInsights(ctx context.Context, in *ListAvailableInsightsRequest, opts ...grpc.CallOption) (*ListAvailableInsightsResponse, error)
	// GetInsights retrieves cached insights for a content item.
	GetInsights(ctx context.Context, in *GetInsightsRequest, opts ...grpc.CallOption) (*GetInsightsResponse, error)
	// GetContentTrace retrieves Langfuse traces associated with a content item.
	GetContentTrace(ctx context.Context, in *GetContentTraceRequest, opts ...grpc.CallOption) (*GetContentTraceResponse, error)
	// GetAssertions retrieves extracted assertions for a content item.
	GetAssertions(ctx context.Context, in *GetAssertionsRequest, opts ...grpc.CallOption) (*GetAssertionsResponse, error)
	// PurgeContentItem hard-deletes a content item and all derived data.
	// Only works on soft-deleted items. Requires confirm=true.
	PurgeContentItem(ctx context.Context, in *PurgeContentItemRequest, opts ...grpc.CallOption) (*PurgeContentItemResponse, error)
	// PurgeContentItems bulk hard-deletes soft-deleted content items.
	// Requires confirm=true.
	PurgeContentItems(ctx context.Context, in *PurgeContentItemsRequest, opts ...grpc.CallOption) (*PurgeContentItemsResponse, error)
	// ClearError clears error fields from a successfully reprocessed content item.
	ClearError(ctx context.Context, in *ClearErrorRequest, opts ...grpc.CallOption) (*ClearErrorResponse, error)
}

type contentProcessorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContentProcessorServiceClient(cc grpc.ClientConnInterface) ContentProcessorServiceClient {
	return &contentProcessorServiceClient{cc}
}

func (c *contentProcessorServiceClient) ProcessContent(ctx context.Context, in *ProcessContentRequest, opts ...grpc.CallOption) (*ProcessContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessContentResponse)
	err := c.cc.Invoke(ctx, ContentProcessorService_ProcessContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentProcessorServiceClient) GetProcessingStatus(ctx context.Context, in *GetProcessingStatusRequest, opts ...grpc.CallOption) (*ProcessingStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessingStatus)
	err := c.cc.Invoke(ctx, ContentProcessorService_GetProcessingStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentProcessorServiceClient) GetContentItem(ctx context.Context, in *GetContentItemRequest, opts ...grpc.CallOption) (*ContentItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentItem)
	err := c.cc.Invoke(ctx, ContentProcessorService_GetContentItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentProcessorServiceClient) ListContentItems(ctx context.Context, in *ListContentItemsRequest, opts ...grpc.CallOption) (*ListContentItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContentItemsResponse)
	err := c.cc.Invoke(ctx, ContentProcessorService_ListContentItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentProcessorServiceClient) ReprocessContent(ctx context.Context, in *ReprocessContentRequest, opts ...grpc.CallOption) (*ReprocessContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReprocessContentResponse)
	err := c.cc.Invoke(ctx, ContentProcessorService_ReprocessContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentProcessorServiceClient) DeleteContentItem(ctx context.Context, in *DeleteContentItemRequest, opts ...grpc.CallOption) (*DeleteContentItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteContentItemResponse)
	err := c.cc.Invoke(ctx, ContentProcessorService_DeleteContentItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentProcessorServiceClient) DeleteContentItems(ctx context.Context, in *DeleteContentItemsRequest, opts ...grpc.CallOption) (*DeleteContentItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteContentItemsResponse)
	err := c.cc.Invoke(ctx, ContentProcessorService_DeleteContentItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentProcessorServiceClient) GetContentStats(ctx context.Context, in *GetContentStatsRequest, opts ...grpc.CallOption) (*ContentStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentStats)
	err := c.cc.Invoke(ctx, ContentProcessorService_GetContentStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentProcessorServiceClient) GetContentText(ctx context.Context, in *GetContentTextRequest, opts ...grpc.CallOption) (*GetContentTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContentTextResponse)
	err := c.cc.Invoke(ctx, ContentProcessorService_GetContentText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentProcessorServiceClient) ListAvailableInsights(ctx context.Context, in *ListAvailableInsightsRequest, opts ...grpc.CallOption) (*ListAvailableInsightsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAvailableInsightsResponse)
	err := c.cc.Invoke(ctx, ContentProcessorService_ListAvailableInsights_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentProcessorServiceClient) GetInsights(ctx context.Context, in *GetInsightsRequest, opts ...grpc.CallOption) (*GetInsightsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInsightsResponse)
	err := c.cc.Invoke(ctx, ContentProcessorService_GetInsights_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentProcessorServiceClient) GetContentTrace(ctx context.Context, in *GetContentTraceRequest, opts ...grpc.CallOption) (*GetContentTraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContentTraceResponse)
	err := c.cc.Invoke(ctx, ContentProcessorService_GetContentTrace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentProcessorServiceClient) GetAssertions(ctx context.Context, in *GetAssertionsRequest, opts ...grpc.CallOption) (*GetAssertionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssertionsResponse)
	err := c.cc.Invoke(ctx, ContentProcessorService_GetAssertions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentProcessorServiceClient) PurgeContentItem(ctx context.Context, in *PurgeContentItemRequest, opts ...grpc.CallOption) (*PurgeContentItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeContentItemResponse)
	err := c.cc.Invoke(ctx, ContentProcessorService_PurgeContentItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentProcessorServiceClient) PurgeContentItems(ctx context.Context, in *PurgeContentItemsRequest, opts ...grpc.CallOption) (*PurgeContentItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeContentItemsResponse)
	err := c.cc.Invoke(ctx, ContentProcessorService_PurgeContentItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentProcessorServiceClient) ClearError(ctx context.Context, in *ClearErrorRequest, opts ...grpc.CallOption) (*ClearErrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearErrorResponse)
	err := c.cc.Invoke(ctx, ContentProcessorService_ClearError_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentProcessorServiceServer is the server API for ContentProcessorService service.
// All implementations must embed UnimplementedContentProcessorServiceServer
// for forward compatibility.
//
// ContentProcessorService provides gRPC endpoints for content processing operations.
// This service manages the AI-powered content processing pipeline, including
// fetching, parsing, embedding generation, summarization, and entity extraction.
type ContentProcessorServiceServer interface {
	// ProcessContent triggers the content processing pipeline for a specific item.
	// Initiates async processing through configured stages (embed, summarize, extract).
	ProcessContent(context.Context, *ProcessContentRequest) (*ProcessContentResponse, error)
	// GetProcessingStatus retrieves the current processing status of a content item.
	// Returns detailed stage completion information and any errors encountered.
	GetProcessingStatus(context.Context, *GetProcessingStatusRequest) (*ProcessingStatus, error)
	// GetContentItem retrieves a specific content item by ID.
	// Returns the full content item including raw/processed content and metadata.
	GetContentItem(context.Context, *GetContentItemRequest) (*ContentItem, error)
	// ListContentItems returns a paginated list of content items.
	// Supports filtering by source type, processing state, and time range.
	ListContentItems(context.Context, *ListContentItemsRequest) (*ListContentItemsResponse, error)
	// ReprocessContent triggers reprocessing of an already-processed content item.
	// Useful for re-running processing after model updates or pipeline changes.
	ReprocessContent(context.Context, *ReprocessContentRequest) (*ReprocessContentResponse, error)
	// DeleteContentItem removes a content item and all derived data.
	DeleteContentItem(context.Context, *DeleteContentItemRequest) (*DeleteContentItemResponse, error)
	// DeleteContentItems bulk deletes content items matching filters.
	DeleteContentItems(context.Context, *DeleteContentItemsRequest) (*DeleteContentItemsResponse, error)
	// GetContentStats returns content statistics.
	GetContentStats(context.Context, *GetContentStatsRequest) (*ContentStats, error)
	// GetContentText retrieves the raw text content for a content item.
	GetContentText(context.Context, *GetContentTextRequest) (*GetContentTextResponse, error)
	// ListAvailableInsights returns available insight types for a content item.
	ListAvailableInsights(context.Context, *ListAvailableInsightsRequest) (*ListAvailableInsightsResponse, error)
	// GetInsights retrieves cached insights for a content item.
	GetInsights(context.Context, *GetInsightsRequest) (*GetInsightsResponse, error)
	// GetContentTrace retrieves Langfuse traces associated with a content item.
	GetContentTrace(context.Context, *GetContentTraceRequest) (*GetContentTraceResponse, error)
	// GetAssertions retrieves extracted assertions for a content item.
	GetAssertions(context.Context, *GetAssertionsRequest) (*GetAssertionsResponse, error)
	// PurgeContentItem hard-deletes a content item and all derived data.
	// Only works on soft-deleted items. Requires confirm=true.
	PurgeContentItem(context.Context, *PurgeContentItemRequest) (*PurgeContentItemResponse, error)
	// PurgeContentItems bulk hard-deletes soft-deleted content items.
	// Requires confirm=true.
	PurgeContentItems(context.Context, *PurgeContentItemsRequest) (*PurgeContentItemsResponse, error)
	// ClearError clears error fields from a successfully reprocessed content item.
	ClearError(context.Context, *ClearErrorRequest) (*ClearErrorResponse, error)
	mustEmbedUnimplementedContentProcessorServiceServer()
}

// UnimplementedContentProcessorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentProcessorServiceServer struct{}

func (UnimplementedContentProcessorServiceServer) ProcessContent(context.Context, *ProcessContentRequest) (*ProcessContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessContent not implemented")
}
func (UnimplementedContentProcessorServiceServer) GetProcessingStatus(context.Context, *GetProcessingStatusRequest) (*ProcessingStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProcessingStatus not implemented")
}
func (UnimplementedContentProcessorServiceServer) GetContentItem(context.Context, *GetContentItemRequest) (*ContentItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContentItem not implemented")
}
func (UnimplementedContentProcessorServiceServer) ListContentItems(context.Context, *ListContentItemsRequest) (*ListContentItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListContentItems not implemented")
}
func (UnimplementedContentProcessorServiceServer) ReprocessContent(context.Context, *ReprocessContentRequest) (*ReprocessContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReprocessContent not implemented")
}
func (UnimplementedContentProcessorServiceServer) DeleteContentItem(context.Context, *DeleteContentItemRequest) (*DeleteContentItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteContentItem not implemented")
}
func (UnimplementedContentProcessorServiceServer) DeleteContentItems(context.Context, *DeleteContentItemsRequest) (*DeleteContentItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteContentItems not implemented")
}
func (UnimplementedContentProcessorServiceServer) GetContentStats(context.Context, *GetContentStatsRequest) (*ContentStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContentStats not implemented")
}
func (UnimplementedContentProcessorServiceServer) GetContentText(context.Context, *GetContentTextRequest) (*GetContentTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContentText not implemented")
}
func (UnimplementedContentProcessorServiceServer) ListAvailableInsights(context.Context, *ListAvailableInsightsRequest) (*ListAvailableInsightsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAvailableInsights not implemented")
}
func (UnimplementedContentProcessorServiceServer) GetInsights(context.Context, *GetInsightsRequest) (*GetInsightsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInsights not implemented")
}
func (UnimplementedContentProcessorServiceServer) GetContentTrace(context.Context, *GetContentTraceRequest) (*GetContentTraceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContentTrace not implemented")
}
func (UnimplementedContentProcessorServiceServer) GetAssertions(context.Context, *GetAssertionsRequest) (*GetAssertionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssertions not implemented")
}
func (UnimplementedContentProcessorServiceServer) PurgeContentItem(context.Context, *PurgeContentItemRequest) (*PurgeContentItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeContentItem not implemented")
}
func (UnimplementedContentProcessorServiceServer) PurgeContentItems(context.Context, *PurgeContentItemsRequest) (*PurgeContentItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeContentItems not implemented")
}
func (UnimplementedContentProcessorServiceServer) ClearError(context.Context, *ClearErrorRequest) (*ClearErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearError not implemented")
}
func (UnimplementedContentProcessorServiceServer) mustEmbedUnimplementedContentProcessorServiceServer() {
}
func (UnimplementedContentProcessorServiceServer) testEmbeddedByValue() {}

// UnsafeContentProcessorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentProcessorServiceServer will
// result in compilation errors.
type UnsafeContentProcessorServiceServer interface {
	mustEmbedUnimplementedContentProcessorServiceServer()
}

func RegisterContentProcessorServiceServer(s grpc.ServiceRegistrar, srv ContentProcessorServiceServer) {
	// If the following call pancis, it indicates UnimplementedContentProcessorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContentProcessorService_ServiceDesc, srv)
}

func _ContentProcessorService_ProcessContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentProcessorServiceServer).ProcessContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentProcessorService_ProcessContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentProcessorServiceServer).ProcessContent(ctx, req.(*ProcessContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentProcessorService_GetProcessingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProcessingStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentProcessorServiceServer).GetProcessingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentProcessorService_GetProcessingStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentProcessorServiceServer).GetProcessingStatus(ctx, req.(*GetProcessingStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentProcessorService_GetContentItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentProcessorServiceServer).GetContentItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentProcessorService_GetContentItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentProcessorServiceServer).GetContentItem(ctx, req.(*GetContentItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentProcessorService_ListContentItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContentItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentProcessorServiceServer).ListContentItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentProcessorService_ListContentItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentProcessorServiceServer).ListContentItems(ctx, req.(*ListContentItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentProcessorService_ReprocessContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReprocessContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentProcessorServiceServer).ReprocessContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentProcessorService_ReprocessContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentProcessorServiceServer).ReprocessContent(ctx, req.(*ReprocessContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentProcessorService_DeleteContentItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContentItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentProcessorServiceServer).DeleteContentItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentProcessorService_DeleteContentItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentProcessorServiceServer).DeleteContentItem(ctx, req.(*DeleteContentItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentProcessorService_DeleteContentItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContentItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentProcessorServiceServer).DeleteContentItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentProcessorService_DeleteContentItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentProcessorServiceServer).DeleteContentItems(ctx, req.(*DeleteContentItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentProcessorService_GetContentStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentProcessorServiceServer).GetContentStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentProcessorService_GetContentStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentProcessorServiceServer).GetContentStats(ctx, req.(*GetContentStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentProcessorService_GetContentText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentProcessorServiceServer).GetContentText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentProcessorService_GetContentText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentProcessorServiceServer).GetContentText(ctx, req.(*GetContentTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentProcessorService_ListAvailableInsights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAvailableInsightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentProcessorServiceServer).ListAvailableInsights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentProcessorService_ListAvailableInsights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentProcessorServiceServer).ListAvailableInsights(ctx, req.(*ListAvailableInsightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentProcessorService_GetInsights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInsightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentProcessorServiceServer).GetInsights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentProcessorService_GetInsights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentProcessorServiceServer).GetInsights(ctx, req.(*GetInsightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentProcessorService_GetContentTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentProcessorServiceServer).GetContentTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentProcessorService_GetContentTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentProcessorServiceServer).GetContentTrace(ctx, req.(*GetContentTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentProcessorService_GetAssertions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssertionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentProcessorServiceServer).GetAssertions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentProcessorService_GetAssertions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentProcessorServiceServer).GetAssertions(ctx, req.(*GetAssertionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentProcessorService_PurgeContentItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeContentItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentProcessorServiceServer).PurgeContentItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentProcessorService_PurgeContentItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentProcessorServiceServer).PurgeContentItem(ctx, req.(*PurgeContentItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentProcessorService_PurgeContentItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeContentItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentProcessorServiceServer).PurgeContentItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentProcessorService_PurgeContentItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentProcessorServiceServer).PurgeContentItems(ctx, req.(*PurgeContentItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentProcessorService_ClearError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentProcessorServiceServer).ClearError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentProcessorService_ClearError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentProcessorServiceServer).ClearError(ctx, req.(*ClearErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContentProcessorService_ServiceDesc is the grpc.ServiceDesc for ContentProcessorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentProcessorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "penfold.content.v1.ContentProcessorService",
	HandlerType: (*ContentProcessorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessContent",
			Handler:    _ContentProcessorService_ProcessContent_Handler,
		},
		{
			MethodName: "GetProcessingStatus",
			Handler:    _ContentProcessorService_GetProcessingStatus_Handler,
		},
		{
			MethodName: "GetContentItem",
			Handler:    _ContentProcessorService_GetContentItem_Handler,
		},
		{
			MethodName: "ListContentItems",
			Handler:    _ContentProcessorService_ListContentItems_Handler,
		},
		{
			MethodName: "ReprocessContent",
			Handler:    _ContentProcessorService_ReprocessContent_Handler,
		},
		{
			MethodName: "DeleteContentItem",
			Handler:    _ContentProcessorService_DeleteContentItem_Handler,
		},
		{
			MethodName: "DeleteContentItems",
			Handler:    _ContentProcessorService_DeleteContentItems_Handler,
		},
		{
			MethodName: "GetContentStats",
			Handler:    _ContentProcessorService_GetContentStats_Handler,
		},
		{
			MethodName: "GetContentText",
			Handler:    _ContentProcessorService_GetContentText_Handler,
		},
		{
			MethodName: "ListAvailableInsights",
			Handler:    _ContentProcessorService_ListAvailableInsights_Handler,
		},
		{
			MethodName: "GetInsights",
			Handler:    _ContentProcessorService_GetInsights_Handler,
		},
		{
			MethodName: "GetContentTrace",
			Handler:    _ContentProcessorService_GetContentTrace_Handler,
		},
		{
			MethodName: "GetAssertions",
			Handler:    _ContentProcessorService_GetAssertions_Handler,
		},
		{
			MethodName: "PurgeContentItem",
			Handler:    _ContentProcessorService_PurgeContentItem_Handler,
		},
		{
			MethodName: "PurgeContentItems",
			Handler:    _ContentProcessorService_PurgeContentItems_Handler,
		},
		{
			MethodName: "ClearError",
			Handler:    _ContentProcessorService_ClearError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "content/v1/content.proto",
}
