// Content Processor Service Protobuf Definitions
// Defines the gRPC service for managing content processing pipeline operations

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: contentpb/content.proto

package contentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProcessingStage represents stages in the content processing pipeline.
// Processing proceeds through these stages in order.
type ProcessingStage int32

const (
	// Default value. Should not be used explicitly.
	ProcessingStage_PROCESSING_STAGE_UNSPECIFIED ProcessingStage = 0
	// Fetching raw content from the source system.
	ProcessingStage_PROCESSING_STAGE_FETCH ProcessingStage = 1
	// Parsing and normalizing content structure.
	ProcessingStage_PROCESSING_STAGE_PARSE ProcessingStage = 2
	// Generating vector embeddings for semantic search.
	ProcessingStage_PROCESSING_STAGE_EMBED ProcessingStage = 3
	// Generating AI summaries of content.
	ProcessingStage_PROCESSING_STAGE_SUMMARIZE ProcessingStage = 4
	// Extracting entities, assertions, and structured data.
	ProcessingStage_PROCESSING_STAGE_EXTRACT ProcessingStage = 5
	// All processing stages completed successfully.
	ProcessingStage_PROCESSING_STAGE_COMPLETE ProcessingStage = 6
)

// Enum value maps for ProcessingStage.
var (
	ProcessingStage_name = map[int32]string{
		0: "PROCESSING_STAGE_UNSPECIFIED",
		1: "PROCESSING_STAGE_FETCH",
		2: "PROCESSING_STAGE_PARSE",
		3: "PROCESSING_STAGE_EMBED",
		4: "PROCESSING_STAGE_SUMMARIZE",
		5: "PROCESSING_STAGE_EXTRACT",
		6: "PROCESSING_STAGE_COMPLETE",
	}
	ProcessingStage_value = map[string]int32{
		"PROCESSING_STAGE_UNSPECIFIED": 0,
		"PROCESSING_STAGE_FETCH":       1,
		"PROCESSING_STAGE_PARSE":       2,
		"PROCESSING_STAGE_EMBED":       3,
		"PROCESSING_STAGE_SUMMARIZE":   4,
		"PROCESSING_STAGE_EXTRACT":     5,
		"PROCESSING_STAGE_COMPLETE":    6,
	}
)

func (x ProcessingStage) Enum() *ProcessingStage {
	p := new(ProcessingStage)
	*p = x
	return p
}

func (x ProcessingStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessingStage) Descriptor() protoreflect.EnumDescriptor {
	return file_contentpb_content_proto_enumTypes[0].Descriptor()
}

func (ProcessingStage) Type() protoreflect.EnumType {
	return &file_contentpb_content_proto_enumTypes[0]
}

func (x ProcessingStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessingStage.Descriptor instead.
func (ProcessingStage) EnumDescriptor() ([]byte, []int) {
	return file_contentpb_content_proto_rawDescGZIP(), []int{0}
}

// ProcessingState represents the overall processing state of a content item.
type ProcessingState int32

const (
	// Default value. Should not be used explicitly.
	ProcessingState_PROCESSING_STATE_UNSPECIFIED ProcessingState = 0
	// Content item is queued for processing.
	ProcessingState_PROCESSING_STATE_PENDING ProcessingState = 1
	// Content item is currently being processed.
	ProcessingState_PROCESSING_STATE_IN_PROGRESS ProcessingState = 2
	// Processing completed successfully.
	ProcessingState_PROCESSING_STATE_COMPLETED ProcessingState = 3
	// Processing failed with an error.
	ProcessingState_PROCESSING_STATE_FAILED ProcessingState = 4
	// Processing was cancelled.
	ProcessingState_PROCESSING_STATE_CANCELLED ProcessingState = 5
)

// Enum value maps for ProcessingState.
var (
	ProcessingState_name = map[int32]string{
		0: "PROCESSING_STATE_UNSPECIFIED",
		1: "PROCESSING_STATE_PENDING",
		2: "PROCESSING_STATE_IN_PROGRESS",
		3: "PROCESSING_STATE_COMPLETED",
		4: "PROCESSING_STATE_FAILED",
		5: "PROCESSING_STATE_CANCELLED",
	}
	ProcessingState_value = map[string]int32{
		"PROCESSING_STATE_UNSPECIFIED": 0,
		"PROCESSING_STATE_PENDING":     1,
		"PROCESSING_STATE_IN_PROGRESS": 2,
		"PROCESSING_STATE_COMPLETED":   3,
		"PROCESSING_STATE_FAILED":      4,
		"PROCESSING_STATE_CANCELLED":   5,
	}
)

func (x ProcessingState) Enum() *ProcessingState {
	p := new(ProcessingState)
	*p = x
	return p
}

func (x ProcessingState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessingState) Descriptor() protoreflect.EnumDescriptor {
	return file_contentpb_content_proto_enumTypes[1].Descriptor()
}

func (ProcessingState) Type() protoreflect.EnumType {
	return &file_contentpb_content_proto_enumTypes[1]
}

func (x ProcessingState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessingState.Descriptor instead.
func (ProcessingState) EnumDescriptor() ([]byte, []int) {
	return file_contentpb_content_proto_rawDescGZIP(), []int{1}
}

// ContentItem represents a unit of content in the processing pipeline.
// Contains both raw and processed representations along with metadata.
type ContentItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this content item.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Type of source this content originated from: "email", "document", "meeting", "slack".
	SourceType string `protobuf:"bytes,2,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	// Identifier of the source record in the originating system.
	SourceId string `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// Tenant identifier for multi-tenancy support.
	TenantId string `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Raw content text as received from the source.
	RawContent string `protobuf:"bytes,5,opt,name=raw_content,json=rawContent,proto3" json:"raw_content,omitempty"`
	// Processed/normalized content text after parsing stage.
	ProcessedContent *string `protobuf:"bytes,6,opt,name=processed_content,json=processedContent,proto3,oneof" json:"processed_content,omitempty"`
	// Vector embedding as float array.
	// Dimensions depend on the embedding model used (typically 768 or 1536).
	Embedding []float32 `protobuf:"fixed32,7,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	// AI-generated summary of the content.
	Summary *string `protobuf:"bytes,8,opt,name=summary,proto3,oneof" json:"summary,omitempty"`
	// Additional metadata key-value pairs.
	// May include source-specific attributes like author, recipients, subject, etc.
	Metadata map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Current processing state of this content item.
	State ProcessingState `protobuf:"varint,10,opt,name=state,proto3,enum=penfold.processing.content.v1.ProcessingState" json:"state,omitempty"`
	// Timestamp when this content item was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp when this content item was last updated.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Timestamp when processing completed (if state is COMPLETED).
	ProcessedAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=processed_at,json=processedAt,proto3,oneof" json:"processed_at,omitempty"`
	// Content hash for deduplication and change detection.
	ContentHash   string `protobuf:"bytes,14,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentItem) Reset() {
	*x = ContentItem{}
	mi := &file_contentpb_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentItem) ProtoMessage() {}

func (x *ContentItem) ProtoReflect() protoreflect.Message {
	mi := &file_contentpb_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentItem.ProtoReflect.Descriptor instead.
func (*ContentItem) Descriptor() ([]byte, []int) {
	return file_contentpb_content_proto_rawDescGZIP(), []int{0}
}

func (x *ContentItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContentItem) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *ContentItem) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *ContentItem) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ContentItem) GetRawContent() string {
	if x != nil {
		return x.RawContent
	}
	return ""
}

func (x *ContentItem) GetProcessedContent() string {
	if x != nil && x.ProcessedContent != nil {
		return *x.ProcessedContent
	}
	return ""
}

func (x *ContentItem) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *ContentItem) GetSummary() string {
	if x != nil && x.Summary != nil {
		return *x.Summary
	}
	return ""
}

func (x *ContentItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ContentItem) GetState() ProcessingState {
	if x != nil {
		return x.State
	}
	return ProcessingState_PROCESSING_STATE_UNSPECIFIED
}

func (x *ContentItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ContentItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ContentItem) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

func (x *ContentItem) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

// ProcessContentRequest triggers content processing for a specific item.
type ProcessContentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the content item to process.
	ContentId string `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	// Processing options to customize the pipeline behavior.
	Options       *ProcessingOptions `protobuf:"bytes,2,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessContentRequest) Reset() {
	*x = ProcessContentRequest{}
	mi := &file_contentpb_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessContentRequest) ProtoMessage() {}

func (x *ProcessContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentpb_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessContentRequest.ProtoReflect.Descriptor instead.
func (*ProcessContentRequest) Descriptor() ([]byte, []int) {
	return file_contentpb_content_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessContentRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *ProcessContentRequest) GetOptions() *ProcessingOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// ProcessingOptions configures the content processing pipeline behavior.
type ProcessingOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether to skip the embedding generation stage.
	SkipEmbedding bool `protobuf:"varint,1,opt,name=skip_embedding,json=skipEmbedding,proto3" json:"skip_embedding,omitempty"`
	// Whether to skip the summarization stage.
	SkipSummarization bool `protobuf:"varint,2,opt,name=skip_summarization,json=skipSummarization,proto3" json:"skip_summarization,omitempty"`
	// Whether to skip the entity extraction stage.
	SkipExtraction bool `protobuf:"varint,3,opt,name=skip_extraction,json=skipExtraction,proto3" json:"skip_extraction,omitempty"`
	// Force reprocessing even if content hasn't changed.
	ForceReprocess bool `protobuf:"varint,4,opt,name=force_reprocess,json=forceReprocess,proto3" json:"force_reprocess,omitempty"`
	// Priority level for processing queue (1=highest, 10=lowest).
	Priority int32 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	// Maximum time in seconds to wait for processing to complete.
	// Used for synchronous processing requests. Default: 300 (5 minutes).
	TimeoutSeconds *int32 `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3,oneof" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessingOptions) Reset() {
	*x = ProcessingOptions{}
	mi := &file_contentpb_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingOptions) ProtoMessage() {}

func (x *ProcessingOptions) ProtoReflect() protoreflect.Message {
	mi := &file_contentpb_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingOptions.ProtoReflect.Descriptor instead.
func (*ProcessingOptions) Descriptor() ([]byte, []int) {
	return file_contentpb_content_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessingOptions) GetSkipEmbedding() bool {
	if x != nil {
		return x.SkipEmbedding
	}
	return false
}

func (x *ProcessingOptions) GetSkipSummarization() bool {
	if x != nil {
		return x.SkipSummarization
	}
	return false
}

func (x *ProcessingOptions) GetSkipExtraction() bool {
	if x != nil {
		return x.SkipExtraction
	}
	return false
}

func (x *ProcessingOptions) GetForceReprocess() bool {
	if x != nil {
		return x.ForceReprocess
	}
	return false
}

func (x *ProcessingOptions) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ProcessingOptions) GetTimeoutSeconds() int32 {
	if x != nil && x.TimeoutSeconds != nil {
		return *x.TimeoutSeconds
	}
	return 0
}

// ProcessContentResponse returns the result of initiating content processing.
type ProcessContentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the content item being processed.
	ContentId string `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	// Processing job identifier for tracking this specific processing run.
	JobId string `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Current processing status after request was submitted.
	Status        *ProcessingStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessContentResponse) Reset() {
	*x = ProcessContentResponse{}
	mi := &file_contentpb_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessContentResponse) ProtoMessage() {}

func (x *ProcessContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentpb_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessContentResponse.ProtoReflect.Descriptor instead.
func (*ProcessContentResponse) Descriptor() ([]byte, []int) {
	return file_contentpb_content_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessContentResponse) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *ProcessContentResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ProcessContentResponse) GetStatus() *ProcessingStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// GetProcessingStatusRequest retrieves processing status for a content item.
type GetProcessingStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the content item.
	ContentId string `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	// Optional: specific job ID to check status of.
	// If not provided, returns status of the most recent processing job.
	JobId         *string `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3,oneof" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessingStatusRequest) Reset() {
	*x = GetProcessingStatusRequest{}
	mi := &file_contentpb_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessingStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessingStatusRequest) ProtoMessage() {}

func (x *GetProcessingStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentpb_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessingStatusRequest.ProtoReflect.Descriptor instead.
func (*GetProcessingStatusRequest) Descriptor() ([]byte, []int) {
	return file_contentpb_content_proto_rawDescGZIP(), []int{4}
}

func (x *GetProcessingStatusRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *GetProcessingStatusRequest) GetJobId() string {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return ""
}

// ProcessingStatus provides detailed status of content processing.
type ProcessingStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the content item.
	ContentId string `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	// Processing job identifier.
	JobId string `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Overall processing state.
	State ProcessingState `protobuf:"varint,3,opt,name=state,proto3,enum=penfold.processing.content.v1.ProcessingState" json:"state,omitempty"`
	// List of processing stages that have completed successfully.
	StagesCompleted []ProcessingStage `protobuf:"varint,4,rep,packed,name=stages_completed,json=stagesCompleted,proto3,enum=penfold.processing.content.v1.ProcessingStage" json:"stages_completed,omitempty"`
	// Current stage being processed (if state is IN_PROGRESS).
	CurrentStage *ProcessingStage `protobuf:"varint,5,opt,name=current_stage,json=currentStage,proto3,enum=penfold.processing.content.v1.ProcessingStage,oneof" json:"current_stage,omitempty"`
	// List of errors encountered during processing.
	Errors []*ProcessingError `protobuf:"bytes,6,rep,name=errors,proto3" json:"errors,omitempty"`
	// Timestamp when processing started.
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	// Timestamp when processing completed or failed.
	FinishedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=finished_at,json=finishedAt,proto3,oneof" json:"finished_at,omitempty"`
	// Processing duration in milliseconds.
	DurationMs *int64 `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3,oneof" json:"duration_ms,omitempty"`
	// Percentage of processing complete (0-100).
	ProgressPercent int32 `protobuf:"varint,10,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessingStatus) Reset() {
	*x = ProcessingStatus{}
	mi := &file_contentpb_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingStatus) ProtoMessage() {}

func (x *ProcessingStatus) ProtoReflect() protoreflect.Message {
	mi := &file_contentpb_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingStatus.ProtoReflect.Descriptor instead.
func (*ProcessingStatus) Descriptor() ([]byte, []int) {
	return file_contentpb_content_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessingStatus) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *ProcessingStatus) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ProcessingStatus) GetState() ProcessingState {
	if x != nil {
		return x.State
	}
	return ProcessingState_PROCESSING_STATE_UNSPECIFIED
}

func (x *ProcessingStatus) GetStagesCompleted() []ProcessingStage {
	if x != nil {
		return x.StagesCompleted
	}
	return nil
}

func (x *ProcessingStatus) GetCurrentStage() ProcessingStage {
	if x != nil && x.CurrentStage != nil {
		return *x.CurrentStage
	}
	return ProcessingStage_PROCESSING_STAGE_UNSPECIFIED
}

func (x *ProcessingStatus) GetErrors() []*ProcessingError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ProcessingStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ProcessingStatus) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *ProcessingStatus) GetDurationMs() int64 {
	if x != nil && x.DurationMs != nil {
		return *x.DurationMs
	}
	return 0
}

func (x *ProcessingStatus) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

// ProcessingError represents an error that occurred during processing.
type ProcessingError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The processing stage where the error occurred.
	Stage ProcessingStage `protobuf:"varint,1,opt,name=stage,proto3,enum=penfold.processing.content.v1.ProcessingStage" json:"stage,omitempty"`
	// Machine-readable error code.
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable error message.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Timestamp when the error occurred.
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// Whether this error is retryable.
	Retryable bool `protobuf:"varint,5,opt,name=retryable,proto3" json:"retryable,omitempty"`
	// Number of retry attempts made for this stage.
	RetryCount    int32 `protobuf:"varint,6,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessingError) Reset() {
	*x = ProcessingError{}
	mi := &file_contentpb_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingError) ProtoMessage() {}

func (x *ProcessingError) ProtoReflect() protoreflect.Message {
	mi := &file_contentpb_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingError.ProtoReflect.Descriptor instead.
func (*ProcessingError) Descriptor() ([]byte, []int) {
	return file_contentpb_content_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessingError) GetStage() ProcessingStage {
	if x != nil {
		return x.Stage
	}
	return ProcessingStage_PROCESSING_STAGE_UNSPECIFIED
}

func (x *ProcessingError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ProcessingError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessingError) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *ProcessingError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ProcessingError) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

// GetContentItemRequest retrieves a specific content item.
type GetContentItemRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the content item to retrieve.
	ContentId string `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	// Whether to include the full embedding vector in the response.
	// Default: false (embedding can be large).
	IncludeEmbedding bool `protobuf:"varint,2,opt,name=include_embedding,json=includeEmbedding,proto3" json:"include_embedding,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetContentItemRequest) Reset() {
	*x = GetContentItemRequest{}
	mi := &file_contentpb_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentItemRequest) ProtoMessage() {}

func (x *GetContentItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentpb_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentItemRequest.ProtoReflect.Descriptor instead.
func (*GetContentItemRequest) Descriptor() ([]byte, []int) {
	return file_contentpb_content_proto_rawDescGZIP(), []int{7}
}

func (x *GetContentItemRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *GetContentItemRequest) GetIncludeEmbedding() bool {
	if x != nil {
		return x.IncludeEmbedding
	}
	return false
}

// ListContentItemsRequest retrieves a paginated list of content items.
type ListContentItemsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by source type (optional): "email", "document", "meeting", "slack".
	SourceType *string `protobuf:"bytes,1,opt,name=source_type,json=sourceType,proto3,oneof" json:"source_type,omitempty"`
	// Filter by processing state (optional).
	State *ProcessingState `protobuf:"varint,2,opt,name=state,proto3,enum=penfold.processing.content.v1.ProcessingState,oneof" json:"state,omitempty"`
	// Filter by tenant ID (required for multi-tenant queries).
	TenantId string `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Filter by content created after this time (optional).
	CreatedAfter *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_after,json=createdAfter,proto3,oneof" json:"created_after,omitempty"`
	// Filter by content created before this time (optional).
	CreatedBefore *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_before,json=createdBefore,proto3,oneof" json:"created_before,omitempty"`
	// Maximum number of results to return per page (default: 50, max: 1000).
	PageSize int32 `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Pagination token from previous response.
	PageToken string `protobuf:"bytes,7,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Whether to include the full embedding vectors in responses.
	// Default: false (embeddings can be large and slow down responses).
	IncludeEmbeddings bool `protobuf:"varint,8,opt,name=include_embeddings,json=includeEmbeddings,proto3" json:"include_embeddings,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListContentItemsRequest) Reset() {
	*x = ListContentItemsRequest{}
	mi := &file_contentpb_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContentItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContentItemsRequest) ProtoMessage() {}

func (x *ListContentItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentpb_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContentItemsRequest.ProtoReflect.Descriptor instead.
func (*ListContentItemsRequest) Descriptor() ([]byte, []int) {
	return file_contentpb_content_proto_rawDescGZIP(), []int{8}
}

func (x *ListContentItemsRequest) GetSourceType() string {
	if x != nil && x.SourceType != nil {
		return *x.SourceType
	}
	return ""
}

func (x *ListContentItemsRequest) GetState() ProcessingState {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ProcessingState_PROCESSING_STATE_UNSPECIFIED
}

func (x *ListContentItemsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListContentItemsRequest) GetCreatedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAfter
	}
	return nil
}

func (x *ListContentItemsRequest) GetCreatedBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedBefore
	}
	return nil
}

func (x *ListContentItemsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListContentItemsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListContentItemsRequest) GetIncludeEmbeddings() bool {
	if x != nil {
		return x.IncludeEmbeddings
	}
	return false
}

// ListContentItemsResponse contains a paginated list of content items.
type ListContentItemsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of content items matching the query.
	Items []*ContentItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Token for fetching the next page (empty if no more results).
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total count of items matching the query (if available).
	TotalCount    *int64 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3,oneof" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContentItemsResponse) Reset() {
	*x = ListContentItemsResponse{}
	mi := &file_contentpb_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContentItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContentItemsResponse) ProtoMessage() {}

func (x *ListContentItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentpb_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContentItemsResponse.ProtoReflect.Descriptor instead.
func (*ListContentItemsResponse) Descriptor() ([]byte, []int) {
	return file_contentpb_content_proto_rawDescGZIP(), []int{9}
}

func (x *ListContentItemsResponse) GetItems() []*ContentItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListContentItemsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListContentItemsResponse) GetTotalCount() int64 {
	if x != nil && x.TotalCount != nil {
		return *x.TotalCount
	}
	return 0
}

// ReprocessContentRequest triggers reprocessing of an already-processed item.
type ReprocessContentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the content item to reprocess.
	ContentId string `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	// Reason for reprocessing (for audit trail).
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Processing options to customize the reprocessing behavior.
	Options *ProcessingOptions `protobuf:"bytes,3,opt,name=options,proto3,oneof" json:"options,omitempty"`
	// Which stages to reprocess. If empty, all stages are reprocessed.
	StagesToReprocess []ProcessingStage `protobuf:"varint,4,rep,packed,name=stages_to_reprocess,json=stagesToReprocess,proto3,enum=penfold.processing.content.v1.ProcessingStage" json:"stages_to_reprocess,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReprocessContentRequest) Reset() {
	*x = ReprocessContentRequest{}
	mi := &file_contentpb_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReprocessContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReprocessContentRequest) ProtoMessage() {}

func (x *ReprocessContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentpb_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReprocessContentRequest.ProtoReflect.Descriptor instead.
func (*ReprocessContentRequest) Descriptor() ([]byte, []int) {
	return file_contentpb_content_proto_rawDescGZIP(), []int{10}
}

func (x *ReprocessContentRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *ReprocessContentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReprocessContentRequest) GetOptions() *ProcessingOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ReprocessContentRequest) GetStagesToReprocess() []ProcessingStage {
	if x != nil {
		return x.StagesToReprocess
	}
	return nil
}

// ReprocessContentResponse returns the result of initiating reprocessing.
type ReprocessContentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the content item being reprocessed.
	ContentId string `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	// New processing job identifier for tracking this reprocessing run.
	JobId string `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Previous processing job identifier (for comparison).
	PreviousJobId string `protobuf:"bytes,3,opt,name=previous_job_id,json=previousJobId,proto3" json:"previous_job_id,omitempty"`
	// Current processing status after request was submitted.
	Status        *ProcessingStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReprocessContentResponse) Reset() {
	*x = ReprocessContentResponse{}
	mi := &file_contentpb_content_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReprocessContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReprocessContentResponse) ProtoMessage() {}

func (x *ReprocessContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentpb_content_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReprocessContentResponse.ProtoReflect.Descriptor instead.
func (*ReprocessContentResponse) Descriptor() ([]byte, []int) {
	return file_contentpb_content_proto_rawDescGZIP(), []int{11}
}

func (x *ReprocessContentResponse) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *ReprocessContentResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReprocessContentResponse) GetPreviousJobId() string {
	if x != nil {
		return x.PreviousJobId
	}
	return ""
}

func (x *ReprocessContentResponse) GetStatus() *ProcessingStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_contentpb_content_proto protoreflect.FileDescriptor

const file_contentpb_content_proto_rawDesc = "" +
	"\n" +
	"\x17contentpb/content.proto\x12\x1dpenfold.processing.content.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf1\x05\n" +
	"\vContentItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vsource_type\x18\x02 \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12\x1f\n" +
	"\vraw_content\x18\x05 \x01(\tR\n" +
	"rawContent\x120\n" +
	"\x11processed_content\x18\x06 \x01(\tH\x00R\x10processedContent\x88\x01\x01\x12\x1c\n" +
	"\tembedding\x18\a \x03(\x02R\tembedding\x12\x1d\n" +
	"\asummary\x18\b \x01(\tH\x01R\asummary\x88\x01\x01\x12T\n" +
	"\bmetadata\x18\t \x03(\v28.penfold.processing.content.v1.ContentItem.MetadataEntryR\bmetadata\x12D\n" +
	"\x05state\x18\n" +
	" \x01(\x0e2..penfold.processing.content.v1.ProcessingStateR\x05state\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12B\n" +
	"\fprocessed_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampH\x02R\vprocessedAt\x88\x01\x01\x12!\n" +
	"\fcontent_hash\x18\x0e \x01(\tR\vcontentHash\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x14\n" +
	"\x12_processed_contentB\n" +
	"\n" +
	"\b_summaryB\x0f\n" +
	"\r_processed_at\"\x93\x01\n" +
	"\x15ProcessContentRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12O\n" +
	"\aoptions\x18\x02 \x01(\v20.penfold.processing.content.v1.ProcessingOptionsH\x00R\aoptions\x88\x01\x01B\n" +
	"\n" +
	"\b_options\"\x99\x02\n" +
	"\x11ProcessingOptions\x12%\n" +
	"\x0eskip_embedding\x18\x01 \x01(\bR\rskipEmbedding\x12-\n" +
	"\x12skip_summarization\x18\x02 \x01(\bR\x11skipSummarization\x12'\n" +
	"\x0fskip_extraction\x18\x03 \x01(\bR\x0eskipExtraction\x12'\n" +
	"\x0fforce_reprocess\x18\x04 \x01(\bR\x0eforceReprocess\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12,\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x05H\x00R\x0etimeoutSeconds\x88\x01\x01B\x12\n" +
	"\x10_timeout_seconds\"\x97\x01\n" +
	"\x16ProcessContentResponse\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12G\n" +
	"\x06status\x18\x03 \x01(\v2/.penfold.processing.content.v1.ProcessingStatusR\x06status\"b\n" +
	"\x1aGetProcessingStatusRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x1a\n" +
	"\x06job_id\x18\x02 \x01(\tH\x00R\x05jobId\x88\x01\x01B\t\n" +
	"\a_job_id\"\x9f\x05\n" +
	"\x10ProcessingStatus\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12D\n" +
	"\x05state\x18\x03 \x01(\x0e2..penfold.processing.content.v1.ProcessingStateR\x05state\x12Y\n" +
	"\x10stages_completed\x18\x04 \x03(\x0e2..penfold.processing.content.v1.ProcessingStageR\x0fstagesCompleted\x12X\n" +
	"\rcurrent_stage\x18\x05 \x01(\x0e2..penfold.processing.content.v1.ProcessingStageH\x00R\fcurrentStage\x88\x01\x01\x12F\n" +
	"\x06errors\x18\x06 \x03(\v2..penfold.processing.content.v1.ProcessingErrorR\x06errors\x12>\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tstartedAt\x88\x01\x01\x12@\n" +
	"\vfinished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x02R\n" +
	"finishedAt\x88\x01\x01\x12$\n" +
	"\vduration_ms\x18\t \x01(\x03H\x03R\n" +
	"durationMs\x88\x01\x01\x12)\n" +
	"\x10progress_percent\x18\n" +
	" \x01(\x05R\x0fprogressPercentB\x10\n" +
	"\x0e_current_stageB\r\n" +
	"\v_started_atB\x0e\n" +
	"\f_finished_atB\x0e\n" +
	"\f_duration_ms\"\x81\x02\n" +
	"\x0fProcessingError\x12D\n" +
	"\x05stage\x18\x01 \x01(\x0e2..penfold.processing.content.v1.ProcessingStageR\x05stage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x1c\n" +
	"\tretryable\x18\x05 \x01(\bR\tretryable\x12\x1f\n" +
	"\vretry_count\x18\x06 \x01(\x05R\n" +
	"retryCount\"c\n" +
	"\x15GetContentItemRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12+\n" +
	"\x11include_embedding\x18\x02 \x01(\bR\x10includeEmbedding\"\xdf\x03\n" +
	"\x17ListContentItemsRequest\x12$\n" +
	"\vsource_type\x18\x01 \x01(\tH\x00R\n" +
	"sourceType\x88\x01\x01\x12I\n" +
	"\x05state\x18\x02 \x01(\x0e2..penfold.processing.content.v1.ProcessingStateH\x01R\x05state\x88\x01\x01\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12D\n" +
	"\rcreated_after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\fcreatedAfter\x88\x01\x01\x12F\n" +
	"\x0ecreated_before\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\rcreatedBefore\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\a \x01(\tR\tpageToken\x12-\n" +
	"\x12include_embeddings\x18\b \x01(\bR\x11includeEmbeddingsB\x0e\n" +
	"\f_source_typeB\b\n" +
	"\x06_stateB\x10\n" +
	"\x0e_created_afterB\x11\n" +
	"\x0f_created_before\"\xba\x01\n" +
	"\x18ListContentItemsResponse\x12@\n" +
	"\x05items\x18\x01 \x03(\v2*.penfold.processing.content.v1.ContentItemR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12$\n" +
	"\vtotal_count\x18\x03 \x01(\x03H\x00R\n" +
	"totalCount\x88\x01\x01B\x0e\n" +
	"\f_total_count\"\x8d\x02\n" +
	"\x17ReprocessContentRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12O\n" +
	"\aoptions\x18\x03 \x01(\v20.penfold.processing.content.v1.ProcessingOptionsH\x00R\aoptions\x88\x01\x01\x12^\n" +
	"\x13stages_to_reprocess\x18\x04 \x03(\x0e2..penfold.processing.content.v1.ProcessingStageR\x11stagesToReprocessB\n" +
	"\n" +
	"\b_options\"\xc1\x01\n" +
	"\x18ReprocessContentResponse\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12&\n" +
	"\x0fprevious_job_id\x18\x03 \x01(\tR\rpreviousJobId\x12G\n" +
	"\x06status\x18\x04 \x01(\v2/.penfold.processing.content.v1.ProcessingStatusR\x06status*\xe4\x01\n" +
	"\x0fProcessingStage\x12 \n" +
	"\x1cPROCESSING_STAGE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PROCESSING_STAGE_FETCH\x10\x01\x12\x1a\n" +
	"\x16PROCESSING_STAGE_PARSE\x10\x02\x12\x1a\n" +
	"\x16PROCESSING_STAGE_EMBED\x10\x03\x12\x1e\n" +
	"\x1aPROCESSING_STAGE_SUMMARIZE\x10\x04\x12\x1c\n" +
	"\x18PROCESSING_STAGE_EXTRACT\x10\x05\x12\x1d\n" +
	"\x19PROCESSING_STAGE_COMPLETE\x10\x06*\xd0\x01\n" +
	"\x0fProcessingState\x12 \n" +
	"\x1cPROCESSING_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PROCESSING_STATE_PENDING\x10\x01\x12 \n" +
	"\x1cPROCESSING_STATE_IN_PROGRESS\x10\x02\x12\x1e\n" +
	"\x1aPROCESSING_STATE_COMPLETED\x10\x03\x12\x1b\n" +
	"\x17PROCESSING_STATE_FAILED\x10\x04\x12\x1e\n" +
	"\x1aPROCESSING_STATE_CANCELLED\x10\x052\x9c\x05\n" +
	"\x17ContentProcessorService\x12}\n" +
	"\x0eProcessContent\x124.penfold.processing.content.v1.ProcessContentRequest\x1a5.penfold.processing.content.v1.ProcessContentResponse\x12\x81\x01\n" +
	"\x13GetProcessingStatus\x129.penfold.processing.content.v1.GetProcessingStatusRequest\x1a/.penfold.processing.content.v1.ProcessingStatus\x12r\n" +
	"\x0eGetContentItem\x124.penfold.processing.content.v1.GetContentItemRequest\x1a*.penfold.processing.content.v1.ContentItem\x12\x83\x01\n" +
	"\x10ListContentItems\x126.penfold.processing.content.v1.ListContentItemsRequest\x1a7.penfold.processing.content.v1.ListContentItemsResponse\x12\x83\x01\n" +
	"\x10ReprocessContent\x126.penfold.processing.content.v1.ReprocessContentRequest\x1a7.penfold.processing.content.v1.ReprocessContentResponseBPZNgithub.com/otherjamesbrown/penfold/api/proto/processing/v1/contentpb;contentpbb\x06proto3"

var (
	file_contentpb_content_proto_rawDescOnce sync.Once
	file_contentpb_content_proto_rawDescData []byte
)

func file_contentpb_content_proto_rawDescGZIP() []byte {
	file_contentpb_content_proto_rawDescOnce.Do(func() {
		file_contentpb_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contentpb_content_proto_rawDesc), len(file_contentpb_content_proto_rawDesc)))
	})
	return file_contentpb_content_proto_rawDescData
}

var file_contentpb_content_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_contentpb_content_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_contentpb_content_proto_goTypes = []any{
	(ProcessingStage)(0),               // 0: penfold.processing.content.v1.ProcessingStage
	(ProcessingState)(0),               // 1: penfold.processing.content.v1.ProcessingState
	(*ContentItem)(nil),                // 2: penfold.processing.content.v1.ContentItem
	(*ProcessContentRequest)(nil),      // 3: penfold.processing.content.v1.ProcessContentRequest
	(*ProcessingOptions)(nil),          // 4: penfold.processing.content.v1.ProcessingOptions
	(*ProcessContentResponse)(nil),     // 5: penfold.processing.content.v1.ProcessContentResponse
	(*GetProcessingStatusRequest)(nil), // 6: penfold.processing.content.v1.GetProcessingStatusRequest
	(*ProcessingStatus)(nil),           // 7: penfold.processing.content.v1.ProcessingStatus
	(*ProcessingError)(nil),            // 8: penfold.processing.content.v1.ProcessingError
	(*GetContentItemRequest)(nil),      // 9: penfold.processing.content.v1.GetContentItemRequest
	(*ListContentItemsRequest)(nil),    // 10: penfold.processing.content.v1.ListContentItemsRequest
	(*ListContentItemsResponse)(nil),   // 11: penfold.processing.content.v1.ListContentItemsResponse
	(*ReprocessContentRequest)(nil),    // 12: penfold.processing.content.v1.ReprocessContentRequest
	(*ReprocessContentResponse)(nil),   // 13: penfold.processing.content.v1.ReprocessContentResponse
	nil,                                // 14: penfold.processing.content.v1.ContentItem.MetadataEntry
	(*timestamppb.Timestamp)(nil),      // 15: google.protobuf.Timestamp
}
var file_contentpb_content_proto_depIdxs = []int32{
	14, // 0: penfold.processing.content.v1.ContentItem.metadata:type_name -> penfold.processing.content.v1.ContentItem.MetadataEntry
	1,  // 1: penfold.processing.content.v1.ContentItem.state:type_name -> penfold.processing.content.v1.ProcessingState
	15, // 2: penfold.processing.content.v1.ContentItem.created_at:type_name -> google.protobuf.Timestamp
	15, // 3: penfold.processing.content.v1.ContentItem.updated_at:type_name -> google.protobuf.Timestamp
	15, // 4: penfold.processing.content.v1.ContentItem.processed_at:type_name -> google.protobuf.Timestamp
	4,  // 5: penfold.processing.content.v1.ProcessContentRequest.options:type_name -> penfold.processing.content.v1.ProcessingOptions
	7,  // 6: penfold.processing.content.v1.ProcessContentResponse.status:type_name -> penfold.processing.content.v1.ProcessingStatus
	1,  // 7: penfold.processing.content.v1.ProcessingStatus.state:type_name -> penfold.processing.content.v1.ProcessingState
	0,  // 8: penfold.processing.content.v1.ProcessingStatus.stages_completed:type_name -> penfold.processing.content.v1.ProcessingStage
	0,  // 9: penfold.processing.content.v1.ProcessingStatus.current_stage:type_name -> penfold.processing.content.v1.ProcessingStage
	8,  // 10: penfold.processing.content.v1.ProcessingStatus.errors:type_name -> penfold.processing.content.v1.ProcessingError
	15, // 11: penfold.processing.content.v1.ProcessingStatus.started_at:type_name -> google.protobuf.Timestamp
	15, // 12: penfold.processing.content.v1.ProcessingStatus.finished_at:type_name -> google.protobuf.Timestamp
	0,  // 13: penfold.processing.content.v1.ProcessingError.stage:type_name -> penfold.processing.content.v1.ProcessingStage
	15, // 14: penfold.processing.content.v1.ProcessingError.occurred_at:type_name -> google.protobuf.Timestamp
	1,  // 15: penfold.processing.content.v1.ListContentItemsRequest.state:type_name -> penfold.processing.content.v1.ProcessingState
	15, // 16: penfold.processing.content.v1.ListContentItemsRequest.created_after:type_name -> google.protobuf.Timestamp
	15, // 17: penfold.processing.content.v1.ListContentItemsRequest.created_before:type_name -> google.protobuf.Timestamp
	2,  // 18: penfold.processing.content.v1.ListContentItemsResponse.items:type_name -> penfold.processing.content.v1.ContentItem
	4,  // 19: penfold.processing.content.v1.ReprocessContentRequest.options:type_name -> penfold.processing.content.v1.ProcessingOptions
	0,  // 20: penfold.processing.content.v1.ReprocessContentRequest.stages_to_reprocess:type_name -> penfold.processing.content.v1.ProcessingStage
	7,  // 21: penfold.processing.content.v1.ReprocessContentResponse.status:type_name -> penfold.processing.content.v1.ProcessingStatus
	3,  // 22: penfold.processing.content.v1.ContentProcessorService.ProcessContent:input_type -> penfold.processing.content.v1.ProcessContentRequest
	6,  // 23: penfold.processing.content.v1.ContentProcessorService.GetProcessingStatus:input_type -> penfold.processing.content.v1.GetProcessingStatusRequest
	9,  // 24: penfold.processing.content.v1.ContentProcessorService.GetContentItem:input_type -> penfold.processing.content.v1.GetContentItemRequest
	10, // 25: penfold.processing.content.v1.ContentProcessorService.ListContentItems:input_type -> penfold.processing.content.v1.ListContentItemsRequest
	12, // 26: penfold.processing.content.v1.ContentProcessorService.ReprocessContent:input_type -> penfold.processing.content.v1.ReprocessContentRequest
	5,  // 27: penfold.processing.content.v1.ContentProcessorService.ProcessContent:output_type -> penfold.processing.content.v1.ProcessContentResponse
	7,  // 28: penfold.processing.content.v1.ContentProcessorService.GetProcessingStatus:output_type -> penfold.processing.content.v1.ProcessingStatus
	2,  // 29: penfold.processing.content.v1.ContentProcessorService.GetContentItem:output_type -> penfold.processing.content.v1.ContentItem
	11, // 30: penfold.processing.content.v1.ContentProcessorService.ListContentItems:output_type -> penfold.processing.content.v1.ListContentItemsResponse
	13, // 31: penfold.processing.content.v1.ContentProcessorService.ReprocessContent:output_type -> penfold.processing.content.v1.ReprocessContentResponse
	27, // [27:32] is the sub-list for method output_type
	22, // [22:27] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_contentpb_content_proto_init() }
func file_contentpb_content_proto_init() {
	if File_contentpb_content_proto != nil {
		return
	}
	file_contentpb_content_proto_msgTypes[0].OneofWrappers = []any{}
	file_contentpb_content_proto_msgTypes[1].OneofWrappers = []any{}
	file_contentpb_content_proto_msgTypes[2].OneofWrappers = []any{}
	file_contentpb_content_proto_msgTypes[4].OneofWrappers = []any{}
	file_contentpb_content_proto_msgTypes[5].OneofWrappers = []any{}
	file_contentpb_content_proto_msgTypes[8].OneofWrappers = []any{}
	file_contentpb_content_proto_msgTypes[9].OneofWrappers = []any{}
	file_contentpb_content_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contentpb_content_proto_rawDesc), len(file_contentpb_content_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contentpb_content_proto_goTypes,
		DependencyIndexes: file_contentpb_content_proto_depIdxs,
		EnumInfos:         file_contentpb_content_proto_enumTypes,
		MessageInfos:      file_contentpb_content_proto_msgTypes,
	}.Build()
	File_contentpb_content_proto = out.File
	file_contentpb_content_proto_goTypes = nil
	file_contentpb_content_proto_depIdxs = nil
}
