// Product Service Protobuf Definitions
// Provides gRPC service for product management with hierarchy and aliases

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: product/v1/product.proto

package productv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductService_CreateProduct_FullMethodName      = "/penfold.product.v1.ProductService/CreateProduct"
	ProductService_GetProduct_FullMethodName         = "/penfold.product.v1.ProductService/GetProduct"
	ProductService_UpdateProduct_FullMethodName      = "/penfold.product.v1.ProductService/UpdateProduct"
	ProductService_DeleteProduct_FullMethodName      = "/penfold.product.v1.ProductService/DeleteProduct"
	ProductService_ListProducts_FullMethodName       = "/penfold.product.v1.ProductService/ListProducts"
	ProductService_GetHierarchy_FullMethodName       = "/penfold.product.v1.ProductService/GetHierarchy"
	ProductService_AddAlias_FullMethodName           = "/penfold.product.v1.ProductService/AddAlias"
	ProductService_RemoveAlias_FullMethodName        = "/penfold.product.v1.ProductService/RemoveAlias"
	ProductService_ListAliases_FullMethodName        = "/penfold.product.v1.ProductService/ListAliases"
	ProductService_ListProductEvents_FullMethodName  = "/penfold.product.v1.ProductService/ListProductEvents"
	ProductService_CreateProductEvent_FullMethodName = "/penfold.product.v1.ProductService/CreateProductEvent"
	ProductService_GetProductEvent_FullMethodName    = "/penfold.product.v1.ProductService/GetProductEvent"
	ProductService_DeleteProductEvent_FullMethodName = "/penfold.product.v1.ProductService/DeleteProductEvent"
	ProductService_LinkProductEvent_FullMethodName   = "/penfold.product.v1.ProductService/LinkProductEvent"
	ProductService_GetEventContext_FullMethodName    = "/penfold.product.v1.ProductService/GetEventContext"
)

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProductService provides gRPC endpoints for product management.
type ProductServiceClient interface {
	// CreateProduct creates a new product.
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error)
	// GetProduct retrieves a product by ID or name/alias.
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
	// UpdateProduct updates an existing product.
	UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error)
	// DeleteProduct deletes a product by ID.
	DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error)
	// ListProducts lists products with optional filtering.
	ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error)
	// GetHierarchy retrieves the product hierarchy tree.
	GetHierarchy(ctx context.Context, in *GetHierarchyRequest, opts ...grpc.CallOption) (*GetHierarchyResponse, error)
	// AddAlias adds an alias to a product.
	AddAlias(ctx context.Context, in *AddAliasRequest, opts ...grpc.CallOption) (*AliasResponse, error)
	// RemoveAlias removes an alias from a product.
	RemoveAlias(ctx context.Context, in *RemoveAliasRequest, opts ...grpc.CallOption) (*AliasResponse, error)
	// ListAliases lists all aliases for a product.
	ListAliases(ctx context.Context, in *ListAliasesRequest, opts ...grpc.CallOption) (*ListAliasesResponse, error)
	// Timeline/Event management
	// ListProductEvents lists events for a product with optional filtering.
	ListProductEvents(ctx context.Context, in *ListProductEventsRequest, opts ...grpc.CallOption) (*ListProductEventsResponse, error)
	// CreateProductEvent creates a new timeline event for a product.
	CreateProductEvent(ctx context.Context, in *CreateProductEventRequest, opts ...grpc.CallOption) (*CreateProductEventResponse, error)
	// GetProductEvent retrieves a specific event by ID.
	GetProductEvent(ctx context.Context, in *GetProductEventRequest, opts ...grpc.CallOption) (*GetProductEventResponse, error)
	// DeleteProductEvent deletes an event by ID.
	DeleteProductEvent(ctx context.Context, in *DeleteProductEventRequest, opts ...grpc.CallOption) (*DeleteProductEventResponse, error)
	// LinkProductEvent links an event to another entity.
	LinkProductEvent(ctx context.Context, in *LinkProductEventRequest, opts ...grpc.CallOption) (*LinkProductEventResponse, error)
	// GetEventContext retrieves events around a specific point in time.
	GetEventContext(ctx context.Context, in *GetEventContextRequest, opts ...grpc.CallOption) (*GetEventContextResponse, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductResponse)
	err := c.cc.Invoke(ctx, ProductService_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductResponse)
	err := c.cc.Invoke(ctx, ProductService_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProductResponse)
	err := c.cc.Invoke(ctx, ProductService_UpdateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProductResponse)
	err := c.cc.Invoke(ctx, ProductService_DeleteProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductsResponse)
	err := c.cc.Invoke(ctx, ProductService_ListProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetHierarchy(ctx context.Context, in *GetHierarchyRequest, opts ...grpc.CallOption) (*GetHierarchyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHierarchyResponse)
	err := c.cc.Invoke(ctx, ProductService_GetHierarchy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) AddAlias(ctx context.Context, in *AddAliasRequest, opts ...grpc.CallOption) (*AliasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AliasResponse)
	err := c.cc.Invoke(ctx, ProductService_AddAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) RemoveAlias(ctx context.Context, in *RemoveAliasRequest, opts ...grpc.CallOption) (*AliasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AliasResponse)
	err := c.cc.Invoke(ctx, ProductService_RemoveAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListAliases(ctx context.Context, in *ListAliasesRequest, opts ...grpc.CallOption) (*ListAliasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAliasesResponse)
	err := c.cc.Invoke(ctx, ProductService_ListAliases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListProductEvents(ctx context.Context, in *ListProductEventsRequest, opts ...grpc.CallOption) (*ListProductEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductEventsResponse)
	err := c.cc.Invoke(ctx, ProductService_ListProductEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateProductEvent(ctx context.Context, in *CreateProductEventRequest, opts ...grpc.CallOption) (*CreateProductEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductEventResponse)
	err := c.cc.Invoke(ctx, ProductService_CreateProductEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProductEvent(ctx context.Context, in *GetProductEventRequest, opts ...grpc.CallOption) (*GetProductEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductEventResponse)
	err := c.cc.Invoke(ctx, ProductService_GetProductEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteProductEvent(ctx context.Context, in *DeleteProductEventRequest, opts ...grpc.CallOption) (*DeleteProductEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProductEventResponse)
	err := c.cc.Invoke(ctx, ProductService_DeleteProductEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) LinkProductEvent(ctx context.Context, in *LinkProductEventRequest, opts ...grpc.CallOption) (*LinkProductEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkProductEventResponse)
	err := c.cc.Invoke(ctx, ProductService_LinkProductEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetEventContext(ctx context.Context, in *GetEventContextRequest, opts ...grpc.CallOption) (*GetEventContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventContextResponse)
	err := c.cc.Invoke(ctx, ProductService_GetEventContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
// All implementations must embed UnimplementedProductServiceServer
// for forward compatibility.
//
// ProductService provides gRPC endpoints for product management.
type ProductServiceServer interface {
	// CreateProduct creates a new product.
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error)
	// GetProduct retrieves a product by ID or name/alias.
	GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error)
	// UpdateProduct updates an existing product.
	UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error)
	// DeleteProduct deletes a product by ID.
	DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductResponse, error)
	// ListProducts lists products with optional filtering.
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error)
	// GetHierarchy retrieves the product hierarchy tree.
	GetHierarchy(context.Context, *GetHierarchyRequest) (*GetHierarchyResponse, error)
	// AddAlias adds an alias to a product.
	AddAlias(context.Context, *AddAliasRequest) (*AliasResponse, error)
	// RemoveAlias removes an alias from a product.
	RemoveAlias(context.Context, *RemoveAliasRequest) (*AliasResponse, error)
	// ListAliases lists all aliases for a product.
	ListAliases(context.Context, *ListAliasesRequest) (*ListAliasesResponse, error)
	// Timeline/Event management
	// ListProductEvents lists events for a product with optional filtering.
	ListProductEvents(context.Context, *ListProductEventsRequest) (*ListProductEventsResponse, error)
	// CreateProductEvent creates a new timeline event for a product.
	CreateProductEvent(context.Context, *CreateProductEventRequest) (*CreateProductEventResponse, error)
	// GetProductEvent retrieves a specific event by ID.
	GetProductEvent(context.Context, *GetProductEventRequest) (*GetProductEventResponse, error)
	// DeleteProductEvent deletes an event by ID.
	DeleteProductEvent(context.Context, *DeleteProductEventRequest) (*DeleteProductEventResponse, error)
	// LinkProductEvent links an event to another entity.
	LinkProductEvent(context.Context, *LinkProductEventRequest) (*LinkProductEventResponse, error)
	// GetEventContext retrieves events around a specific point in time.
	GetEventContext(context.Context, *GetEventContextRequest) (*GetEventContextResponse, error)
	mustEmbedUnimplementedProductServiceServer()
}

// UnimplementedProductServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductServiceServer struct{}

func (UnimplementedProductServiceServer) CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedProductServiceServer) GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedProductServiceServer) UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (UnimplementedProductServiceServer) DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (UnimplementedProductServiceServer) ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedProductServiceServer) GetHierarchy(context.Context, *GetHierarchyRequest) (*GetHierarchyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHierarchy not implemented")
}
func (UnimplementedProductServiceServer) AddAlias(context.Context, *AddAliasRequest) (*AliasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAlias not implemented")
}
func (UnimplementedProductServiceServer) RemoveAlias(context.Context, *RemoveAliasRequest) (*AliasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveAlias not implemented")
}
func (UnimplementedProductServiceServer) ListAliases(context.Context, *ListAliasesRequest) (*ListAliasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAliases not implemented")
}
func (UnimplementedProductServiceServer) ListProductEvents(context.Context, *ListProductEventsRequest) (*ListProductEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProductEvents not implemented")
}
func (UnimplementedProductServiceServer) CreateProductEvent(context.Context, *CreateProductEventRequest) (*CreateProductEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProductEvent not implemented")
}
func (UnimplementedProductServiceServer) GetProductEvent(context.Context, *GetProductEventRequest) (*GetProductEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductEvent not implemented")
}
func (UnimplementedProductServiceServer) DeleteProductEvent(context.Context, *DeleteProductEventRequest) (*DeleteProductEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProductEvent not implemented")
}
func (UnimplementedProductServiceServer) LinkProductEvent(context.Context, *LinkProductEventRequest) (*LinkProductEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinkProductEvent not implemented")
}
func (UnimplementedProductServiceServer) GetEventContext(context.Context, *GetEventContextRequest) (*GetEventContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventContext not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}
func (UnimplementedProductServiceServer) testEmbeddedByValue()                        {}

// UnsafeProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServiceServer will
// result in compilation errors.
type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	// If the following call pancis, it indicates UnimplementedProductServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_UpdateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateProduct(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_DeleteProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteProduct(ctx, req.(*DeleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_ListProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListProducts(ctx, req.(*ListProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetHierarchy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHierarchyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetHierarchy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetHierarchy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetHierarchy(ctx, req.(*GetHierarchyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_AddAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).AddAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_AddAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).AddAlias(ctx, req.(*AddAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_RemoveAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).RemoveAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_RemoveAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).RemoveAlias(ctx, req.(*RemoveAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListAliases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAliasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListAliases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_ListAliases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListAliases(ctx, req.(*ListAliasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListProductEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListProductEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_ListProductEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListProductEvents(ctx, req.(*ListProductEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateProductEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateProductEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_CreateProductEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateProductEvent(ctx, req.(*CreateProductEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProductEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetProductEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductEvent(ctx, req.(*GetProductEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteProductEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteProductEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_DeleteProductEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteProductEvent(ctx, req.(*DeleteProductEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_LinkProductEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkProductEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).LinkProductEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_LinkProductEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).LinkProductEvent(ctx, req.(*LinkProductEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetEventContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetEventContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetEventContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetEventContext(ctx, req.(*GetEventContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductService_ServiceDesc is the grpc.ServiceDesc for ProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "penfold.product.v1.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProduct",
			Handler:    _ProductService_CreateProduct_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _ProductService_GetProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _ProductService_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _ProductService_DeleteProduct_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _ProductService_ListProducts_Handler,
		},
		{
			MethodName: "GetHierarchy",
			Handler:    _ProductService_GetHierarchy_Handler,
		},
		{
			MethodName: "AddAlias",
			Handler:    _ProductService_AddAlias_Handler,
		},
		{
			MethodName: "RemoveAlias",
			Handler:    _ProductService_RemoveAlias_Handler,
		},
		{
			MethodName: "ListAliases",
			Handler:    _ProductService_ListAliases_Handler,
		},
		{
			MethodName: "ListProductEvents",
			Handler:    _ProductService_ListProductEvents_Handler,
		},
		{
			MethodName: "CreateProductEvent",
			Handler:    _ProductService_CreateProductEvent_Handler,
		},
		{
			MethodName: "GetProductEvent",
			Handler:    _ProductService_GetProductEvent_Handler,
		},
		{
			MethodName: "DeleteProductEvent",
			Handler:    _ProductService_DeleteProductEvent_Handler,
		},
		{
			MethodName: "LinkProductEvent",
			Handler:    _ProductService_LinkProductEvent_Handler,
		},
		{
			MethodName: "GetEventContext",
			Handler:    _ProductService_GetEventContext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product/v1/product.proto",
}
