// Package server provides a reproduction test for bug pf-9b868f.
//
// Bug: Worker stage spans (stage.triage, stage.extract_entities, etc.) are not
// reaching Langfuse. The workflow generates phantom stage span IDs via
// workflow.SideEffect (random hex strings) and passes them as PipelineSpanID to
// activities. The AI coordinator installs these as remote parent SpanIDs, but no
// actual OTel spans with those IDs are ever created or exported.
//
// Expected: When TriageContent (or any AI coordinator RPC) is called, the exported
// spans should include BOTH:
//   - A "stage.triage" span (the stage wrapper)
//   - An "ai.triage" span (the AI generation) as a child of stage.triage
//
// Currently FAILING because no stage.X spans are created anywhere.
package server

import (
	"context"
	"testing"
	"time"

	"go.opentelemetry.io/otel"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	"go.opentelemetry.io/otel/sdk/trace/tracetest"
	"go.opentelemetry.io/otel/trace"

	aiv1 "github.com/otherjamesbrown/penfold/api/proto/ai/v1"
	"github.com/otherjamesbrown/penfold/pkg/tracing"
	"github.com/otherjamesbrown/penfold/services/ai/backend"
)

// setupStageSpanTestTracer creates a test OTel tracer with an in-memory exporter,
// replacing both the global provider and the AITracer package var so all spans
// (pipeline, stage, and ai) are captured.
func setupStageSpanTestTracer(t *testing.T) (*tracetest.InMemoryExporter, func()) {
	t.Helper()

	exporter := tracetest.NewInMemoryExporter()
	tp := sdktrace.NewTracerProvider(
		sdktrace.WithSyncer(exporter),
		sdktrace.WithSampler(sdktrace.AlwaysSample()),
	)

	oldProvider := otel.GetTracerProvider()
	otel.SetTracerProvider(tp)

	// Rebind the AITracer package-level var so it uses the test provider.
	oldAITracer := tracing.AITracer
	tracing.AITracer = otel.Tracer("penfold.ai")

	return exporter, func() {
		_ = tp.Shutdown(context.Background())
		otel.SetTracerProvider(oldProvider)
		tracing.AITracer = oldAITracer
	}
}

// TestTriageContent_StageSpanCreated_BugReproduction is the primary reproduction test
// for pf-9b868f.
//
// The fix requires the AI coordinator (or the worker stage code) to create a real
// OTel stage.X span that wraps each ai.X generation span. Currently no stage spans
// exist, so this test FAILS.
//
// After the fix the test should pass with:
//   - 2 exported spans: "stage.triage" + "ai.triage"
//   - "ai.triage" parent span ID == "stage.triage" span ID
//   - Both spans share the same trace ID
func TestTriageContent_StageSpanCreated_BugReproduction(t *testing.T) {
	exporter, cleanup := setupStageSpanTestTracer(t)
	defer cleanup()

	// Build a mock backend that returns a valid triage response.
	be := &mockBackend{
		chatCompletionFunc: func(ctx context.Context, messages []backend.Message, opts backend.CompletionOptions) (*backend.CompletionResult, error) {
			return &backend.CompletionResult{
				Content:      `{"category": "PROJECT_UPDATE", "importance": "HIGH", "reason": "test"}`,
				Model:        "test-model",
				InputTokens:  10,
				OutputTokens: 5,
			}, nil
		},
	}
	server := newTestServer(be)

	// Simulate what the workflow sends: a real pipeline TraceID + a phantom stage SpanID.
	// The phantom span ID is a random 16-char hex string generated by workflow.SideEffect
	// (see services/worker/workflows/pipeline.go lines 872-878). It is NOT a real OTel span.
	pipelineTraceID := "aabbccddeeff00112233445566778899"
	phantomStageSpanID := "deadbeef12345678" // random bytes, no real OTel span behind this

	req := &aiv1.TriageContentRequest{
		Content:         "Discuss the sprint planning meeting and upcoming milestones.",
		Subject:         stringPtr("Sprint Planning"),
		Sender:          stringPtr("alice@example.com"),
		TenantId:        stringPtr("tenant-1"),
		ContentId:       stringPtr("em-abc12XYZ"),
		PipelineTraceId: stringPtr(pipelineTraceID),
		PipelineSpanId:  stringPtr(phantomStageSpanID),
	}

	_, err := server.TriageContent(context.Background(), req)
	if err != nil {
		t.Fatalf("TriageContent returned unexpected error: %v", err)
	}

	spans := exporter.GetSpans()

	// -------------------------------------------------------------------
	// ASSERTION 1: There should be exactly 2 spans:
	//   - "stage.triage" (the stage wrapper span)
	//   - "ai.triage" (the AI generation span)
	//
	// Currently FAILS because TriageContent only creates 1 span ("ai.triage").
	// No "stage.triage" span is ever created anywhere.
	// -------------------------------------------------------------------
	if len(spans) != 2 {
		t.Errorf("BUG pf-9b868f: expected 2 spans (stage.triage + ai.triage), got %d span(s): %v",
			len(spans), spanNames(spans))
		t.Log("Fix: The AI coordinator (or the worker) must create a real stage.X OTel span")
		t.Log("that wraps the ai.X generation span. The phantom span IDs generated by")
		t.Log("workflow.SideEffect are random hex strings with no OTel span behind them.")
		// Continue checking what we did get so the failure is informative.
	}

	// Find the stage and ai spans by name.
	var stageSpan, aiSpan *tracetest.SpanStub
	for i := range spans {
		s := &spans[i]
		switch s.Name {
		case "stage.triage":
			stageSpan = s
		case "ai.triage":
			aiSpan = s
		}
	}

	// -------------------------------------------------------------------
	// ASSERTION 2: "stage.triage" span must exist.
	//
	// Currently FAILS: no stage.triage span is created.
	// -------------------------------------------------------------------
	if stageSpan == nil {
		t.Error("BUG pf-9b868f: no 'stage.triage' span found in exported spans")
		t.Logf("Exported spans: %v", spanNames(spans))
	}

	// -------------------------------------------------------------------
	// ASSERTION 3: "ai.triage" span must exist.
	// (This is the span that TriageContent already creates — it should pass.)
	// -------------------------------------------------------------------
	if aiSpan == nil {
		t.Error("'ai.triage' span not found in exported spans (unexpected — should exist)")
		t.Logf("Exported spans: %v", spanNames(spans))
	}

	// -------------------------------------------------------------------
	// ASSERTION 4: Both spans share the same trace ID.
	//
	// Currently FAILS for stage.triage (doesn't exist), but the ai.triage span
	// should have the correct trace ID because applyPipelineTrace parses pipelineTraceID.
	// -------------------------------------------------------------------
	if stageSpan != nil {
		stageTraceID := stageSpan.SpanContext.TraceID().String()
		if stageTraceID != pipelineTraceID {
			t.Errorf("stage.triage trace ID = %s, want %s", stageTraceID, pipelineTraceID)
		}
	}
	if aiSpan != nil {
		aiTraceID := aiSpan.SpanContext.TraceID().String()
		if aiTraceID != pipelineTraceID {
			t.Errorf("ai.triage trace ID = %s, want %s", aiTraceID, pipelineTraceID)
		}
	}

	// -------------------------------------------------------------------
	// ASSERTION 5: "ai.triage" must be a child of "stage.triage" (not the
	// phantom stage span ID).
	//
	// Currently FAILS in two ways:
	//   a) stage.triage doesn't exist, so there's no valid parent
	//   b) ai.triage's parent is set to the phantom span ID (deadbeef12345678)
	//      which has no corresponding OTel span — it's an orphaned remote ref
	// -------------------------------------------------------------------
	if stageSpan != nil && aiSpan != nil {
		stageSpanID := stageSpan.SpanContext.SpanID()
		aiParentSpanID := aiSpan.Parent.SpanID()

		if aiParentSpanID != stageSpanID {
			t.Errorf("ai.triage parent span ID = %s, want stage.triage span ID %s",
				aiParentSpanID.String(), stageSpanID.String())
			t.Log("The ai.triage span should be a child of the real stage.triage span,")
			t.Log("not of the phantom span ID generated by workflow.SideEffect.")
		}
	}

	// Show informative output about what the bug causes.
	if aiSpan != nil && stageSpan == nil {
		t.Logf("BUG SYMPTOM: ai.triage has parent span ID %s (phantom, no real span)",
			aiSpan.Parent.SpanID().String())
		t.Logf("  pipelineTraceID = %s", pipelineTraceID)
		t.Logf("  phantomStageSpanID = %s", phantomStageSpanID)
		t.Logf("  ai.triage.parent = %s", aiSpan.Parent.SpanID().String())
		t.Logf("In Langfuse, ai.triage will reference a parent observation ID that doesn't exist.")
	}
}

// TestStartPipelineTracing_ZeroDurationSpan_BugReproduction reproduces the
// second aspect of bug pf-9b868f: the slm-pipeline span has zero duration
// because StartPipelineTracing uses `defer span.End()` (line 171 of
// pipeline_activities.go). The span ends the moment the activity returns,
// capturing none of the pipeline's actual work.
//
// This test verifies that the pipeline span duration is non-trivially short,
// and documents that the current implementation ends the span immediately
// (giving it zero duration relative to the pipeline's real work time).
//
// Currently FAILS: the span duration is ~0ms because span.End() is deferred
// and fires when the activity goroutine returns, not when the pipeline finishes.
func TestStartPipelineTracing_ZeroDurationSpan_BugReproduction(t *testing.T) {
	exporter, cleanup := setupStageSpanTestTracer(t)
	defer cleanup()

	// We import the activities package indirectly through the tracing package
	// to test the span lifetime. The pipeline span is created inside
	// StartPipelineTracing activity with `defer span.End()`, which ends the
	// span as soon as the activity function returns.
	//
	// The correct fix is to NOT use defer span.End() in the activity, and
	// instead return the span (or a cancellation function) so the workflow
	// can end it when the pipeline completes.
	//
	// Here we directly test the tracing.StartPipeline API to show that if a
	// span is ended immediately (simulating defer span.End()), its duration
	// is effectively zero compared to the actual pipeline duration.

	contentID := "em-abc12XYZ"
	contentType := "email"
	pipelineTraceID := "1122334455667788aabbccddeeff0011"

	// Simulate what StartPipelineTracing activity does: create span then
	// immediately end it (defer fires on return).
	simulateActivityBehavior := func() (startTime, endTime time.Time) {
		ctx := context.Background()
		_, span := tracing.StartPipeline(ctx, "slm-pipeline", contentID, contentType, pipelineTraceID)
		startTime = time.Now()
		// Activity returns here — defer span.End() fires immediately.
		defer span.End()
		endTime = time.Now()
		return startTime, endTime
	}

	start, end := simulateActivityBehavior()

	// Give the exporter a moment to flush (it's synchronous, but just in case).
	time.Sleep(1 * time.Millisecond)

	spans := exporter.GetSpans()
	if len(spans) != 1 {
		t.Fatalf("expected 1 span (slm-pipeline), got %d", len(spans))
	}

	pipelineSpan := spans[0]

	if pipelineSpan.Name != "slm-pipeline" {
		t.Errorf("expected span name 'slm-pipeline', got %q", pipelineSpan.Name)
	}

	// The span duration as captured by OTel
	spanDuration := pipelineSpan.EndTime.Sub(pipelineSpan.StartTime)

	// Simulated pipeline work duration (what should happen: span lives as long
	// as the actual pipeline, not just the activity execution time).
	// For the test we use the actual end-start gap as a proxy.
	simulatedPipelineDuration := end.Sub(start)

	t.Logf("OTel span duration: %v", spanDuration)
	t.Logf("Activity goroutine duration: %v", simulatedPipelineDuration)

	// The bug: the span is ended inside the activity when it returns,
	// not when the pipeline workflow completes. The span has a valid start/end
	// time but represents only the activity's return time, not the full
	// pipeline duration.
	//
	// Assert that the span duration is < 1ms (proving it's effectively zero
	// — it ends immediately when the activity returns).
	//
	// This documents the bug: in production, the pipeline takes seconds but
	// the slm-pipeline span records near-zero duration.
	if spanDuration >= 100*time.Millisecond {
		// Unexpectedly long — this would mean the span actually lives long enough.
		// This is the DESIRED behavior after the fix. If this assertion fails it
		// means the test environment somehow makes the span long (unlikely in unit tests).
		t.Logf("NOTE: span duration %v is >= 100ms — this is the desired fixed behavior", spanDuration)
	} else {
		// The span ends almost immediately — this is the BUG.
		t.Logf("BUG pf-9b868f: slm-pipeline span duration is %v (near-zero)", spanDuration)
		t.Log("The span ends when StartPipelineTracing activity returns (defer span.End()),")
		t.Log("not when the pipeline workflow completes. In Langfuse this appears as a")
		t.Log("zero-duration root observation with no child observations under it.")
	}

	// The actual assertion that documents the bug symptom:
	// The slm-pipeline span must NOT end before the pipeline does real work.
	// The fix requires the span to outlive the activity that creates it.
	//
	// We enforce: the span duration must be >= 1ms to be considered meaningful.
	// A zero-duration span (< 1ms) proves the `defer span.End()` bug is present.
	//
	// NOTE: In unit tests the span will always be near-zero because we have no
	// real pipeline work. This assertion is deliberately set to a threshold that
	// the current `defer span.End()` implementation cannot satisfy, proving that
	// the implementation approach (ending span in activity) is fundamentally wrong.
	// The fix must change the architecture so the span is NOT ended in the activity.
	const minExpectedDuration = 1 * time.Millisecond
	if spanDuration < minExpectedDuration {
		t.Errorf("BUG pf-9b868f: slm-pipeline span duration %v is less than %v — "+
			"the span ends when StartPipelineTracing activity returns (defer span.End()), "+
			"not when the pipeline workflow completes. "+
			"Fix: do not use defer span.End() in the activity; the span must outlive the activity.",
			spanDuration, minExpectedDuration)
	}

	t.Logf("EXPECTED after fix: span duration should cover the full pipeline execution time (>= %v)", minExpectedDuration)
	t.Logf("CURRENT (buggy): span duration = %v (activity return time, not pipeline time)", spanDuration)
}

// TestTriageContent_PhantomSpanIDNotInExportedSpans verifies that the phantom
// stage span ID passed as PipelineSpanID is not present as a real span in the
// OTel export. This proves the phantom ID has no backing span.
//
// This test directly captures the "orphaned parent" symptom: the ai.triage span
// references a parent span ID (the phantom) that doesn't appear in the exported spans.
func TestTriageContent_PhantomSpanIDNotInExportedSpans(t *testing.T) {
	exporter, cleanup := setupStageSpanTestTracer(t)
	defer cleanup()

	be := &mockBackend{
		chatCompletionFunc: func(ctx context.Context, messages []backend.Message, opts backend.CompletionOptions) (*backend.CompletionResult, error) {
			return &backend.CompletionResult{
				Content:     `{"category": "CUSTOMER", "importance": "MEDIUM", "reason": "test"}`,
				Model:       "test-model",
				InputTokens: 5, OutputTokens: 3,
			}, nil
		},
	}
	server := newTestServer(be)

	// This phantom span ID simulates what workflow.SideEffect generates:
	// 8 random bytes encoded as hex. There is no OTel span with this ID.
	phantomStageSpanID := "cafebabe01234567"
	pipelineTraceID := "fedcba9876543210fedcba9876543210"

	req := &aiv1.TriageContentRequest{
		Content:         "Customer asking about product pricing and availability.",
		Subject:         stringPtr("Pricing question"),
		TenantId:        stringPtr("tenant-2"),
		ContentId:       stringPtr("em-xyz98ABC"),
		PipelineTraceId: stringPtr(pipelineTraceID),
		PipelineSpanId:  stringPtr(phantomStageSpanID),
	}

	_, err := server.TriageContent(context.Background(), req)
	if err != nil {
		t.Fatalf("TriageContent returned unexpected error: %v", err)
	}

	spans := exporter.GetSpans()

	// Collect all real span IDs from the export.
	realSpanIDs := make(map[string]bool)
	for _, s := range spans {
		realSpanIDs[s.SpanContext.SpanID().String()] = true
	}

	// The phantom span ID must NOT appear in the real span IDs.
	// (This is expected to pass — it confirms the phantom has no backing span.)
	if realSpanIDs[phantomStageSpanID] {
		t.Errorf("phantom span ID %s unexpectedly found as a real span", phantomStageSpanID)
	} else {
		t.Logf("Confirmed: phantom span ID %s has no backing OTel span", phantomStageSpanID)
	}

	// Find the ai.triage span and check its parent.
	var aiSpan *tracetest.SpanStub
	for i := range spans {
		if spans[i].Name == "ai.triage" {
			aiSpan = &spans[i]
			break
		}
	}

	if aiSpan == nil {
		t.Fatal("ai.triage span not found in exports")
	}

	aiParentSpanID := aiSpan.Parent.SpanID().String()

	// The ai.triage span's parent span ID is the phantom ID.
	// This means Langfuse will try to look up an observation with ID
	// phantomStageSpanID and find nothing — the orphaned parent problem.
	if aiParentSpanID == phantomStageSpanID {
		t.Logf("BUG pf-9b868f CONFIRMED: ai.triage parent span ID = %s (phantom, no backing span)",
			aiParentSpanID)
		t.Error("ai.triage's parent span ID is the phantom stage span ID — " +
			"this ID has no corresponding OTel span in the export, causing orphaned " +
			"observations in Langfuse")
	} else if aiParentSpanID == "0000000000000000" || !aiSpan.Parent.IsValid() {
		t.Logf("ai.triage has no valid parent (parent span ID: %s)", aiParentSpanID)
		t.Log("This also indicates the phantom span ID was not installed as parent")
	} else {
		t.Logf("ai.triage parent span ID = %s", aiParentSpanID)
		// If the parent is neither phantom nor zero, it might be a real stage span.
		if realSpanIDs[aiParentSpanID] {
			t.Logf("Parent %s is a real span — this would be the FIXED behavior", aiParentSpanID)
		} else {
			t.Errorf("ai.triage has an unrecognized parent span ID %s (not a real span, not phantom)",
				aiParentSpanID)
		}
	}
}

// spanNames returns the names of all spans for use in diagnostic messages.
func spanNames(spans tracetest.SpanStubs) []string {
	names := make([]string, len(spans))
	for i, s := range spans {
		names[i] = s.Name
	}
	return names
}

// Ensure trace.SpanID type is used (avoids unused import).
var _ = trace.SpanID{}
