// Package server provides tests for stage span behavior.
//
// After fix pf-1b4929: Stage spans are created by WORKER ACTIVITIES (pf-e6f1d3),
// NOT by ai-coordinator handlers. The ai-coordinator handlers only create ai.X
// generation spans (ai.triage, ai.extract, etc.). The worker provides the stage
// span via PipelineSpanID, and applyPipelineTrace parents the ai.X span correctly.
//
// Expected: When TriageContent (or any AI coordinator RPC) is called, the handler
// should create ONLY the ai.X generation span, NOT the stage.X wrapper span.
package server

import (
	"context"
	"testing"
	"time"

	"go.opentelemetry.io/otel"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	"go.opentelemetry.io/otel/sdk/trace/tracetest"
	"go.opentelemetry.io/otel/trace"

	aiv1 "github.com/otherjamesbrown/penfold/api/proto/ai/v1"
	"github.com/otherjamesbrown/penfold/pkg/tracing"
	"github.com/otherjamesbrown/penfold/services/ai/backend"
)

// setupStageSpanTestTracer creates a test OTel tracer with an in-memory exporter,
// replacing both the global provider and the AITracer package var so all spans
// (pipeline, stage, and ai) are captured.
func setupStageSpanTestTracer(t *testing.T) (*tracetest.InMemoryExporter, func()) {
	t.Helper()

	exporter := tracetest.NewInMemoryExporter()
	tp := sdktrace.NewTracerProvider(
		sdktrace.WithSyncer(exporter),
		sdktrace.WithSampler(sdktrace.AlwaysSample()),
	)

	oldProvider := otel.GetTracerProvider()
	otel.SetTracerProvider(tp)

	// Rebind the AITracer package-level var so it uses the test provider.
	oldAITracer := tracing.AITracer
	tracing.AITracer = otel.Tracer("penfold.ai")

	return exporter, func() {
		_ = tp.Shutdown(context.Background())
		otel.SetTracerProvider(oldProvider)
		tracing.AITracer = oldAITracer
	}
}

// TestTriageContent_NoStageSpanFromHandler verifies that after fix pf-1b4929,
// ai-coordinator handlers do NOT create stage.X spans. Only ai.X spans are created.
//
// The worker activities (fixed in pf-e6f1d3) create stage.X spans. The ai-coordinator
// handlers create only ai.X spans, which are parented via applyPipelineTrace logic.
//
// Expected after fix:
//   - 1 exported span: "ai.triage" (no "stage.triage" from the handler)
//   - The ai.triage span's parent/trace are set via applyPipelineTrace
func TestTriageContent_NoStageSpanFromHandler(t *testing.T) {
	exporter, cleanup := setupStageSpanTestTracer(t)
	defer cleanup()

	// Build a mock backend that returns a valid triage response.
	be := &mockBackend{
		chatCompletionFunc: func(ctx context.Context, messages []backend.Message, opts backend.CompletionOptions) (*backend.CompletionResult, error) {
			return &backend.CompletionResult{
				Content:      `{"category": "PROJECT_UPDATE", "importance": "HIGH", "reason": "test"}`,
				Model:        "test-model",
				InputTokens:  10,
				OutputTokens: 5,
			}, nil
		},
	}
	server := newTestServer(be)

	// Simulate what the workflow sends: a real pipeline TraceID + a phantom stage SpanID.
	// The phantom span ID is a random 16-char hex string generated by workflow.SideEffect
	// (see services/worker/workflows/pipeline.go lines 872-878). It is NOT a real OTel span.
	pipelineTraceID := "aabbccddeeff00112233445566778899"
	phantomStageSpanID := "deadbeef12345678" // random bytes, no real OTel span behind this

	req := &aiv1.TriageContentRequest{
		Content:         "Discuss the sprint planning meeting and upcoming milestones.",
		Subject:         stringPtr("Sprint Planning"),
		Sender:          stringPtr("alice@example.com"),
		TenantId:        stringPtr("tenant-1"),
		ContentId:       stringPtr("em-abc12XYZ"),
		PipelineTraceId: stringPtr(pipelineTraceID),
		PipelineSpanId:  stringPtr(phantomStageSpanID),
	}

	_, err := server.TriageContent(context.Background(), req)
	if err != nil {
		t.Fatalf("TriageContent returned unexpected error: %v", err)
	}

	spans := exporter.GetSpans()

	// -------------------------------------------------------------------
	// ASSERTION 1: The handler should create ONLY 1 span: "ai.triage".
	// NO "stage.triage" span should be created by the handler.
	// (The worker creates stage spans, not the ai-coordinator.)
	// -------------------------------------------------------------------
	if len(spans) != 1 {
		t.Errorf("expected 1 span (ai.triage), got %d span(s): %v",
			len(spans), spanNames(spans))
		t.Log("After fix pf-1b4929: ai-coordinator handlers do NOT create stage spans.")
		t.Log("Only ai.X generation spans are created here.")
	}

	// Find the ai.triage span by name.
	var aiSpan *tracetest.SpanStub
	var stageSpan *tracetest.SpanStub
	for i := range spans {
		s := &spans[i]
		switch s.Name {
		case "stage.triage":
			stageSpan = s
		case "ai.triage":
			aiSpan = s
		}
	}

	// -------------------------------------------------------------------
	// ASSERTION 2: "stage.triage" span must NOT exist (handler doesn't create it).
	// -------------------------------------------------------------------
	if stageSpan != nil {
		t.Error("REGRESSION: 'stage.triage' span found — handler should NOT create stage spans")
		t.Logf("Exported spans: %v", spanNames(spans))
	}

	// -------------------------------------------------------------------
	// ASSERTION 3: "ai.triage" span must exist.
	// -------------------------------------------------------------------
	if aiSpan == nil {
		t.Fatal("'ai.triage' span not found in exported spans (handler should create this)")
	}

	// -------------------------------------------------------------------
	// ASSERTION 4: Phase 4 — ai.triage trace ID is auto-generated (NOT the pipelineTraceID).
	// applyPipelineTrace no longer reconstructs span context from string IDs.
	// OTel interceptors propagate trace context via gRPC metadata instead.
	// -------------------------------------------------------------------
	aiTraceID := aiSpan.SpanContext.TraceID().String()
	if aiTraceID == pipelineTraceID {
		t.Errorf("Phase 4: ai.triage trace ID should be auto-generated, not pipelineTraceID. Got %s", aiTraceID)
	}
	if aiTraceID == "" {
		t.Error("expected a non-empty auto-generated trace ID")
	}

	// -------------------------------------------------------------------
	// ASSERTION 5: Phase 4 — ai.triage is a root span (no parent from manual reconstruction).
	// In production, the parent comes from OTel gRPC interceptors, not string IDs.
	// -------------------------------------------------------------------
	aiParentSpanID := aiSpan.Parent.SpanID().String()
	t.Logf("Phase 4: ai.triage parent span ID = %s (root span — no manual reconstruction)", aiParentSpanID)
}

// TestStartPipelineTracing_ZeroDurationSpan_BugReproduction reproduces the
// second aspect of bug pf-9b868f: the email-processing span has zero duration
// because StartPipelineTracing uses `defer span.End()` (line 171 of
// pipeline_activities.go). The span ends the moment the activity returns,
// capturing none of the pipeline's actual work.
//
// This test verifies that the pipeline span duration is non-trivially short,
// and documents that the current implementation ends the span immediately
// (giving it zero duration relative to the pipeline's real work time).
//
// Currently FAILS: the span duration is ~0ms because span.End() is deferred
// and fires when the activity goroutine returns, not when the pipeline finishes.
func TestStartPipelineTracing_ZeroDurationSpan_BugReproduction(t *testing.T) {
	exporter, cleanup := setupStageSpanTestTracer(t)
	defer cleanup()

	// We import the activities package indirectly through the tracing package
	// to test the span lifetime. The pipeline span is created inside
	// StartPipelineTracing activity with `defer span.End()`, which ends the
	// span as soon as the activity function returns.
	//
	// The correct fix is to NOT use defer span.End() in the activity, and
	// instead return the span (or a cancellation function) so the workflow
	// can end it when the pipeline completes.
	//
	// Here we directly test the tracing.StartPipeline API to show that if a
	// span is ended immediately (simulating defer span.End()), its duration
	// is effectively zero compared to the actual pipeline duration.

	contentID := "em-abc12XYZ"
	contentType := "email"
	pipelineTraceID := "1122334455667788aabbccddeeff0011"

	// Simulate what StartPipelineTracing activity does: create span then
	// immediately end it (defer fires on return).
	simulateActivityBehavior := func() (startTime, endTime time.Time) {
		ctx := context.Background()
		_, span := tracing.StartPipeline(ctx, "email-processing", contentID, contentType, "tenant-1", pipelineTraceID)
		startTime = time.Now()
		// Activity returns here — defer span.End() fires immediately.
		defer span.End()
		endTime = time.Now()
		return startTime, endTime
	}

	start, end := simulateActivityBehavior()

	// Give the exporter a moment to flush (it's synchronous, but just in case).
	time.Sleep(1 * time.Millisecond)

	spans := exporter.GetSpans()
	if len(spans) != 1 {
		t.Fatalf("expected 1 span (email-processing), got %d", len(spans))
	}

	pipelineSpan := spans[0]

	if pipelineSpan.Name != "email-processing" {
		t.Errorf("expected span name 'email-processing', got %q", pipelineSpan.Name)
	}

	// The span duration as captured by OTel
	spanDuration := pipelineSpan.EndTime.Sub(pipelineSpan.StartTime)

	// Simulated pipeline work duration (what should happen: span lives as long
	// as the actual pipeline, not just the activity execution time).
	// For the test we use the actual end-start gap as a proxy.
	simulatedPipelineDuration := end.Sub(start)

	t.Logf("OTel span duration: %v", spanDuration)
	t.Logf("Activity goroutine duration: %v", simulatedPipelineDuration)

	// The bug: the span is ended inside the activity when it returns,
	// not when the pipeline workflow completes. The span has a valid start/end
	// time but represents only the activity's return time, not the full
	// pipeline duration.
	//
	// Assert that the span duration is < 1ms (proving it's effectively zero
	// — it ends immediately when the activity returns).
	//
	// This documents the bug: in production, the pipeline takes seconds but
	// the email-processing span records near-zero duration.
	if spanDuration >= 100*time.Millisecond {
		// Unexpectedly long — this would mean the span actually lives long enough.
		// This is the DESIRED behavior after the fix. If this assertion fails it
		// means the test environment somehow makes the span long (unlikely in unit tests).
		t.Logf("NOTE: span duration %v is >= 100ms — this is the desired fixed behavior", spanDuration)
	} else {
		// The span ends almost immediately — this is the BUG.
		t.Logf("BUG pf-9b868f: email-processing span duration is %v (near-zero)", spanDuration)
		t.Log("The span ends when StartPipelineTracing activity returns (defer span.End()),")
		t.Log("not when the pipeline workflow completes. In Langfuse this appears as a")
		t.Log("zero-duration root observation with no child observations under it.")
	}

	// The actual assertion that documents the bug symptom:
	// The email-processing span must NOT end before the pipeline does real work.
	// The fix requires the span to outlive the activity that creates it.
	//
	// We enforce: the span duration must be >= 1ms to be considered meaningful.
	// A zero-duration span (< 1ms) proves the `defer span.End()` bug is present.
	//
	// NOTE: In unit tests the span will always be near-zero because we have no
	// real pipeline work. This assertion is deliberately set to a threshold that
	// the current `defer span.End()` implementation cannot satisfy, proving that
	// the implementation approach (ending span in activity) is fundamentally wrong.
	// The fix must change the architecture so the span is NOT ended in the activity.
	const minExpectedDuration = 1 * time.Millisecond
	if spanDuration < minExpectedDuration {
		t.Errorf("BUG pf-9b868f: email-processing span duration %v is less than %v — "+
			"the span ends when StartPipelineTracing activity returns (defer span.End()), "+
			"not when the pipeline workflow completes. "+
			"Fix: do not use defer span.End() in the activity; the span must outlive the activity.",
			spanDuration, minExpectedDuration)
	}

	t.Logf("EXPECTED after fix: span duration should cover the full pipeline execution time (>= %v)", minExpectedDuration)
	t.Logf("CURRENT (buggy): span duration = %v (activity return time, not pipeline time)", spanDuration)
}

// TestTriageContent_HandlerUsesApplyPipelineTrace verifies that after fix pf-1b4929,
// the ai-coordinator handler does NOT create stage spans, and applyPipelineTrace
// correctly sets the parent span ID from the PipelineSpanID proto field.
//
// The handler creates only ai.X spans. The parent/trace context comes from
// applyPipelineTrace, which uses PipelineTraceID and PipelineSpanID from the proto.
func TestTriageContent_HandlerUsesApplyPipelineTrace(t *testing.T) {
	exporter, cleanup := setupStageSpanTestTracer(t)
	defer cleanup()

	be := &mockBackend{
		chatCompletionFunc: func(ctx context.Context, messages []backend.Message, opts backend.CompletionOptions) (*backend.CompletionResult, error) {
			return &backend.CompletionResult{
				Content:     `{"category": "CUSTOMER", "importance": "MEDIUM", "reason": "test"}`,
				Model:       "test-model",
				InputTokens: 5, OutputTokens: 3,
			}, nil
		},
	}
	server := newTestServer(be)

	// This phantom span ID simulates what workflow.SideEffect generates:
	// 8 random bytes encoded as hex. There is no OTel span with this ID.
	phantomStageSpanID := "cafebabe01234567"
	pipelineTraceID := "fedcba9876543210fedcba9876543210"

	req := &aiv1.TriageContentRequest{
		Content:         "Customer asking about product pricing and availability.",
		Subject:         stringPtr("Pricing question"),
		TenantId:        stringPtr("tenant-2"),
		ContentId:       stringPtr("em-xyz98ABC"),
		PipelineTraceId: stringPtr(pipelineTraceID),
		PipelineSpanId:  stringPtr(phantomStageSpanID),
	}

	_, err := server.TriageContent(context.Background(), req)
	if err != nil {
		t.Fatalf("TriageContent returned unexpected error: %v", err)
	}

	spans := exporter.GetSpans()

	// After fix pf-1b4929: handler creates only 1 span (ai.triage).
	if len(spans) != 1 {
		t.Errorf("expected 1 span (ai.triage), got %d", len(spans))
	}

	// Verify NO stage spans created by the handler.
	var stageSpan *tracetest.SpanStub
	var aiSpan *tracetest.SpanStub
	for i := range spans {
		s := &spans[i]
		if s.Name == "stage.triage" {
			stageSpan = s
		} else if s.Name == "ai.triage" {
			aiSpan = s
		}
	}

	if stageSpan != nil {
		t.Error("REGRESSION: handler created 'stage.triage' span — should not happen after pf-1b4929")
	}

	if aiSpan == nil {
		t.Fatal("ai.triage span not found in exports")
	}

	// Phase 4: applyPipelineTrace no longer reconstructs span context from string IDs.
	// OTel interceptors propagate trace context via gRPC metadata instead.

	// Verify trace ID is auto-generated (NOT the provided pipelineTraceID).
	aiTraceID := aiSpan.SpanContext.TraceID().String()
	if aiTraceID == pipelineTraceID {
		t.Errorf("Phase 4: ai.triage trace ID should be auto-generated, not pipelineTraceID %s", pipelineTraceID)
	}
	if aiTraceID == "" {
		t.Error("expected a non-empty auto-generated trace ID")
	}

	// Verify span is a root span (no parent from manual reconstruction).
	// In production, the parent comes from OTel gRPC interceptors, not string IDs.
	aiParentSpanID := aiSpan.Parent.SpanID().String()
	if aiSpan.Parent.IsValid() {
		t.Errorf("Phase 4: ai.triage should be a root span (no parent from manual reconstruction). Parent: %s", aiParentSpanID)
	}
	t.Logf("Phase 4: ai.triage is a root span (parent span ID = %s). OTel handles propagation in production.", aiParentSpanID)
}

// spanNames returns the names of all spans for use in diagnostic messages.
func spanNames(spans tracetest.SpanStubs) []string {
	names := make([]string, len(spans))
	for i, s := range spans {
		names[i] = s.Name
	}
	return names
}

// Ensure trace.SpanID type is used (avoids unused import).
var _ = trace.SpanID{}
