// WatchList Service Protobuf Definitions
// Provides gRPC service for watch list management, trust/seniority, and briefing queries

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: watchlist/v1/watchlist.proto

package watchlistv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WatchListService_AddWatchItem_FullMethodName            = "/penfold.watchlist.v1.WatchListService/AddWatchItem"
	WatchListService_RemoveWatchItem_FullMethodName         = "/penfold.watchlist.v1.WatchListService/RemoveWatchItem"
	WatchListService_ListWatchItems_FullMethodName          = "/penfold.watchlist.v1.WatchListService/ListWatchItems"
	WatchListService_UpdateWatchItem_FullMethodName         = "/penfold.watchlist.v1.WatchListService/UpdateWatchItem"
	WatchListService_SetTrust_FullMethodName                = "/penfold.watchlist.v1.WatchListService/SetTrust"
	WatchListService_SetSeniority_FullMethodName            = "/penfold.watchlist.v1.WatchListService/SetSeniority"
	WatchListService_GetBriefingAssertions_FullMethodName   = "/penfold.watchlist.v1.WatchListService/GetBriefingAssertions"
	WatchListService_GetSeniorityEscalations_FullMethodName = "/penfold.watchlist.v1.WatchListService/GetSeniorityEscalations"
)

// WatchListServiceClient is the client API for WatchListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WatchListService provides gRPC endpoints for watch list and priority management.
type WatchListServiceClient interface {
	// Watch list operations
	AddWatchItem(ctx context.Context, in *AddWatchItemRequest, opts ...grpc.CallOption) (*AddWatchItemResponse, error)
	RemoveWatchItem(ctx context.Context, in *RemoveWatchItemRequest, opts ...grpc.CallOption) (*RemoveWatchItemResponse, error)
	ListWatchItems(ctx context.Context, in *ListWatchItemsRequest, opts ...grpc.CallOption) (*ListWatchItemsResponse, error)
	UpdateWatchItem(ctx context.Context, in *UpdateWatchItemRequest, opts ...grpc.CallOption) (*UpdateWatchItemResponse, error)
	// Trust and seniority management
	SetTrust(ctx context.Context, in *SetTrustRequest, opts ...grpc.CallOption) (*SetTrustResponse, error)
	SetSeniority(ctx context.Context, in *SetSeniorityRequest, opts ...grpc.CallOption) (*SetSeniorityResponse, error)
	// Briefing and escalation queries
	GetBriefingAssertions(ctx context.Context, in *GetBriefingAssertionsRequest, opts ...grpc.CallOption) (*GetBriefingAssertionsResponse, error)
	GetSeniorityEscalations(ctx context.Context, in *GetSeniorityEscalationsRequest, opts ...grpc.CallOption) (*GetSeniorityEscalationsResponse, error)
}

type watchListServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWatchListServiceClient(cc grpc.ClientConnInterface) WatchListServiceClient {
	return &watchListServiceClient{cc}
}

func (c *watchListServiceClient) AddWatchItem(ctx context.Context, in *AddWatchItemRequest, opts ...grpc.CallOption) (*AddWatchItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddWatchItemResponse)
	err := c.cc.Invoke(ctx, WatchListService_AddWatchItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchListServiceClient) RemoveWatchItem(ctx context.Context, in *RemoveWatchItemRequest, opts ...grpc.CallOption) (*RemoveWatchItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveWatchItemResponse)
	err := c.cc.Invoke(ctx, WatchListService_RemoveWatchItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchListServiceClient) ListWatchItems(ctx context.Context, in *ListWatchItemsRequest, opts ...grpc.CallOption) (*ListWatchItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWatchItemsResponse)
	err := c.cc.Invoke(ctx, WatchListService_ListWatchItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchListServiceClient) UpdateWatchItem(ctx context.Context, in *UpdateWatchItemRequest, opts ...grpc.CallOption) (*UpdateWatchItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWatchItemResponse)
	err := c.cc.Invoke(ctx, WatchListService_UpdateWatchItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchListServiceClient) SetTrust(ctx context.Context, in *SetTrustRequest, opts ...grpc.CallOption) (*SetTrustResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTrustResponse)
	err := c.cc.Invoke(ctx, WatchListService_SetTrust_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchListServiceClient) SetSeniority(ctx context.Context, in *SetSeniorityRequest, opts ...grpc.CallOption) (*SetSeniorityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSeniorityResponse)
	err := c.cc.Invoke(ctx, WatchListService_SetSeniority_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchListServiceClient) GetBriefingAssertions(ctx context.Context, in *GetBriefingAssertionsRequest, opts ...grpc.CallOption) (*GetBriefingAssertionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBriefingAssertionsResponse)
	err := c.cc.Invoke(ctx, WatchListService_GetBriefingAssertions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchListServiceClient) GetSeniorityEscalations(ctx context.Context, in *GetSeniorityEscalationsRequest, opts ...grpc.CallOption) (*GetSeniorityEscalationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSeniorityEscalationsResponse)
	err := c.cc.Invoke(ctx, WatchListService_GetSeniorityEscalations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WatchListServiceServer is the server API for WatchListService service.
// All implementations must embed UnimplementedWatchListServiceServer
// for forward compatibility.
//
// WatchListService provides gRPC endpoints for watch list and priority management.
type WatchListServiceServer interface {
	// Watch list operations
	AddWatchItem(context.Context, *AddWatchItemRequest) (*AddWatchItemResponse, error)
	RemoveWatchItem(context.Context, *RemoveWatchItemRequest) (*RemoveWatchItemResponse, error)
	ListWatchItems(context.Context, *ListWatchItemsRequest) (*ListWatchItemsResponse, error)
	UpdateWatchItem(context.Context, *UpdateWatchItemRequest) (*UpdateWatchItemResponse, error)
	// Trust and seniority management
	SetTrust(context.Context, *SetTrustRequest) (*SetTrustResponse, error)
	SetSeniority(context.Context, *SetSeniorityRequest) (*SetSeniorityResponse, error)
	// Briefing and escalation queries
	GetBriefingAssertions(context.Context, *GetBriefingAssertionsRequest) (*GetBriefingAssertionsResponse, error)
	GetSeniorityEscalations(context.Context, *GetSeniorityEscalationsRequest) (*GetSeniorityEscalationsResponse, error)
	mustEmbedUnimplementedWatchListServiceServer()
}

// UnimplementedWatchListServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWatchListServiceServer struct{}

func (UnimplementedWatchListServiceServer) AddWatchItem(context.Context, *AddWatchItemRequest) (*AddWatchItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddWatchItem not implemented")
}
func (UnimplementedWatchListServiceServer) RemoveWatchItem(context.Context, *RemoveWatchItemRequest) (*RemoveWatchItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveWatchItem not implemented")
}
func (UnimplementedWatchListServiceServer) ListWatchItems(context.Context, *ListWatchItemsRequest) (*ListWatchItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWatchItems not implemented")
}
func (UnimplementedWatchListServiceServer) UpdateWatchItem(context.Context, *UpdateWatchItemRequest) (*UpdateWatchItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWatchItem not implemented")
}
func (UnimplementedWatchListServiceServer) SetTrust(context.Context, *SetTrustRequest) (*SetTrustResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTrust not implemented")
}
func (UnimplementedWatchListServiceServer) SetSeniority(context.Context, *SetSeniorityRequest) (*SetSeniorityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSeniority not implemented")
}
func (UnimplementedWatchListServiceServer) GetBriefingAssertions(context.Context, *GetBriefingAssertionsRequest) (*GetBriefingAssertionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBriefingAssertions not implemented")
}
func (UnimplementedWatchListServiceServer) GetSeniorityEscalations(context.Context, *GetSeniorityEscalationsRequest) (*GetSeniorityEscalationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSeniorityEscalations not implemented")
}
func (UnimplementedWatchListServiceServer) mustEmbedUnimplementedWatchListServiceServer() {}
func (UnimplementedWatchListServiceServer) testEmbeddedByValue()                          {}

// UnsafeWatchListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatchListServiceServer will
// result in compilation errors.
type UnsafeWatchListServiceServer interface {
	mustEmbedUnimplementedWatchListServiceServer()
}

func RegisterWatchListServiceServer(s grpc.ServiceRegistrar, srv WatchListServiceServer) {
	// If the following call pancis, it indicates UnimplementedWatchListServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WatchListService_ServiceDesc, srv)
}

func _WatchListService_AddWatchItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWatchItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchListServiceServer).AddWatchItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchListService_AddWatchItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchListServiceServer).AddWatchItem(ctx, req.(*AddWatchItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchListService_RemoveWatchItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWatchItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchListServiceServer).RemoveWatchItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchListService_RemoveWatchItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchListServiceServer).RemoveWatchItem(ctx, req.(*RemoveWatchItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchListService_ListWatchItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWatchItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchListServiceServer).ListWatchItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchListService_ListWatchItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchListServiceServer).ListWatchItems(ctx, req.(*ListWatchItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchListService_UpdateWatchItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWatchItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchListServiceServer).UpdateWatchItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchListService_UpdateWatchItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchListServiceServer).UpdateWatchItem(ctx, req.(*UpdateWatchItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchListService_SetTrust_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTrustRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchListServiceServer).SetTrust(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchListService_SetTrust_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchListServiceServer).SetTrust(ctx, req.(*SetTrustRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchListService_SetSeniority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSeniorityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchListServiceServer).SetSeniority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchListService_SetSeniority_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchListServiceServer).SetSeniority(ctx, req.(*SetSeniorityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchListService_GetBriefingAssertions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBriefingAssertionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchListServiceServer).GetBriefingAssertions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchListService_GetBriefingAssertions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchListServiceServer).GetBriefingAssertions(ctx, req.(*GetBriefingAssertionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchListService_GetSeniorityEscalations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeniorityEscalationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchListServiceServer).GetSeniorityEscalations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchListService_GetSeniorityEscalations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchListServiceServer).GetSeniorityEscalations(ctx, req.(*GetSeniorityEscalationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WatchListService_ServiceDesc is the grpc.ServiceDesc for WatchListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WatchListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "penfold.watchlist.v1.WatchListService",
	HandlerType: (*WatchListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddWatchItem",
			Handler:    _WatchListService_AddWatchItem_Handler,
		},
		{
			MethodName: "RemoveWatchItem",
			Handler:    _WatchListService_RemoveWatchItem_Handler,
		},
		{
			MethodName: "ListWatchItems",
			Handler:    _WatchListService_ListWatchItems_Handler,
		},
		{
			MethodName: "UpdateWatchItem",
			Handler:    _WatchListService_UpdateWatchItem_Handler,
		},
		{
			MethodName: "SetTrust",
			Handler:    _WatchListService_SetTrust_Handler,
		},
		{
			MethodName: "SetSeniority",
			Handler:    _WatchListService_SetSeniority_Handler,
		},
		{
			MethodName: "GetBriefingAssertions",
			Handler:    _WatchListService_GetBriefingAssertions_Handler,
		},
		{
			MethodName: "GetSeniorityEscalations",
			Handler:    _WatchListService_GetSeniorityEscalations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "watchlist/v1/watchlist.proto",
}
