// Gmail Connector Service Protobuf Definitions
// Defines the gRPC service for syncing and managing Gmail messages

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gmailpb/gmail.proto

package gmailpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncState enumerates the possible states of a sync operation.
type SyncState int32

const (
	// Default value, should not be used
	SyncState_SYNC_STATE_UNSPECIFIED SyncState = 0
	// Sync operation is queued and waiting to start
	SyncState_SYNC_STATE_PENDING SyncState = 1
	// Sync operation is currently in progress
	SyncState_SYNC_STATE_IN_PROGRESS SyncState = 2
	// Sync operation completed successfully
	SyncState_SYNC_STATE_COMPLETED SyncState = 3
	// Sync operation completed with some errors
	SyncState_SYNC_STATE_COMPLETED_WITH_ERRORS SyncState = 4
	// Sync operation failed
	SyncState_SYNC_STATE_FAILED SyncState = 5
	// Sync operation was cancelled
	SyncState_SYNC_STATE_CANCELLED SyncState = 6
)

// Enum value maps for SyncState.
var (
	SyncState_name = map[int32]string{
		0: "SYNC_STATE_UNSPECIFIED",
		1: "SYNC_STATE_PENDING",
		2: "SYNC_STATE_IN_PROGRESS",
		3: "SYNC_STATE_COMPLETED",
		4: "SYNC_STATE_COMPLETED_WITH_ERRORS",
		5: "SYNC_STATE_FAILED",
		6: "SYNC_STATE_CANCELLED",
	}
	SyncState_value = map[string]int32{
		"SYNC_STATE_UNSPECIFIED":           0,
		"SYNC_STATE_PENDING":               1,
		"SYNC_STATE_IN_PROGRESS":           2,
		"SYNC_STATE_COMPLETED":             3,
		"SYNC_STATE_COMPLETED_WITH_ERRORS": 4,
		"SYNC_STATE_FAILED":                5,
		"SYNC_STATE_CANCELLED":             6,
	}
)

func (x SyncState) Enum() *SyncState {
	p := new(SyncState)
	*p = x
	return p
}

func (x SyncState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncState) Descriptor() protoreflect.EnumDescriptor {
	return file_gmailpb_gmail_proto_enumTypes[0].Descriptor()
}

func (SyncState) Type() protoreflect.EnumType {
	return &file_gmailpb_gmail_proto_enumTypes[0]
}

func (x SyncState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncState.Descriptor instead.
func (SyncState) EnumDescriptor() ([]byte, []int) {
	return file_gmailpb_gmail_proto_rawDescGZIP(), []int{0}
}

// EmailFormat specifies the format for retrieving email content.
type EmailFormat int32

const (
	// Returns only email metadata (IDs, labels, thread info)
	EmailFormat_EMAIL_FORMAT_METADATA EmailFormat = 0
	// Returns all email data except body content
	EmailFormat_EMAIL_FORMAT_MINIMAL EmailFormat = 1
	// Returns full email message including body
	EmailFormat_EMAIL_FORMAT_FULL EmailFormat = 2
	// Returns the raw RFC 2822 formatted email
	EmailFormat_EMAIL_FORMAT_RAW EmailFormat = 3
)

// Enum value maps for EmailFormat.
var (
	EmailFormat_name = map[int32]string{
		0: "EMAIL_FORMAT_METADATA",
		1: "EMAIL_FORMAT_MINIMAL",
		2: "EMAIL_FORMAT_FULL",
		3: "EMAIL_FORMAT_RAW",
	}
	EmailFormat_value = map[string]int32{
		"EMAIL_FORMAT_METADATA": 0,
		"EMAIL_FORMAT_MINIMAL":  1,
		"EMAIL_FORMAT_FULL":     2,
		"EMAIL_FORMAT_RAW":      3,
	}
)

func (x EmailFormat) Enum() *EmailFormat {
	p := new(EmailFormat)
	*p = x
	return p
}

func (x EmailFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmailFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_gmailpb_gmail_proto_enumTypes[1].Descriptor()
}

func (EmailFormat) Type() protoreflect.EnumType {
	return &file_gmailpb_gmail_proto_enumTypes[1]
}

func (x EmailFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmailFormat.Descriptor instead.
func (EmailFormat) EnumDescriptor() ([]byte, []int) {
	return file_gmailpb_gmail_proto_rawDescGZIP(), []int{1}
}

// Email represents a Gmail message with all relevant metadata.
type Email struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique Gmail message ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Gmail thread ID for conversation grouping
	ThreadId string `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	// Email subject line
	Subject string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	// Sender email address and optional display name
	From *EmailAddress `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	// List of primary recipients
	To []*EmailAddress `protobuf:"bytes,5,rep,name=to,proto3" json:"to,omitempty"`
	// List of CC recipients
	Cc []*EmailAddress `protobuf:"bytes,6,rep,name=cc,proto3" json:"cc,omitempty"`
	// List of BCC recipients (if available)
	Bcc []*EmailAddress `protobuf:"bytes,7,rep,name=bcc,proto3" json:"bcc,omitempty"`
	// Email body content
	Body *EmailBody `protobuf:"bytes,8,opt,name=body,proto3" json:"body,omitempty"`
	// When the email was sent/received
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Gmail labels applied to this message
	Labels []string `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty"`
	// Whether the email has attachments
	HasAttachments bool `protobuf:"varint,11,opt,name=has_attachments,json=hasAttachments,proto3" json:"has_attachments,omitempty"`
	// List of attachment metadata (if has_attachments is true)
	Attachments []*Attachment `protobuf:"bytes,12,rep,name=attachments,proto3" json:"attachments,omitempty"`
	// Gmail internal date (epoch milliseconds)
	InternalDate int64 `protobuf:"varint,13,opt,name=internal_date,json=internalDate,proto3" json:"internal_date,omitempty"`
	// Size of the message in bytes
	SizeEstimate int64 `protobuf:"varint,14,opt,name=size_estimate,json=sizeEstimate,proto3" json:"size_estimate,omitempty"`
	// Whether the email has been read
	IsRead bool `protobuf:"varint,15,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	// Whether the email is starred
	IsStarred bool `protobuf:"varint,16,opt,name=is_starred,json=isStarred,proto3" json:"is_starred,omitempty"`
	// Snippet preview of the email content
	Snippet string `protobuf:"bytes,17,opt,name=snippet,proto3" json:"snippet,omitempty"`
	// RFC 2822 Message-ID header
	MessageIdHeader string `protobuf:"bytes,18,opt,name=message_id_header,json=messageIdHeader,proto3" json:"message_id_header,omitempty"`
	// In-Reply-To header for threading
	InReplyTo *string `protobuf:"bytes,19,opt,name=in_reply_to,json=inReplyTo,proto3,oneof" json:"in_reply_to,omitempty"`
	// References header for threading
	References    []string `protobuf:"bytes,20,rep,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Email) Reset() {
	*x = Email{}
	mi := &file_gmailpb_gmail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_gmailpb_gmail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_gmailpb_gmail_proto_rawDescGZIP(), []int{0}
}

func (x *Email) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Email) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *Email) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Email) GetFrom() *EmailAddress {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Email) GetTo() []*EmailAddress {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Email) GetCc() []*EmailAddress {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *Email) GetBcc() []*EmailAddress {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *Email) GetBody() *EmailBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Email) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Email) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Email) GetHasAttachments() bool {
	if x != nil {
		return x.HasAttachments
	}
	return false
}

func (x *Email) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *Email) GetInternalDate() int64 {
	if x != nil {
		return x.InternalDate
	}
	return 0
}

func (x *Email) GetSizeEstimate() int64 {
	if x != nil {
		return x.SizeEstimate
	}
	return 0
}

func (x *Email) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Email) GetIsStarred() bool {
	if x != nil {
		return x.IsStarred
	}
	return false
}

func (x *Email) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *Email) GetMessageIdHeader() string {
	if x != nil {
		return x.MessageIdHeader
	}
	return ""
}

func (x *Email) GetInReplyTo() string {
	if x != nil && x.InReplyTo != nil {
		return *x.InReplyTo
	}
	return ""
}

func (x *Email) GetReferences() []string {
	if x != nil {
		return x.References
	}
	return nil
}

// EmailAddress represents an email address with optional display name.
type EmailAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Email address (e.g., "user@example.com")
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Display name (e.g., "John Doe")
	Name          *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailAddress) Reset() {
	*x = EmailAddress{}
	mi := &file_gmailpb_gmail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailAddress) ProtoMessage() {}

func (x *EmailAddress) ProtoReflect() protoreflect.Message {
	mi := &file_gmailpb_gmail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailAddress.ProtoReflect.Descriptor instead.
func (*EmailAddress) Descriptor() ([]byte, []int) {
	return file_gmailpb_gmail_proto_rawDescGZIP(), []int{1}
}

func (x *EmailAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *EmailAddress) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// EmailBody contains the email content in various formats.
type EmailBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plain text version of the email body
	PlainText string `protobuf:"bytes,1,opt,name=plain_text,json=plainText,proto3" json:"plain_text,omitempty"`
	// HTML version of the email body (if available)
	Html          *string `protobuf:"bytes,2,opt,name=html,proto3,oneof" json:"html,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailBody) Reset() {
	*x = EmailBody{}
	mi := &file_gmailpb_gmail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailBody) ProtoMessage() {}

func (x *EmailBody) ProtoReflect() protoreflect.Message {
	mi := &file_gmailpb_gmail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailBody.ProtoReflect.Descriptor instead.
func (*EmailBody) Descriptor() ([]byte, []int) {
	return file_gmailpb_gmail_proto_rawDescGZIP(), []int{2}
}

func (x *EmailBody) GetPlainText() string {
	if x != nil {
		return x.PlainText
	}
	return ""
}

func (x *EmailBody) GetHtml() string {
	if x != nil && x.Html != nil {
		return *x.Html
	}
	return ""
}

// Attachment represents email attachment metadata.
type Attachment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Attachment ID for fetching the content
	AttachmentId string `protobuf:"bytes,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	// Original filename
	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	// MIME type of the attachment
	MimeType string `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Size in bytes
	Size          int64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_gmailpb_gmail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_gmailpb_gmail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_gmailpb_gmail_proto_rawDescGZIP(), []int{3}
}

func (x *Attachment) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Attachment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// SyncEmailsRequest initiates email synchronization from Gmail.
type SyncEmailsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant identifier for multi-tenancy support
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Start date for sync range (inclusive, optional)
	// If not specified, syncs from last sync point or beginning
	StartDate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	// End date for sync range (inclusive, optional)
	// If not specified, syncs up to current time
	EndDate *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	// Filter to specific labels (e.g., "INBOX", "IMPORTANT")
	// Empty list means sync all labels
	Labels []string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	// Gmail search query for filtering (e.g., "from:example.com")
	Query *string `protobuf:"bytes,5,opt,name=query,proto3,oneof" json:"query,omitempty"`
	// Maximum number of emails to sync in this request
	// Default: 500, Max: 10000
	MaxResults int32 `protobuf:"varint,6,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	// Whether to force full sync (ignore last sync point)
	ForceFullSync bool `protobuf:"varint,7,opt,name=force_full_sync,json=forceFullSync,proto3" json:"force_full_sync,omitempty"`
	// Include spam and trash folders
	IncludeSpamTrash bool `protobuf:"varint,8,opt,name=include_spam_trash,json=includeSpamTrash,proto3" json:"include_spam_trash,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncEmailsRequest) Reset() {
	*x = SyncEmailsRequest{}
	mi := &file_gmailpb_gmail_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEmailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEmailsRequest) ProtoMessage() {}

func (x *SyncEmailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gmailpb_gmail_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEmailsRequest.ProtoReflect.Descriptor instead.
func (*SyncEmailsRequest) Descriptor() ([]byte, []int) {
	return file_gmailpb_gmail_proto_rawDescGZIP(), []int{4}
}

func (x *SyncEmailsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SyncEmailsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *SyncEmailsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *SyncEmailsRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SyncEmailsRequest) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

func (x *SyncEmailsRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

func (x *SyncEmailsRequest) GetForceFullSync() bool {
	if x != nil {
		return x.ForceFullSync
	}
	return false
}

func (x *SyncEmailsRequest) GetIncludeSpamTrash() bool {
	if x != nil {
		return x.IncludeSpamTrash
	}
	return false
}

// SyncEmailsResponse contains the result of a sync operation.
type SyncEmailsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique sync job identifier for tracking progress
	SyncId string `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3" json:"sync_id,omitempty"`
	// Current status of the sync operation
	Status *SyncStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Message providing additional context
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncEmailsResponse) Reset() {
	*x = SyncEmailsResponse{}
	mi := &file_gmailpb_gmail_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEmailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEmailsResponse) ProtoMessage() {}

func (x *SyncEmailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gmailpb_gmail_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEmailsResponse.ProtoReflect.Descriptor instead.
func (*SyncEmailsResponse) Descriptor() ([]byte, []int) {
	return file_gmailpb_gmail_proto_rawDescGZIP(), []int{5}
}

func (x *SyncEmailsResponse) GetSyncId() string {
	if x != nil {
		return x.SyncId
	}
	return ""
}

func (x *SyncEmailsResponse) GetStatus() *SyncStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SyncEmailsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetSyncStatusRequest retrieves status of a sync operation.
type GetSyncStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique sync job identifier
	SyncId string `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3" json:"sync_id,omitempty"`
	// Tenant identifier for multi-tenancy support
	TenantId      string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncStatusRequest) Reset() {
	*x = GetSyncStatusRequest{}
	mi := &file_gmailpb_gmail_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncStatusRequest) ProtoMessage() {}

func (x *GetSyncStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gmailpb_gmail_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSyncStatusRequest) Descriptor() ([]byte, []int) {
	return file_gmailpb_gmail_proto_rawDescGZIP(), []int{6}
}

func (x *GetSyncStatusRequest) GetSyncId() string {
	if x != nil {
		return x.SyncId
	}
	return ""
}

func (x *GetSyncStatusRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// SyncStatus represents the current state of a sync operation.
type SyncStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique sync job identifier
	SyncId string `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3" json:"sync_id,omitempty"`
	// Current state of the sync operation
	State SyncState `protobuf:"varint,2,opt,name=state,proto3,enum=penfold.connectors.gmail.v1.SyncState" json:"state,omitempty"`
	// Number of emails processed so far
	ProcessedCount int64 `protobuf:"varint,3,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	// Total number of emails to process (may be estimated)
	TotalCount int64 `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// Number of emails successfully synced
	SuccessCount int64 `protobuf:"varint,5,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	// Number of emails that failed to sync
	ErrorCount int64 `protobuf:"varint,6,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	// List of errors encountered during sync
	Errors []*SyncError `protobuf:"bytes,7,rep,name=errors,proto3" json:"errors,omitempty"`
	// When the sync operation started
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// When the sync operation completed (if finished)
	CompletedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	// Estimated time remaining in seconds (if in progress)
	EstimatedSecondsRemaining *int64 `protobuf:"varint,10,opt,name=estimated_seconds_remaining,json=estimatedSecondsRemaining,proto3,oneof" json:"estimated_seconds_remaining,omitempty"`
	// History ID for incremental sync tracking
	HistoryId *uint64 `protobuf:"varint,11,opt,name=history_id,json=historyId,proto3,oneof" json:"history_id,omitempty"`
	// Progress percentage (0-100)
	ProgressPercent int32 `protobuf:"varint,12,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncStatus) Reset() {
	*x = SyncStatus{}
	mi := &file_gmailpb_gmail_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStatus) ProtoMessage() {}

func (x *SyncStatus) ProtoReflect() protoreflect.Message {
	mi := &file_gmailpb_gmail_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStatus.ProtoReflect.Descriptor instead.
func (*SyncStatus) Descriptor() ([]byte, []int) {
	return file_gmailpb_gmail_proto_rawDescGZIP(), []int{7}
}

func (x *SyncStatus) GetSyncId() string {
	if x != nil {
		return x.SyncId
	}
	return ""
}

func (x *SyncStatus) GetState() SyncState {
	if x != nil {
		return x.State
	}
	return SyncState_SYNC_STATE_UNSPECIFIED
}

func (x *SyncStatus) GetProcessedCount() int64 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

func (x *SyncStatus) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *SyncStatus) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *SyncStatus) GetErrorCount() int64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *SyncStatus) GetErrors() []*SyncError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *SyncStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SyncStatus) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *SyncStatus) GetEstimatedSecondsRemaining() int64 {
	if x != nil && x.EstimatedSecondsRemaining != nil {
		return *x.EstimatedSecondsRemaining
	}
	return 0
}

func (x *SyncStatus) GetHistoryId() uint64 {
	if x != nil && x.HistoryId != nil {
		return *x.HistoryId
	}
	return 0
}

func (x *SyncStatus) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

// SyncError represents an error that occurred during sync.
type SyncError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Email ID that caused the error (if applicable)
	EmailId *string `protobuf:"bytes,1,opt,name=email_id,json=emailId,proto3,oneof" json:"email_id,omitempty"`
	// Error code
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable error message
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// When the error occurred
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Whether the error is retryable
	Retryable     bool `protobuf:"varint,5,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncError) Reset() {
	*x = SyncError{}
	mi := &file_gmailpb_gmail_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncError) ProtoMessage() {}

func (x *SyncError) ProtoReflect() protoreflect.Message {
	mi := &file_gmailpb_gmail_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncError.ProtoReflect.Descriptor instead.
func (*SyncError) Descriptor() ([]byte, []int) {
	return file_gmailpb_gmail_proto_rawDescGZIP(), []int{8}
}

func (x *SyncError) GetEmailId() string {
	if x != nil && x.EmailId != nil {
		return *x.EmailId
	}
	return ""
}

func (x *SyncError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SyncError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncError) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SyncError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

// ListEmailsRequest retrieves a paginated list of processed emails.
type ListEmailsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant identifier for multi-tenancy support
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Maximum number of results per page (default: 50, max: 200)
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Pagination token from previous response
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Filter by labels
	Labels []string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	// Filter by sender email address
	FromAddress *string `protobuf:"bytes,5,opt,name=from_address,json=fromAddress,proto3,oneof" json:"from_address,omitempty"`
	// Filter by start date (inclusive)
	StartDate *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	// Filter by end date (inclusive)
	EndDate *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	// Search query for filtering results
	Query *string `protobuf:"bytes,8,opt,name=query,proto3,oneof" json:"query,omitempty"`
	// Include only read or unread emails
	IsRead *bool `protobuf:"varint,9,opt,name=is_read,json=isRead,proto3,oneof" json:"is_read,omitempty"`
	// Include only starred emails
	IsStarred *bool `protobuf:"varint,10,opt,name=is_starred,json=isStarred,proto3,oneof" json:"is_starred,omitempty"`
	// Thread ID to filter by specific conversation
	ThreadId *string `protobuf:"bytes,11,opt,name=thread_id,json=threadId,proto3,oneof" json:"thread_id,omitempty"`
	// Sort order: "date_desc" (default), "date_asc"
	OrderBy       string `protobuf:"bytes,12,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmailsRequest) Reset() {
	*x = ListEmailsRequest{}
	mi := &file_gmailpb_gmail_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmailsRequest) ProtoMessage() {}

func (x *ListEmailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gmailpb_gmail_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmailsRequest.ProtoReflect.Descriptor instead.
func (*ListEmailsRequest) Descriptor() ([]byte, []int) {
	return file_gmailpb_gmail_proto_rawDescGZIP(), []int{9}
}

func (x *ListEmailsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListEmailsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEmailsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListEmailsRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ListEmailsRequest) GetFromAddress() string {
	if x != nil && x.FromAddress != nil {
		return *x.FromAddress
	}
	return ""
}

func (x *ListEmailsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ListEmailsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *ListEmailsRequest) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

func (x *ListEmailsRequest) GetIsRead() bool {
	if x != nil && x.IsRead != nil {
		return *x.IsRead
	}
	return false
}

func (x *ListEmailsRequest) GetIsStarred() bool {
	if x != nil && x.IsStarred != nil {
		return *x.IsStarred
	}
	return false
}

func (x *ListEmailsRequest) GetThreadId() string {
	if x != nil && x.ThreadId != nil {
		return *x.ThreadId
	}
	return ""
}

func (x *ListEmailsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

// ListEmailsResponse contains a paginated list of emails.
type ListEmailsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of emails matching the query
	Emails []*Email `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	// Token for fetching the next page (empty if no more results)
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total count of matching emails (if available)
	TotalCount *int64 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3,oneof" json:"total_count,omitempty"`
	// Number of results in this page
	ResultSize    int32 `protobuf:"varint,4,opt,name=result_size,json=resultSize,proto3" json:"result_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmailsResponse) Reset() {
	*x = ListEmailsResponse{}
	mi := &file_gmailpb_gmail_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmailsResponse) ProtoMessage() {}

func (x *ListEmailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gmailpb_gmail_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmailsResponse.ProtoReflect.Descriptor instead.
func (*ListEmailsResponse) Descriptor() ([]byte, []int) {
	return file_gmailpb_gmail_proto_rawDescGZIP(), []int{10}
}

func (x *ListEmailsResponse) GetEmails() []*Email {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *ListEmailsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListEmailsResponse) GetTotalCount() int64 {
	if x != nil && x.TotalCount != nil {
		return *x.TotalCount
	}
	return 0
}

func (x *ListEmailsResponse) GetResultSize() int32 {
	if x != nil {
		return x.ResultSize
	}
	return 0
}

// GetEmailRequest retrieves a single email by ID.
type GetEmailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant identifier for multi-tenancy support
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Gmail message ID
	EmailId string `protobuf:"bytes,2,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	// Format for the email body: "minimal", "full", "raw", "metadata"
	// Default: "full"
	Format        string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailRequest) Reset() {
	*x = GetEmailRequest{}
	mi := &file_gmailpb_gmail_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailRequest) ProtoMessage() {}

func (x *GetEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gmailpb_gmail_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailRequest.ProtoReflect.Descriptor instead.
func (*GetEmailRequest) Descriptor() ([]byte, []int) {
	return file_gmailpb_gmail_proto_rawDescGZIP(), []int{11}
}

func (x *GetEmailRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetEmailRequest) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *GetEmailRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// WatchMailboxRequest sets up push notifications for new emails.
type WatchMailboxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant identifier for multi-tenancy support
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Labels to watch (e.g., "INBOX")
	// Empty list means watch all labels
	Labels []string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	// Cloud Pub/Sub topic for receiving notifications
	// Format: "projects/{project}/topics/{topic}"
	TopicName string `protobuf:"bytes,3,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	// Filter types to watch: "message_added", "message_deleted", "label_added", "label_removed"
	// Default: ["message_added"]
	LabelFilterAction []string `protobuf:"bytes,4,rep,name=label_filter_action,json=labelFilterAction,proto3" json:"label_filter_action,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WatchMailboxRequest) Reset() {
	*x = WatchMailboxRequest{}
	mi := &file_gmailpb_gmail_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchMailboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchMailboxRequest) ProtoMessage() {}

func (x *WatchMailboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gmailpb_gmail_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchMailboxRequest.ProtoReflect.Descriptor instead.
func (*WatchMailboxRequest) Descriptor() ([]byte, []int) {
	return file_gmailpb_gmail_proto_rawDescGZIP(), []int{12}
}

func (x *WatchMailboxRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *WatchMailboxRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *WatchMailboxRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *WatchMailboxRequest) GetLabelFilterAction() []string {
	if x != nil {
		return x.LabelFilterAction
	}
	return nil
}

// WatchMailboxResponse contains the result of setting up push notifications.
type WatchMailboxResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// History ID to use for subsequent sync operations
	HistoryId uint64 `protobuf:"varint,1,opt,name=history_id,json=historyId,proto3" json:"history_id,omitempty"`
	// When the watch will expire (requires renewal)
	Expiration *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
	// Message providing additional context
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchMailboxResponse) Reset() {
	*x = WatchMailboxResponse{}
	mi := &file_gmailpb_gmail_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchMailboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchMailboxResponse) ProtoMessage() {}

func (x *WatchMailboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gmailpb_gmail_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchMailboxResponse.ProtoReflect.Descriptor instead.
func (*WatchMailboxResponse) Descriptor() ([]byte, []int) {
	return file_gmailpb_gmail_proto_rawDescGZIP(), []int{13}
}

func (x *WatchMailboxResponse) GetHistoryId() uint64 {
	if x != nil {
		return x.HistoryId
	}
	return 0
}

func (x *WatchMailboxResponse) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *WatchMailboxResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_gmailpb_gmail_proto protoreflect.FileDescriptor

const file_gmailpb_gmail_proto_rawDesc = "" +
	"\n" +
	"\x13gmailpb/gmail.proto\x12\x1bpenfold.connectors.gmail.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdf\x06\n" +
	"\x05Email\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12=\n" +
	"\x04from\x18\x04 \x01(\v2).penfold.connectors.gmail.v1.EmailAddressR\x04from\x129\n" +
	"\x02to\x18\x05 \x03(\v2).penfold.connectors.gmail.v1.EmailAddressR\x02to\x129\n" +
	"\x02cc\x18\x06 \x03(\v2).penfold.connectors.gmail.v1.EmailAddressR\x02cc\x12;\n" +
	"\x03bcc\x18\a \x03(\v2).penfold.connectors.gmail.v1.EmailAddressR\x03bcc\x12:\n" +
	"\x04body\x18\b \x01(\v2&.penfold.connectors.gmail.v1.EmailBodyR\x04body\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06labels\x18\n" +
	" \x03(\tR\x06labels\x12'\n" +
	"\x0fhas_attachments\x18\v \x01(\bR\x0ehasAttachments\x12I\n" +
	"\vattachments\x18\f \x03(\v2'.penfold.connectors.gmail.v1.AttachmentR\vattachments\x12#\n" +
	"\rinternal_date\x18\r \x01(\x03R\finternalDate\x12#\n" +
	"\rsize_estimate\x18\x0e \x01(\x03R\fsizeEstimate\x12\x17\n" +
	"\ais_read\x18\x0f \x01(\bR\x06isRead\x12\x1d\n" +
	"\n" +
	"is_starred\x18\x10 \x01(\bR\tisStarred\x12\x18\n" +
	"\asnippet\x18\x11 \x01(\tR\asnippet\x12*\n" +
	"\x11message_id_header\x18\x12 \x01(\tR\x0fmessageIdHeader\x12#\n" +
	"\vin_reply_to\x18\x13 \x01(\tH\x00R\tinReplyTo\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"references\x18\x14 \x03(\tR\n" +
	"referencesB\x0e\n" +
	"\f_in_reply_to\"J\n" +
	"\fEmailAddress\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\"L\n" +
	"\tEmailBody\x12\x1d\n" +
	"\n" +
	"plain_text\x18\x01 \x01(\tR\tplainText\x12\x17\n" +
	"\x04html\x18\x02 \x01(\tH\x00R\x04html\x88\x01\x01B\a\n" +
	"\x05_html\"~\n" +
	"\n" +
	"Attachment\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\tR\fattachmentId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"\xfc\x02\n" +
	"\x11SyncEmailsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12>\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartDate\x88\x01\x01\x12:\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aendDate\x88\x01\x01\x12\x16\n" +
	"\x06labels\x18\x04 \x03(\tR\x06labels\x12\x19\n" +
	"\x05query\x18\x05 \x01(\tH\x02R\x05query\x88\x01\x01\x12\x1f\n" +
	"\vmax_results\x18\x06 \x01(\x05R\n" +
	"maxResults\x12&\n" +
	"\x0fforce_full_sync\x18\a \x01(\bR\rforceFullSync\x12,\n" +
	"\x12include_spam_trash\x18\b \x01(\bR\x10includeSpamTrashB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_dateB\b\n" +
	"\x06_query\"\x88\x01\n" +
	"\x12SyncEmailsResponse\x12\x17\n" +
	"\async_id\x18\x01 \x01(\tR\x06syncId\x12?\n" +
	"\x06status\x18\x02 \x01(\v2'.penfold.connectors.gmail.v1.SyncStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"L\n" +
	"\x14GetSyncStatusRequest\x12\x17\n" +
	"\async_id\x18\x01 \x01(\tR\x06syncId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"\x86\x05\n" +
	"\n" +
	"SyncStatus\x12\x17\n" +
	"\async_id\x18\x01 \x01(\tR\x06syncId\x12<\n" +
	"\x05state\x18\x02 \x01(\x0e2&.penfold.connectors.gmail.v1.SyncStateR\x05state\x12'\n" +
	"\x0fprocessed_count\x18\x03 \x01(\x03R\x0eprocessedCount\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x03R\n" +
	"totalCount\x12#\n" +
	"\rsuccess_count\x18\x05 \x01(\x03R\fsuccessCount\x12\x1f\n" +
	"\verror_count\x18\x06 \x01(\x03R\n" +
	"errorCount\x12>\n" +
	"\x06errors\x18\a \x03(\v2&.penfold.connectors.gmail.v1.SyncErrorR\x06errors\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12B\n" +
	"\fcompleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vcompletedAt\x88\x01\x01\x12C\n" +
	"\x1bestimated_seconds_remaining\x18\n" +
	" \x01(\x03H\x01R\x19estimatedSecondsRemaining\x88\x01\x01\x12\"\n" +
	"\n" +
	"history_id\x18\v \x01(\x04H\x02R\thistoryId\x88\x01\x01\x12)\n" +
	"\x10progress_percent\x18\f \x01(\x05R\x0fprogressPercentB\x0f\n" +
	"\r_completed_atB\x1e\n" +
	"\x1c_estimated_seconds_remainingB\r\n" +
	"\v_history_id\"\xbe\x01\n" +
	"\tSyncError\x12\x1e\n" +
	"\bemail_id\x18\x01 \x01(\tH\x00R\aemailId\x88\x01\x01\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\tretryable\x18\x05 \x01(\bR\tretryableB\v\n" +
	"\t_email_id\"\xa2\x04\n" +
	"\x11ListEmailsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06labels\x18\x04 \x03(\tR\x06labels\x12&\n" +
	"\ffrom_address\x18\x05 \x01(\tH\x00R\vfromAddress\x88\x01\x01\x12>\n" +
	"\n" +
	"start_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tstartDate\x88\x01\x01\x12:\n" +
	"\bend_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x02R\aendDate\x88\x01\x01\x12\x19\n" +
	"\x05query\x18\b \x01(\tH\x03R\x05query\x88\x01\x01\x12\x1c\n" +
	"\ais_read\x18\t \x01(\bH\x04R\x06isRead\x88\x01\x01\x12\"\n" +
	"\n" +
	"is_starred\x18\n" +
	" \x01(\bH\x05R\tisStarred\x88\x01\x01\x12 \n" +
	"\tthread_id\x18\v \x01(\tH\x06R\bthreadId\x88\x01\x01\x12\x19\n" +
	"\border_by\x18\f \x01(\tR\aorderByB\x0f\n" +
	"\r_from_addressB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_dateB\b\n" +
	"\x06_queryB\n" +
	"\n" +
	"\b_is_readB\r\n" +
	"\v_is_starredB\f\n" +
	"\n" +
	"_thread_id\"\xcf\x01\n" +
	"\x12ListEmailsResponse\x12:\n" +
	"\x06emails\x18\x01 \x03(\v2\".penfold.connectors.gmail.v1.EmailR\x06emails\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12$\n" +
	"\vtotal_count\x18\x03 \x01(\x03H\x00R\n" +
	"totalCount\x88\x01\x01\x12\x1f\n" +
	"\vresult_size\x18\x04 \x01(\x05R\n" +
	"resultSizeB\x0e\n" +
	"\f_total_count\"a\n" +
	"\x0fGetEmailRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bemail_id\x18\x02 \x01(\tR\aemailId\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\"\x99\x01\n" +
	"\x13WatchMailboxRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06labels\x18\x02 \x03(\tR\x06labels\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x03 \x01(\tR\ttopicName\x12.\n" +
	"\x13label_filter_action\x18\x04 \x03(\tR\x11labelFilterAction\"\x8b\x01\n" +
	"\x14WatchMailboxResponse\x12\x1d\n" +
	"\n" +
	"history_id\x18\x01 \x01(\x04R\thistoryId\x12:\n" +
	"\n" +
	"expiration\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*\xcc\x01\n" +
	"\tSyncState\x12\x1a\n" +
	"\x16SYNC_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SYNC_STATE_PENDING\x10\x01\x12\x1a\n" +
	"\x16SYNC_STATE_IN_PROGRESS\x10\x02\x12\x18\n" +
	"\x14SYNC_STATE_COMPLETED\x10\x03\x12$\n" +
	" SYNC_STATE_COMPLETED_WITH_ERRORS\x10\x04\x12\x15\n" +
	"\x11SYNC_STATE_FAILED\x10\x05\x12\x18\n" +
	"\x14SYNC_STATE_CANCELLED\x10\x06*o\n" +
	"\vEmailFormat\x12\x19\n" +
	"\x15EMAIL_FORMAT_METADATA\x10\x00\x12\x18\n" +
	"\x14EMAIL_FORMAT_MINIMAL\x10\x01\x12\x15\n" +
	"\x11EMAIL_FORMAT_FULL\x10\x02\x12\x14\n" +
	"\x10EMAIL_FORMAT_RAW\x10\x032\xb5\x04\n" +
	"\x15GmailConnectorService\x12m\n" +
	"\n" +
	"SyncEmails\x12..penfold.connectors.gmail.v1.SyncEmailsRequest\x1a/.penfold.connectors.gmail.v1.SyncEmailsResponse\x12k\n" +
	"\rGetSyncStatus\x121.penfold.connectors.gmail.v1.GetSyncStatusRequest\x1a'.penfold.connectors.gmail.v1.SyncStatus\x12m\n" +
	"\n" +
	"ListEmails\x12..penfold.connectors.gmail.v1.ListEmailsRequest\x1a/.penfold.connectors.gmail.v1.ListEmailsResponse\x12\\\n" +
	"\bGetEmail\x12,.penfold.connectors.gmail.v1.GetEmailRequest\x1a\".penfold.connectors.gmail.v1.Email\x12s\n" +
	"\fWatchMailbox\x120.penfold.connectors.gmail.v1.WatchMailboxRequest\x1a1.penfold.connectors.gmail.v1.WatchMailboxResponseBLZJgithub.com/otherjamesbrown/penfold/api/proto/connectors/v1/gmailpb;gmailpbb\x06proto3"

var (
	file_gmailpb_gmail_proto_rawDescOnce sync.Once
	file_gmailpb_gmail_proto_rawDescData []byte
)

func file_gmailpb_gmail_proto_rawDescGZIP() []byte {
	file_gmailpb_gmail_proto_rawDescOnce.Do(func() {
		file_gmailpb_gmail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gmailpb_gmail_proto_rawDesc), len(file_gmailpb_gmail_proto_rawDesc)))
	})
	return file_gmailpb_gmail_proto_rawDescData
}

var file_gmailpb_gmail_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gmailpb_gmail_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_gmailpb_gmail_proto_goTypes = []any{
	(SyncState)(0),                // 0: penfold.connectors.gmail.v1.SyncState
	(EmailFormat)(0),              // 1: penfold.connectors.gmail.v1.EmailFormat
	(*Email)(nil),                 // 2: penfold.connectors.gmail.v1.Email
	(*EmailAddress)(nil),          // 3: penfold.connectors.gmail.v1.EmailAddress
	(*EmailBody)(nil),             // 4: penfold.connectors.gmail.v1.EmailBody
	(*Attachment)(nil),            // 5: penfold.connectors.gmail.v1.Attachment
	(*SyncEmailsRequest)(nil),     // 6: penfold.connectors.gmail.v1.SyncEmailsRequest
	(*SyncEmailsResponse)(nil),    // 7: penfold.connectors.gmail.v1.SyncEmailsResponse
	(*GetSyncStatusRequest)(nil),  // 8: penfold.connectors.gmail.v1.GetSyncStatusRequest
	(*SyncStatus)(nil),            // 9: penfold.connectors.gmail.v1.SyncStatus
	(*SyncError)(nil),             // 10: penfold.connectors.gmail.v1.SyncError
	(*ListEmailsRequest)(nil),     // 11: penfold.connectors.gmail.v1.ListEmailsRequest
	(*ListEmailsResponse)(nil),    // 12: penfold.connectors.gmail.v1.ListEmailsResponse
	(*GetEmailRequest)(nil),       // 13: penfold.connectors.gmail.v1.GetEmailRequest
	(*WatchMailboxRequest)(nil),   // 14: penfold.connectors.gmail.v1.WatchMailboxRequest
	(*WatchMailboxResponse)(nil),  // 15: penfold.connectors.gmail.v1.WatchMailboxResponse
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_gmailpb_gmail_proto_depIdxs = []int32{
	3,  // 0: penfold.connectors.gmail.v1.Email.from:type_name -> penfold.connectors.gmail.v1.EmailAddress
	3,  // 1: penfold.connectors.gmail.v1.Email.to:type_name -> penfold.connectors.gmail.v1.EmailAddress
	3,  // 2: penfold.connectors.gmail.v1.Email.cc:type_name -> penfold.connectors.gmail.v1.EmailAddress
	3,  // 3: penfold.connectors.gmail.v1.Email.bcc:type_name -> penfold.connectors.gmail.v1.EmailAddress
	4,  // 4: penfold.connectors.gmail.v1.Email.body:type_name -> penfold.connectors.gmail.v1.EmailBody
	16, // 5: penfold.connectors.gmail.v1.Email.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 6: penfold.connectors.gmail.v1.Email.attachments:type_name -> penfold.connectors.gmail.v1.Attachment
	16, // 7: penfold.connectors.gmail.v1.SyncEmailsRequest.start_date:type_name -> google.protobuf.Timestamp
	16, // 8: penfold.connectors.gmail.v1.SyncEmailsRequest.end_date:type_name -> google.protobuf.Timestamp
	9,  // 9: penfold.connectors.gmail.v1.SyncEmailsResponse.status:type_name -> penfold.connectors.gmail.v1.SyncStatus
	0,  // 10: penfold.connectors.gmail.v1.SyncStatus.state:type_name -> penfold.connectors.gmail.v1.SyncState
	10, // 11: penfold.connectors.gmail.v1.SyncStatus.errors:type_name -> penfold.connectors.gmail.v1.SyncError
	16, // 12: penfold.connectors.gmail.v1.SyncStatus.started_at:type_name -> google.protobuf.Timestamp
	16, // 13: penfold.connectors.gmail.v1.SyncStatus.completed_at:type_name -> google.protobuf.Timestamp
	16, // 14: penfold.connectors.gmail.v1.SyncError.timestamp:type_name -> google.protobuf.Timestamp
	16, // 15: penfold.connectors.gmail.v1.ListEmailsRequest.start_date:type_name -> google.protobuf.Timestamp
	16, // 16: penfold.connectors.gmail.v1.ListEmailsRequest.end_date:type_name -> google.protobuf.Timestamp
	2,  // 17: penfold.connectors.gmail.v1.ListEmailsResponse.emails:type_name -> penfold.connectors.gmail.v1.Email
	16, // 18: penfold.connectors.gmail.v1.WatchMailboxResponse.expiration:type_name -> google.protobuf.Timestamp
	6,  // 19: penfold.connectors.gmail.v1.GmailConnectorService.SyncEmails:input_type -> penfold.connectors.gmail.v1.SyncEmailsRequest
	8,  // 20: penfold.connectors.gmail.v1.GmailConnectorService.GetSyncStatus:input_type -> penfold.connectors.gmail.v1.GetSyncStatusRequest
	11, // 21: penfold.connectors.gmail.v1.GmailConnectorService.ListEmails:input_type -> penfold.connectors.gmail.v1.ListEmailsRequest
	13, // 22: penfold.connectors.gmail.v1.GmailConnectorService.GetEmail:input_type -> penfold.connectors.gmail.v1.GetEmailRequest
	14, // 23: penfold.connectors.gmail.v1.GmailConnectorService.WatchMailbox:input_type -> penfold.connectors.gmail.v1.WatchMailboxRequest
	7,  // 24: penfold.connectors.gmail.v1.GmailConnectorService.SyncEmails:output_type -> penfold.connectors.gmail.v1.SyncEmailsResponse
	9,  // 25: penfold.connectors.gmail.v1.GmailConnectorService.GetSyncStatus:output_type -> penfold.connectors.gmail.v1.SyncStatus
	12, // 26: penfold.connectors.gmail.v1.GmailConnectorService.ListEmails:output_type -> penfold.connectors.gmail.v1.ListEmailsResponse
	2,  // 27: penfold.connectors.gmail.v1.GmailConnectorService.GetEmail:output_type -> penfold.connectors.gmail.v1.Email
	15, // 28: penfold.connectors.gmail.v1.GmailConnectorService.WatchMailbox:output_type -> penfold.connectors.gmail.v1.WatchMailboxResponse
	24, // [24:29] is the sub-list for method output_type
	19, // [19:24] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_gmailpb_gmail_proto_init() }
func file_gmailpb_gmail_proto_init() {
	if File_gmailpb_gmail_proto != nil {
		return
	}
	file_gmailpb_gmail_proto_msgTypes[0].OneofWrappers = []any{}
	file_gmailpb_gmail_proto_msgTypes[1].OneofWrappers = []any{}
	file_gmailpb_gmail_proto_msgTypes[2].OneofWrappers = []any{}
	file_gmailpb_gmail_proto_msgTypes[4].OneofWrappers = []any{}
	file_gmailpb_gmail_proto_msgTypes[7].OneofWrappers = []any{}
	file_gmailpb_gmail_proto_msgTypes[8].OneofWrappers = []any{}
	file_gmailpb_gmail_proto_msgTypes[9].OneofWrappers = []any{}
	file_gmailpb_gmail_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gmailpb_gmail_proto_rawDesc), len(file_gmailpb_gmail_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gmailpb_gmail_proto_goTypes,
		DependencyIndexes: file_gmailpb_gmail_proto_depIdxs,
		EnumInfos:         file_gmailpb_gmail_proto_enumTypes,
		MessageInfos:      file_gmailpb_gmail_proto_msgTypes,
	}.Build()
	File_gmailpb_gmail_proto = out.File
	file_gmailpb_gmail_proto_goTypes = nil
	file_gmailpb_gmail_proto_depIdxs = nil
}
