// Workflow Orchestrator Service Protobuf Definitions
// Defines the gRPC service for managing Temporal workflows

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: orchestratorpb/orchestrator.proto

package orchestratorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkflowType enumerates the available workflow types.
type WorkflowType int32

const (
	// Unspecified workflow type
	WorkflowType_WORKFLOW_TYPE_UNSPECIFIED WorkflowType = 0
	// Email processing workflow - processes incoming emails through AI pipeline
	WorkflowType_WORKFLOW_TYPE_EMAIL_PROCESSING WorkflowType = 1
	// Content ingestion workflow - ingests and processes documents and content
	WorkflowType_WORKFLOW_TYPE_CONTENT_INGESTION WorkflowType = 2
	// Daily review workflow - generates daily review items for user attention
	WorkflowType_WORKFLOW_TYPE_DAILY_REVIEW WorkflowType = 3
	// Relationship discovery workflow - discovers and analyzes entity relationships
	WorkflowType_WORKFLOW_TYPE_RELATIONSHIP_DISCOVERY WorkflowType = 4
)

// Enum value maps for WorkflowType.
var (
	WorkflowType_name = map[int32]string{
		0: "WORKFLOW_TYPE_UNSPECIFIED",
		1: "WORKFLOW_TYPE_EMAIL_PROCESSING",
		2: "WORKFLOW_TYPE_CONTENT_INGESTION",
		3: "WORKFLOW_TYPE_DAILY_REVIEW",
		4: "WORKFLOW_TYPE_RELATIONSHIP_DISCOVERY",
	}
	WorkflowType_value = map[string]int32{
		"WORKFLOW_TYPE_UNSPECIFIED":            0,
		"WORKFLOW_TYPE_EMAIL_PROCESSING":       1,
		"WORKFLOW_TYPE_CONTENT_INGESTION":      2,
		"WORKFLOW_TYPE_DAILY_REVIEW":           3,
		"WORKFLOW_TYPE_RELATIONSHIP_DISCOVERY": 4,
	}
)

func (x WorkflowType) Enum() *WorkflowType {
	p := new(WorkflowType)
	*p = x
	return p
}

func (x WorkflowType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowType) Descriptor() protoreflect.EnumDescriptor {
	return file_orchestratorpb_orchestrator_proto_enumTypes[0].Descriptor()
}

func (WorkflowType) Type() protoreflect.EnumType {
	return &file_orchestratorpb_orchestrator_proto_enumTypes[0]
}

func (x WorkflowType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowType.Descriptor instead.
func (WorkflowType) EnumDescriptor() ([]byte, []int) {
	return file_orchestratorpb_orchestrator_proto_rawDescGZIP(), []int{0}
}

// WorkflowStatus enumerates the possible workflow execution statuses.
type WorkflowStatus int32

const (
	// Unspecified status
	WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED WorkflowStatus = 0
	// Workflow is pending execution (scheduled but not yet started)
	WorkflowStatus_WORKFLOW_STATUS_PENDING WorkflowStatus = 1
	// Workflow is currently running
	WorkflowStatus_WORKFLOW_STATUS_RUNNING WorkflowStatus = 2
	// Workflow completed successfully
	WorkflowStatus_WORKFLOW_STATUS_COMPLETED WorkflowStatus = 3
	// Workflow failed with an error
	WorkflowStatus_WORKFLOW_STATUS_FAILED WorkflowStatus = 4
	// Workflow was cancelled
	WorkflowStatus_WORKFLOW_STATUS_CANCELLED WorkflowStatus = 5
	// Workflow timed out
	WorkflowStatus_WORKFLOW_STATUS_TIMED_OUT WorkflowStatus = 6
)

// Enum value maps for WorkflowStatus.
var (
	WorkflowStatus_name = map[int32]string{
		0: "WORKFLOW_STATUS_UNSPECIFIED",
		1: "WORKFLOW_STATUS_PENDING",
		2: "WORKFLOW_STATUS_RUNNING",
		3: "WORKFLOW_STATUS_COMPLETED",
		4: "WORKFLOW_STATUS_FAILED",
		5: "WORKFLOW_STATUS_CANCELLED",
		6: "WORKFLOW_STATUS_TIMED_OUT",
	}
	WorkflowStatus_value = map[string]int32{
		"WORKFLOW_STATUS_UNSPECIFIED": 0,
		"WORKFLOW_STATUS_PENDING":     1,
		"WORKFLOW_STATUS_RUNNING":     2,
		"WORKFLOW_STATUS_COMPLETED":   3,
		"WORKFLOW_STATUS_FAILED":      4,
		"WORKFLOW_STATUS_CANCELLED":   5,
		"WORKFLOW_STATUS_TIMED_OUT":   6,
	}
)

func (x WorkflowStatus) Enum() *WorkflowStatus {
	p := new(WorkflowStatus)
	*p = x
	return p
}

func (x WorkflowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_orchestratorpb_orchestrator_proto_enumTypes[1].Descriptor()
}

func (WorkflowStatus) Type() protoreflect.EnumType {
	return &file_orchestratorpb_orchestrator_proto_enumTypes[1]
}

func (x WorkflowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowStatus.Descriptor instead.
func (WorkflowStatus) EnumDescriptor() ([]byte, []int) {
	return file_orchestratorpb_orchestrator_proto_rawDescGZIP(), []int{1}
}

// StartWorkflowRequest initiates a new workflow execution.
type StartWorkflowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of workflow to start: "email_processing", "content_processing", "relationship_discovery"
	WorkflowType string `protobuf:"bytes,1,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	// Tenant identifier for multi-tenancy support
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// JSON-encoded workflow input (specific to workflow type)
	Input []byte `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	// Optional custom workflow ID (auto-generated if not provided)
	WorkflowId    *string `protobuf:"bytes,4,opt,name=workflow_id,json=workflowId,proto3,oneof" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkflowRequest) Reset() {
	*x = StartWorkflowRequest{}
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowRequest) ProtoMessage() {}

func (x *StartWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowRequest.ProtoReflect.Descriptor instead.
func (*StartWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_orchestratorpb_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *StartWorkflowRequest) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *StartWorkflowRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *StartWorkflowRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *StartWorkflowRequest) GetWorkflowId() string {
	if x != nil && x.WorkflowId != nil {
		return *x.WorkflowId
	}
	return ""
}

// StartWorkflowResponse contains the identifiers for the started workflow.
type StartWorkflowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique workflow execution ID
	WorkflowId string `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// Run ID for this specific execution attempt
	RunId         string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkflowResponse) Reset() {
	*x = StartWorkflowResponse{}
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowResponse) ProtoMessage() {}

func (x *StartWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowResponse.ProtoReflect.Descriptor instead.
func (*StartWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_orchestratorpb_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *StartWorkflowResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *StartWorkflowResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

// GetWorkflowStatusRequest retrieves the status of a specific workflow execution.
type GetWorkflowStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique workflow execution ID
	WorkflowId string `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// Optional run ID for a specific execution attempt
	RunId         *string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3,oneof" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowStatusRequest) Reset() {
	*x = GetWorkflowStatusRequest{}
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowStatusRequest) ProtoMessage() {}

func (x *GetWorkflowStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowStatusRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowStatusRequest) Descriptor() ([]byte, []int) {
	return file_orchestratorpb_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorkflowStatusRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *GetWorkflowStatusRequest) GetRunId() string {
	if x != nil && x.RunId != nil {
		return *x.RunId
	}
	return ""
}

// GetWorkflowStatusResponse contains the workflow execution status details.
type GetWorkflowStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The workflow execution details
	Execution     *WorkflowExecution `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowStatusResponse) Reset() {
	*x = GetWorkflowStatusResponse{}
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowStatusResponse) ProtoMessage() {}

func (x *GetWorkflowStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowStatusResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowStatusResponse) Descriptor() ([]byte, []int) {
	return file_orchestratorpb_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorkflowStatusResponse) GetExecution() *WorkflowExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

// WorkflowExecution contains detailed information about a workflow execution.
type WorkflowExecution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique workflow execution ID
	WorkflowId string `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// Run ID for this specific execution attempt
	RunId string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// Type of workflow: "email_processing", "content_processing", "relationship_discovery"
	WorkflowType string `protobuf:"bytes,3,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	// Execution status: "Running", "Completed", "Failed", "Canceled", "Terminated", "TimedOut"
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// When the workflow execution started
	StartTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// When the workflow execution closed (completed, failed, canceled, etc.)
	CloseTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=close_time,json=closeTime,proto3,oneof" json:"close_time,omitempty"`
	// JSON-encoded result if workflow completed successfully
	Result []byte `protobuf:"bytes,7,opt,name=result,proto3,oneof" json:"result,omitempty"`
	// Error message if workflow failed
	Error *string `protobuf:"bytes,8,opt,name=error,proto3,oneof" json:"error,omitempty"`
	// Tenant ID associated with this workflow
	TenantId string `protobuf:"bytes,9,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Task queue the workflow is running on
	TaskQueue string `protobuf:"bytes,10,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	// Number of pending activities
	PendingActivities int32 `protobuf:"varint,11,opt,name=pending_activities,json=pendingActivities,proto3" json:"pending_activities,omitempty"`
	// History event count
	HistoryLength int64 `protobuf:"varint,12,opt,name=history_length,json=historyLength,proto3" json:"history_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowExecution) Reset() {
	*x = WorkflowExecution{}
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecution) ProtoMessage() {}

func (x *WorkflowExecution) ProtoReflect() protoreflect.Message {
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecution.ProtoReflect.Descriptor instead.
func (*WorkflowExecution) Descriptor() ([]byte, []int) {
	return file_orchestratorpb_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *WorkflowExecution) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowExecution) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WorkflowExecution) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *WorkflowExecution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowExecution) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *WorkflowExecution) GetCloseTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CloseTime
	}
	return nil
}

func (x *WorkflowExecution) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *WorkflowExecution) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *WorkflowExecution) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *WorkflowExecution) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

func (x *WorkflowExecution) GetPendingActivities() int32 {
	if x != nil {
		return x.PendingActivities
	}
	return 0
}

func (x *WorkflowExecution) GetHistoryLength() int64 {
	if x != nil {
		return x.HistoryLength
	}
	return 0
}

// ListWorkflowsRequest retrieves a paginated list of workflow executions.
type ListWorkflowsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by workflow type (optional)
	WorkflowType *string `protobuf:"bytes,1,opt,name=workflow_type,json=workflowType,proto3,oneof" json:"workflow_type,omitempty"`
	// Filter by status (optional): "Running", "Completed", "Failed", "Canceled", "Terminated"
	Status *string `protobuf:"bytes,2,opt,name=status,proto3,oneof" json:"status,omitempty"`
	// Filter by tenant ID (optional)
	TenantId *string `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	// Maximum number of results to return (default: 100, max: 1000)
	PageSize int32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Pagination token from previous response
	PageToken string `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Filter by start time range (optional)
	StartTimeFrom *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time_from,json=startTimeFrom,proto3,oneof" json:"start_time_from,omitempty"`
	StartTimeTo   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=start_time_to,json=startTimeTo,proto3,oneof" json:"start_time_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsRequest) Reset() {
	*x = ListWorkflowsRequest{}
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsRequest) ProtoMessage() {}

func (x *ListWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_orchestratorpb_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *ListWorkflowsRequest) GetWorkflowType() string {
	if x != nil && x.WorkflowType != nil {
		return *x.WorkflowType
	}
	return ""
}

func (x *ListWorkflowsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *ListWorkflowsRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *ListWorkflowsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWorkflowsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListWorkflowsRequest) GetStartTimeFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTimeFrom
	}
	return nil
}

func (x *ListWorkflowsRequest) GetStartTimeTo() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTimeTo
	}
	return nil
}

// ListWorkflowsResponse contains a paginated list of workflow executions.
type ListWorkflowsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of workflow executions
	Workflows []*WorkflowExecution `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	// Token for fetching the next page (empty if no more results)
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total count of matching workflows (if available)
	TotalCount    *int64 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3,oneof" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsResponse) Reset() {
	*x = ListWorkflowsResponse{}
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsResponse) ProtoMessage() {}

func (x *ListWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_orchestratorpb_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *ListWorkflowsResponse) GetWorkflows() []*WorkflowExecution {
	if x != nil {
		return x.Workflows
	}
	return nil
}

func (x *ListWorkflowsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListWorkflowsResponse) GetTotalCount() int64 {
	if x != nil && x.TotalCount != nil {
		return *x.TotalCount
	}
	return 0
}

// CancelWorkflowRequest requests cancellation of a running workflow.
type CancelWorkflowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique workflow execution ID to cancel
	WorkflowId string `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// Optional run ID for a specific execution attempt
	RunId *string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3,oneof" json:"run_id,omitempty"`
	// Reason for cancellation
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflowRequest) Reset() {
	*x = CancelWorkflowRequest{}
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowRequest) ProtoMessage() {}

func (x *CancelWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CancelWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_orchestratorpb_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *CancelWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *CancelWorkflowRequest) GetRunId() string {
	if x != nil && x.RunId != nil {
		return *x.RunId
	}
	return ""
}

func (x *CancelWorkflowRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// CancelWorkflowResponse confirms the cancellation request.
type CancelWorkflowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the cancellation request was accepted
	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Message providing additional details
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflowResponse) Reset() {
	*x = CancelWorkflowResponse{}
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowResponse) ProtoMessage() {}

func (x *CancelWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowResponse.ProtoReflect.Descriptor instead.
func (*CancelWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_orchestratorpb_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *CancelWorkflowResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *CancelWorkflowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SignalWorkflowRequest sends a signal to a running workflow execution.
type SignalWorkflowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique workflow execution ID to signal
	WorkflowId string `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// Optional run ID for a specific execution attempt
	RunId *string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3,oneof" json:"run_id,omitempty"`
	// Name of the signal to send
	SignalName string `protobuf:"bytes,3,opt,name=signal_name,json=signalName,proto3" json:"signal_name,omitempty"`
	// JSON-encoded signal payload (optional)
	Payload       []byte `protobuf:"bytes,4,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalWorkflowRequest) Reset() {
	*x = SignalWorkflowRequest{}
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalWorkflowRequest) ProtoMessage() {}

func (x *SignalWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalWorkflowRequest.ProtoReflect.Descriptor instead.
func (*SignalWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_orchestratorpb_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *SignalWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *SignalWorkflowRequest) GetRunId() string {
	if x != nil && x.RunId != nil {
		return *x.RunId
	}
	return ""
}

func (x *SignalWorkflowRequest) GetSignalName() string {
	if x != nil {
		return x.SignalName
	}
	return ""
}

func (x *SignalWorkflowRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// SignalWorkflowResponse confirms the signal was sent.
type SignalWorkflowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the signal was successfully delivered
	Delivered bool `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"`
	// Message providing additional details
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalWorkflowResponse) Reset() {
	*x = SignalWorkflowResponse{}
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalWorkflowResponse) ProtoMessage() {}

func (x *SignalWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalWorkflowResponse.ProtoReflect.Descriptor instead.
func (*SignalWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_orchestratorpb_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *SignalWorkflowResponse) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

func (x *SignalWorkflowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RetryWorkflowRequest resets and retries a failed workflow.
type RetryWorkflowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique workflow execution ID to retry
	WorkflowId string `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// Optional run ID for a specific execution attempt
	RunId *string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3,oneof" json:"run_id,omitempty"`
	// Reason for retry
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryWorkflowRequest) Reset() {
	*x = RetryWorkflowRequest{}
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryWorkflowRequest) ProtoMessage() {}

func (x *RetryWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryWorkflowRequest.ProtoReflect.Descriptor instead.
func (*RetryWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_orchestratorpb_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *RetryWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *RetryWorkflowRequest) GetRunId() string {
	if x != nil && x.RunId != nil {
		return *x.RunId
	}
	return ""
}

func (x *RetryWorkflowRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// RetryWorkflowResponse contains the new execution identifiers.
type RetryWorkflowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New workflow execution ID (may be same as original)
	WorkflowId string `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// New run ID for the retry attempt
	RunId         string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryWorkflowResponse) Reset() {
	*x = RetryWorkflowResponse{}
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryWorkflowResponse) ProtoMessage() {}

func (x *RetryWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryWorkflowResponse.ProtoReflect.Descriptor instead.
func (*RetryWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_orchestratorpb_orchestrator_proto_rawDescGZIP(), []int{12}
}

func (x *RetryWorkflowResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *RetryWorkflowResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

// GetStatsRequest retrieves workflow execution statistics.
type GetStatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional tenant ID filter
	TenantId *string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	// Time range for statistics (default: last 24 hours)
	FromTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from_time,json=fromTime,proto3,oneof" json:"from_time,omitempty"`
	ToTime        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to_time,json=toTime,proto3,oneof" json:"to_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_orchestratorpb_orchestrator_proto_rawDescGZIP(), []int{13}
}

func (x *GetStatsRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *GetStatsRequest) GetFromTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FromTime
	}
	return nil
}

func (x *GetStatsRequest) GetToTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ToTime
	}
	return nil
}

// GetStatsResponse contains workflow execution statistics.
type GetStatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of currently running workflows
	WorkflowsRunning int64 `protobuf:"varint,1,opt,name=workflows_running,json=workflowsRunning,proto3" json:"workflows_running,omitempty"`
	// Number of workflows completed in the time range
	WorkflowsCompleted_24H int64 `protobuf:"varint,2,opt,name=workflows_completed_24h,json=workflowsCompleted24h,proto3" json:"workflows_completed_24h,omitempty"`
	// Number of workflows failed in the time range
	WorkflowsFailed_24H int64 `protobuf:"varint,3,opt,name=workflows_failed_24h,json=workflowsFailed24h,proto3" json:"workflows_failed_24h,omitempty"`
	// Number of pending activities across all workflows
	ActivitiesPending int64 `protobuf:"varint,4,opt,name=activities_pending,json=activitiesPending,proto3" json:"activities_pending,omitempty"`
	// Breakdown of workflows by type
	WorkflowsByType map[string]int64 `protobuf:"bytes,5,rep,name=workflows_by_type,json=workflowsByType,proto3" json:"workflows_by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Breakdown of workflows by status
	WorkflowsByStatus map[string]int64 `protobuf:"bytes,6,rep,name=workflows_by_status,json=workflowsByStatus,proto3" json:"workflows_by_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Average workflow duration in milliseconds
	AvgWorkflowDurationMs float64 `protobuf:"fixed64,7,opt,name=avg_workflow_duration_ms,json=avgWorkflowDurationMs,proto3" json:"avg_workflow_duration_ms,omitempty"`
	// Average activity duration in milliseconds
	AvgActivityDurationMs float64 `protobuf:"fixed64,8,opt,name=avg_activity_duration_ms,json=avgActivityDurationMs,proto3" json:"avg_activity_duration_ms,omitempty"`
	// P95 workflow duration in milliseconds
	P95WorkflowDurationMs float64 `protobuf:"fixed64,9,opt,name=p95_workflow_duration_ms,json=p95WorkflowDurationMs,proto3" json:"p95_workflow_duration_ms,omitempty"`
	// P99 workflow duration in milliseconds
	P99WorkflowDurationMs float64 `protobuf:"fixed64,10,opt,name=p99_workflow_duration_ms,json=p99WorkflowDurationMs,proto3" json:"p99_workflow_duration_ms,omitempty"`
	// Workflow throughput (completions per minute)
	WorkflowsPerMinute float64 `protobuf:"fixed64,11,opt,name=workflows_per_minute,json=workflowsPerMinute,proto3" json:"workflows_per_minute,omitempty"`
	// Activity throughput (completions per minute)
	ActivitiesPerMinute float64 `protobuf:"fixed64,12,opt,name=activities_per_minute,json=activitiesPerMinute,proto3" json:"activities_per_minute,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_orchestratorpb_orchestrator_proto_rawDescGZIP(), []int{14}
}

func (x *GetStatsResponse) GetWorkflowsRunning() int64 {
	if x != nil {
		return x.WorkflowsRunning
	}
	return 0
}

func (x *GetStatsResponse) GetWorkflowsCompleted_24H() int64 {
	if x != nil {
		return x.WorkflowsCompleted_24H
	}
	return 0
}

func (x *GetStatsResponse) GetWorkflowsFailed_24H() int64 {
	if x != nil {
		return x.WorkflowsFailed_24H
	}
	return 0
}

func (x *GetStatsResponse) GetActivitiesPending() int64 {
	if x != nil {
		return x.ActivitiesPending
	}
	return 0
}

func (x *GetStatsResponse) GetWorkflowsByType() map[string]int64 {
	if x != nil {
		return x.WorkflowsByType
	}
	return nil
}

func (x *GetStatsResponse) GetWorkflowsByStatus() map[string]int64 {
	if x != nil {
		return x.WorkflowsByStatus
	}
	return nil
}

func (x *GetStatsResponse) GetAvgWorkflowDurationMs() float64 {
	if x != nil {
		return x.AvgWorkflowDurationMs
	}
	return 0
}

func (x *GetStatsResponse) GetAvgActivityDurationMs() float64 {
	if x != nil {
		return x.AvgActivityDurationMs
	}
	return 0
}

func (x *GetStatsResponse) GetP95WorkflowDurationMs() float64 {
	if x != nil {
		return x.P95WorkflowDurationMs
	}
	return 0
}

func (x *GetStatsResponse) GetP99WorkflowDurationMs() float64 {
	if x != nil {
		return x.P99WorkflowDurationMs
	}
	return 0
}

func (x *GetStatsResponse) GetWorkflowsPerMinute() float64 {
	if x != nil {
		return x.WorkflowsPerMinute
	}
	return 0
}

func (x *GetStatsResponse) GetActivitiesPerMinute() float64 {
	if x != nil {
		return x.ActivitiesPerMinute
	}
	return 0
}

// HealthRequest checks the health of the orchestrator service.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_orchestratorpb_orchestrator_proto_rawDescGZIP(), []int{15}
}

// HealthResponse indicates the health status of the service.
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall health status
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Human-readable status message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Individual component health checks
	Components []*ComponentHealth `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty"`
	// Service version
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Service uptime in seconds
	UptimeSeconds int64 `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_orchestratorpb_orchestrator_proto_rawDescGZIP(), []int{16}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthResponse) GetComponents() []*ComponentHealth {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// ComponentHealth represents the health of a specific component.
type ComponentHealth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Component name: "temporal", "database", "embedding_service", "llm_service"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Whether the component is healthy
	Healthy bool `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Status message or error details
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Response latency in milliseconds (for connectivity checks)
	LatencyMs     *float64 `protobuf:"fixed64,4,opt,name=latency_ms,json=latencyMs,proto3,oneof" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentHealth) Reset() {
	*x = ComponentHealth{}
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentHealth) ProtoMessage() {}

func (x *ComponentHealth) ProtoReflect() protoreflect.Message {
	mi := &file_orchestratorpb_orchestrator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentHealth.ProtoReflect.Descriptor instead.
func (*ComponentHealth) Descriptor() ([]byte, []int) {
	return file_orchestratorpb_orchestrator_proto_rawDescGZIP(), []int{17}
}

func (x *ComponentHealth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentHealth) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ComponentHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ComponentHealth) GetLatencyMs() float64 {
	if x != nil && x.LatencyMs != nil {
		return *x.LatencyMs
	}
	return 0
}

var File_orchestratorpb_orchestrator_proto protoreflect.FileDescriptor

const file_orchestratorpb_orchestrator_proto_rawDesc = "" +
	"\n" +
	"!orchestratorpb/orchestrator.proto\x12\"penfold.processing.orchestrator.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x01\n" +
	"\x14StartWorkflowRequest\x12#\n" +
	"\rworkflow_type\x18\x01 \x01(\tR\fworkflowType\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x14\n" +
	"\x05input\x18\x03 \x01(\fR\x05input\x12$\n" +
	"\vworkflow_id\x18\x04 \x01(\tH\x00R\n" +
	"workflowId\x88\x01\x01B\x0e\n" +
	"\f_workflow_id\"O\n" +
	"\x15StartWorkflowResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\"b\n" +
	"\x18GetWorkflowStatusRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x1a\n" +
	"\x06run_id\x18\x02 \x01(\tH\x00R\x05runId\x88\x01\x01B\t\n" +
	"\a_run_id\"p\n" +
	"\x19GetWorkflowStatusResponse\x12S\n" +
	"\texecution\x18\x01 \x01(\v25.penfold.processing.orchestrator.v1.WorkflowExecutionR\texecution\"\xf1\x03\n" +
	"\x11WorkflowExecution\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12#\n" +
	"\rworkflow_type\x18\x03 \x01(\tR\fworkflowType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12>\n" +
	"\n" +
	"close_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tcloseTime\x88\x01\x01\x12\x1b\n" +
	"\x06result\x18\a \x01(\fH\x01R\x06result\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\b \x01(\tH\x02R\x05error\x88\x01\x01\x12\x1b\n" +
	"\ttenant_id\x18\t \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"task_queue\x18\n" +
	" \x01(\tR\ttaskQueue\x12-\n" +
	"\x12pending_activities\x18\v \x01(\x05R\x11pendingActivities\x12%\n" +
	"\x0ehistory_length\x18\f \x01(\x03R\rhistoryLengthB\r\n" +
	"\v_close_timeB\t\n" +
	"\a_resultB\b\n" +
	"\x06_error\"\x9a\x03\n" +
	"\x14ListWorkflowsRequest\x12(\n" +
	"\rworkflow_type\x18\x01 \x01(\tH\x00R\fworkflowType\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x02 \x01(\tH\x01R\x06status\x88\x01\x01\x12 \n" +
	"\ttenant_id\x18\x03 \x01(\tH\x02R\btenantId\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\x12G\n" +
	"\x0fstart_time_from\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\rstartTimeFrom\x88\x01\x01\x12C\n" +
	"\rstart_time_to\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x04R\vstartTimeTo\x88\x01\x01B\x10\n" +
	"\x0e_workflow_typeB\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_tenant_idB\x12\n" +
	"\x10_start_time_fromB\x10\n" +
	"\x0e_start_time_to\"\xca\x01\n" +
	"\x15ListWorkflowsResponse\x12S\n" +
	"\tworkflows\x18\x01 \x03(\v25.penfold.processing.orchestrator.v1.WorkflowExecutionR\tworkflows\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12$\n" +
	"\vtotal_count\x18\x03 \x01(\x03H\x00R\n" +
	"totalCount\x88\x01\x01B\x0e\n" +
	"\f_total_count\"w\n" +
	"\x15CancelWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x1a\n" +
	"\x06run_id\x18\x02 \x01(\tH\x00R\x05runId\x88\x01\x01\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reasonB\t\n" +
	"\a_run_id\"N\n" +
	"\x16CancelWorkflowResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xab\x01\n" +
	"\x15SignalWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x1a\n" +
	"\x06run_id\x18\x02 \x01(\tH\x00R\x05runId\x88\x01\x01\x12\x1f\n" +
	"\vsignal_name\x18\x03 \x01(\tR\n" +
	"signalName\x12\x1d\n" +
	"\apayload\x18\x04 \x01(\fH\x01R\apayload\x88\x01\x01B\t\n" +
	"\a_run_idB\n" +
	"\n" +
	"\b_payload\"P\n" +
	"\x16SignalWorkflowResponse\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\bR\tdelivered\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"v\n" +
	"\x14RetryWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x1a\n" +
	"\x06run_id\x18\x02 \x01(\tH\x00R\x05runId\x88\x01\x01\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reasonB\t\n" +
	"\a_run_id\"O\n" +
	"\x15RetryWorkflowResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\"\xd3\x01\n" +
	"\x0fGetStatsRequest\x12 \n" +
	"\ttenant_id\x18\x01 \x01(\tH\x00R\btenantId\x88\x01\x01\x12<\n" +
	"\tfrom_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\bfromTime\x88\x01\x01\x128\n" +
	"\ato_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x06toTime\x88\x01\x01B\f\n" +
	"\n" +
	"_tenant_idB\f\n" +
	"\n" +
	"_from_timeB\n" +
	"\n" +
	"\b_to_time\"\xa0\a\n" +
	"\x10GetStatsResponse\x12+\n" +
	"\x11workflows_running\x18\x01 \x01(\x03R\x10workflowsRunning\x126\n" +
	"\x17workflows_completed_24h\x18\x02 \x01(\x03R\x15workflowsCompleted24h\x120\n" +
	"\x14workflows_failed_24h\x18\x03 \x01(\x03R\x12workflowsFailed24h\x12-\n" +
	"\x12activities_pending\x18\x04 \x01(\x03R\x11activitiesPending\x12u\n" +
	"\x11workflows_by_type\x18\x05 \x03(\v2I.penfold.processing.orchestrator.v1.GetStatsResponse.WorkflowsByTypeEntryR\x0fworkflowsByType\x12{\n" +
	"\x13workflows_by_status\x18\x06 \x03(\v2K.penfold.processing.orchestrator.v1.GetStatsResponse.WorkflowsByStatusEntryR\x11workflowsByStatus\x127\n" +
	"\x18avg_workflow_duration_ms\x18\a \x01(\x01R\x15avgWorkflowDurationMs\x127\n" +
	"\x18avg_activity_duration_ms\x18\b \x01(\x01R\x15avgActivityDurationMs\x127\n" +
	"\x18p95_workflow_duration_ms\x18\t \x01(\x01R\x15p95WorkflowDurationMs\x127\n" +
	"\x18p99_workflow_duration_ms\x18\n" +
	" \x01(\x01R\x15p99WorkflowDurationMs\x120\n" +
	"\x14workflows_per_minute\x18\v \x01(\x01R\x12workflowsPerMinute\x122\n" +
	"\x15activities_per_minute\x18\f \x01(\x01R\x13activitiesPerMinute\x1aB\n" +
	"\x14WorkflowsByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aD\n" +
	"\x16WorkflowsByStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x0f\n" +
	"\rHealthRequest\"\xda\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12S\n" +
	"\n" +
	"components\x18\x03 \x03(\v23.penfold.processing.orchestrator.v1.ComponentHealthR\n" +
	"components\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds\"\x8c\x01\n" +
	"\x0fComponentHealth\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\"\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x01H\x00R\tlatencyMs\x88\x01\x01B\r\n" +
	"\v_latency_ms*\xc0\x01\n" +
	"\fWorkflowType\x12\x1d\n" +
	"\x19WORKFLOW_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eWORKFLOW_TYPE_EMAIL_PROCESSING\x10\x01\x12#\n" +
	"\x1fWORKFLOW_TYPE_CONTENT_INGESTION\x10\x02\x12\x1e\n" +
	"\x1aWORKFLOW_TYPE_DAILY_REVIEW\x10\x03\x12(\n" +
	"$WORKFLOW_TYPE_RELATIONSHIP_DISCOVERY\x10\x04*\xe4\x01\n" +
	"\x0eWorkflowStatus\x12\x1f\n" +
	"\x1bWORKFLOW_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_RUNNING\x10\x02\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_COMPLETED\x10\x03\x12\x1a\n" +
	"\x16WORKFLOW_STATUS_FAILED\x10\x04\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_CANCELLED\x10\x05\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_TIMED_OUT\x10\x062\xb9\b\n" +
	"\x13OrchestratorService\x12\x84\x01\n" +
	"\rStartWorkflow\x128.penfold.processing.orchestrator.v1.StartWorkflowRequest\x1a9.penfold.processing.orchestrator.v1.StartWorkflowResponse\x12\x90\x01\n" +
	"\x11GetWorkflowStatus\x12<.penfold.processing.orchestrator.v1.GetWorkflowStatusRequest\x1a=.penfold.processing.orchestrator.v1.GetWorkflowStatusResponse\x12\x87\x01\n" +
	"\x0eCancelWorkflow\x129.penfold.processing.orchestrator.v1.CancelWorkflowRequest\x1a:.penfold.processing.orchestrator.v1.CancelWorkflowResponse\x12\x84\x01\n" +
	"\rListWorkflows\x128.penfold.processing.orchestrator.v1.ListWorkflowsRequest\x1a9.penfold.processing.orchestrator.v1.ListWorkflowsResponse\x12\x87\x01\n" +
	"\x0eSignalWorkflow\x129.penfold.processing.orchestrator.v1.SignalWorkflowRequest\x1a:.penfold.processing.orchestrator.v1.SignalWorkflowResponse\x12\x84\x01\n" +
	"\rRetryWorkflow\x128.penfold.processing.orchestrator.v1.RetryWorkflowRequest\x1a9.penfold.processing.orchestrator.v1.RetryWorkflowResponse\x12u\n" +
	"\bGetStats\x123.penfold.processing.orchestrator.v1.GetStatsRequest\x1a4.penfold.processing.orchestrator.v1.GetStatsResponse\x12o\n" +
	"\x06Health\x121.penfold.processing.orchestrator.v1.HealthRequest\x1a2.penfold.processing.orchestrator.v1.HealthResponseBZZXgithub.com/otherjamesbrown/penfold/api/proto/processing/v1/orchestratorpb;orchestratorpbb\x06proto3"

var (
	file_orchestratorpb_orchestrator_proto_rawDescOnce sync.Once
	file_orchestratorpb_orchestrator_proto_rawDescData []byte
)

func file_orchestratorpb_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestratorpb_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestratorpb_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestratorpb_orchestrator_proto_rawDesc), len(file_orchestratorpb_orchestrator_proto_rawDesc)))
	})
	return file_orchestratorpb_orchestrator_proto_rawDescData
}

var file_orchestratorpb_orchestrator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_orchestratorpb_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_orchestratorpb_orchestrator_proto_goTypes = []any{
	(WorkflowType)(0),                 // 0: penfold.processing.orchestrator.v1.WorkflowType
	(WorkflowStatus)(0),               // 1: penfold.processing.orchestrator.v1.WorkflowStatus
	(*StartWorkflowRequest)(nil),      // 2: penfold.processing.orchestrator.v1.StartWorkflowRequest
	(*StartWorkflowResponse)(nil),     // 3: penfold.processing.orchestrator.v1.StartWorkflowResponse
	(*GetWorkflowStatusRequest)(nil),  // 4: penfold.processing.orchestrator.v1.GetWorkflowStatusRequest
	(*GetWorkflowStatusResponse)(nil), // 5: penfold.processing.orchestrator.v1.GetWorkflowStatusResponse
	(*WorkflowExecution)(nil),         // 6: penfold.processing.orchestrator.v1.WorkflowExecution
	(*ListWorkflowsRequest)(nil),      // 7: penfold.processing.orchestrator.v1.ListWorkflowsRequest
	(*ListWorkflowsResponse)(nil),     // 8: penfold.processing.orchestrator.v1.ListWorkflowsResponse
	(*CancelWorkflowRequest)(nil),     // 9: penfold.processing.orchestrator.v1.CancelWorkflowRequest
	(*CancelWorkflowResponse)(nil),    // 10: penfold.processing.orchestrator.v1.CancelWorkflowResponse
	(*SignalWorkflowRequest)(nil),     // 11: penfold.processing.orchestrator.v1.SignalWorkflowRequest
	(*SignalWorkflowResponse)(nil),    // 12: penfold.processing.orchestrator.v1.SignalWorkflowResponse
	(*RetryWorkflowRequest)(nil),      // 13: penfold.processing.orchestrator.v1.RetryWorkflowRequest
	(*RetryWorkflowResponse)(nil),     // 14: penfold.processing.orchestrator.v1.RetryWorkflowResponse
	(*GetStatsRequest)(nil),           // 15: penfold.processing.orchestrator.v1.GetStatsRequest
	(*GetStatsResponse)(nil),          // 16: penfold.processing.orchestrator.v1.GetStatsResponse
	(*HealthRequest)(nil),             // 17: penfold.processing.orchestrator.v1.HealthRequest
	(*HealthResponse)(nil),            // 18: penfold.processing.orchestrator.v1.HealthResponse
	(*ComponentHealth)(nil),           // 19: penfold.processing.orchestrator.v1.ComponentHealth
	nil,                               // 20: penfold.processing.orchestrator.v1.GetStatsResponse.WorkflowsByTypeEntry
	nil,                               // 21: penfold.processing.orchestrator.v1.GetStatsResponse.WorkflowsByStatusEntry
	(*timestamppb.Timestamp)(nil),     // 22: google.protobuf.Timestamp
}
var file_orchestratorpb_orchestrator_proto_depIdxs = []int32{
	6,  // 0: penfold.processing.orchestrator.v1.GetWorkflowStatusResponse.execution:type_name -> penfold.processing.orchestrator.v1.WorkflowExecution
	22, // 1: penfold.processing.orchestrator.v1.WorkflowExecution.start_time:type_name -> google.protobuf.Timestamp
	22, // 2: penfold.processing.orchestrator.v1.WorkflowExecution.close_time:type_name -> google.protobuf.Timestamp
	22, // 3: penfold.processing.orchestrator.v1.ListWorkflowsRequest.start_time_from:type_name -> google.protobuf.Timestamp
	22, // 4: penfold.processing.orchestrator.v1.ListWorkflowsRequest.start_time_to:type_name -> google.protobuf.Timestamp
	6,  // 5: penfold.processing.orchestrator.v1.ListWorkflowsResponse.workflows:type_name -> penfold.processing.orchestrator.v1.WorkflowExecution
	22, // 6: penfold.processing.orchestrator.v1.GetStatsRequest.from_time:type_name -> google.protobuf.Timestamp
	22, // 7: penfold.processing.orchestrator.v1.GetStatsRequest.to_time:type_name -> google.protobuf.Timestamp
	20, // 8: penfold.processing.orchestrator.v1.GetStatsResponse.workflows_by_type:type_name -> penfold.processing.orchestrator.v1.GetStatsResponse.WorkflowsByTypeEntry
	21, // 9: penfold.processing.orchestrator.v1.GetStatsResponse.workflows_by_status:type_name -> penfold.processing.orchestrator.v1.GetStatsResponse.WorkflowsByStatusEntry
	19, // 10: penfold.processing.orchestrator.v1.HealthResponse.components:type_name -> penfold.processing.orchestrator.v1.ComponentHealth
	2,  // 11: penfold.processing.orchestrator.v1.OrchestratorService.StartWorkflow:input_type -> penfold.processing.orchestrator.v1.StartWorkflowRequest
	4,  // 12: penfold.processing.orchestrator.v1.OrchestratorService.GetWorkflowStatus:input_type -> penfold.processing.orchestrator.v1.GetWorkflowStatusRequest
	9,  // 13: penfold.processing.orchestrator.v1.OrchestratorService.CancelWorkflow:input_type -> penfold.processing.orchestrator.v1.CancelWorkflowRequest
	7,  // 14: penfold.processing.orchestrator.v1.OrchestratorService.ListWorkflows:input_type -> penfold.processing.orchestrator.v1.ListWorkflowsRequest
	11, // 15: penfold.processing.orchestrator.v1.OrchestratorService.SignalWorkflow:input_type -> penfold.processing.orchestrator.v1.SignalWorkflowRequest
	13, // 16: penfold.processing.orchestrator.v1.OrchestratorService.RetryWorkflow:input_type -> penfold.processing.orchestrator.v1.RetryWorkflowRequest
	15, // 17: penfold.processing.orchestrator.v1.OrchestratorService.GetStats:input_type -> penfold.processing.orchestrator.v1.GetStatsRequest
	17, // 18: penfold.processing.orchestrator.v1.OrchestratorService.Health:input_type -> penfold.processing.orchestrator.v1.HealthRequest
	3,  // 19: penfold.processing.orchestrator.v1.OrchestratorService.StartWorkflow:output_type -> penfold.processing.orchestrator.v1.StartWorkflowResponse
	5,  // 20: penfold.processing.orchestrator.v1.OrchestratorService.GetWorkflowStatus:output_type -> penfold.processing.orchestrator.v1.GetWorkflowStatusResponse
	10, // 21: penfold.processing.orchestrator.v1.OrchestratorService.CancelWorkflow:output_type -> penfold.processing.orchestrator.v1.CancelWorkflowResponse
	8,  // 22: penfold.processing.orchestrator.v1.OrchestratorService.ListWorkflows:output_type -> penfold.processing.orchestrator.v1.ListWorkflowsResponse
	12, // 23: penfold.processing.orchestrator.v1.OrchestratorService.SignalWorkflow:output_type -> penfold.processing.orchestrator.v1.SignalWorkflowResponse
	14, // 24: penfold.processing.orchestrator.v1.OrchestratorService.RetryWorkflow:output_type -> penfold.processing.orchestrator.v1.RetryWorkflowResponse
	16, // 25: penfold.processing.orchestrator.v1.OrchestratorService.GetStats:output_type -> penfold.processing.orchestrator.v1.GetStatsResponse
	18, // 26: penfold.processing.orchestrator.v1.OrchestratorService.Health:output_type -> penfold.processing.orchestrator.v1.HealthResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_orchestratorpb_orchestrator_proto_init() }
func file_orchestratorpb_orchestrator_proto_init() {
	if File_orchestratorpb_orchestrator_proto != nil {
		return
	}
	file_orchestratorpb_orchestrator_proto_msgTypes[0].OneofWrappers = []any{}
	file_orchestratorpb_orchestrator_proto_msgTypes[2].OneofWrappers = []any{}
	file_orchestratorpb_orchestrator_proto_msgTypes[4].OneofWrappers = []any{}
	file_orchestratorpb_orchestrator_proto_msgTypes[5].OneofWrappers = []any{}
	file_orchestratorpb_orchestrator_proto_msgTypes[6].OneofWrappers = []any{}
	file_orchestratorpb_orchestrator_proto_msgTypes[7].OneofWrappers = []any{}
	file_orchestratorpb_orchestrator_proto_msgTypes[9].OneofWrappers = []any{}
	file_orchestratorpb_orchestrator_proto_msgTypes[11].OneofWrappers = []any{}
	file_orchestratorpb_orchestrator_proto_msgTypes[13].OneofWrappers = []any{}
	file_orchestratorpb_orchestrator_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestratorpb_orchestrator_proto_rawDesc), len(file_orchestratorpb_orchestrator_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestratorpb_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestratorpb_orchestrator_proto_depIdxs,
		EnumInfos:         file_orchestratorpb_orchestrator_proto_enumTypes,
		MessageInfos:      file_orchestratorpb_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestratorpb_orchestrator_proto = out.File
	file_orchestratorpb_orchestrator_proto_goTypes = nil
	file_orchestratorpb_orchestrator_proto_depIdxs = nil
}
