name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [pkg, penfold-go-pipeline]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true
          cache-dependency-path: ${{ matrix.module }}/go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          working-directory: ${{ matrix.module }}
          args: --timeout=5m
